########################################################
#
# CPMG pulse sequence in which each echo is summed to 
# return a single complex number per echo.
#
# 90 - delay - {180 - delay - acq}
#
# A parameter; "shift", is included to allow to allow
# data collection later in the echo, thereby reducing
# ringdown artefacts.
#
# Last modified : 13 March 2013
# Modified by : C Eccles, Magritek Ltd
# 
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y)
  interface = ["b1Freq",      "B1 Frequency (MHz)",         "0","0","tbw",   "freq",
               "ieTime",      "Inter-exp delay (ms)",       "0","1","tbw",   "float,[80,1e8]",               "t2SnrMode"  , "Run to fixed SNR",           "-0.1","3","cb",  "fixedScans,minSNR",
               "O1",          "Offset (Hz)",                "0","2","tbw",  "float",
               "t2Snr",       "SNR",                        "0.20","3","tb", "float,[0.1,1e6]",
               "90Amplitude", "90 amplitude (dB)",          "1","0","tb",    "pulseamp",
               "180Amplitude","180 amplitude (dB)",         "1","1","tb",    "pulseamp",
               "pulseLength", "Pulse length (us)",          "1","2","tb",    "float,[1,25]",
               "echoShift",   "Echo shift (us)",            "1","3","tb",    "float,[-100,100]",
               "echoTime",    "Echotime (us)",              "2","0","tb",    "sdelay",
               "nrEchoes",    "Number of echoes",           "2","1","tb",    "integer,[10,131072]",
               "dummys",      "Dummy scans",                "2","3", "tb",   "integer,[0,64]"]


# Relationships to determine remaining variable values
   relationships = ["ieTime = ieTime-40",  # Compensate for heater delay
                    "n3 = xcal*xshim/1000", # x shim value
                    "n4 = ycal*yshim/1000", # y shim value
                    "n5 = zcal*zshim/1000", # z shim value
                    "n6 = ocal*oshim/1000", # o shim value
                    "a1 = 90Amplitude",
                    "a2 = 180Amplitude",
                    "d1 = pulseLength",
                    "d2 = echoTime/2-d1-pgo",
                    "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
                    "d4 = echoTime-d1-pgo-d3",
                    "n1 = nrEchoes",
                    "n2 = nrPnts",
                    "totPnts = nrEchoes",
                    "totTime = echoTime*nrEchoes"]

# Define the tabs and their order
   tabs = ["Pulse sequence","Progress","Acquisition","T2CPMG_Processing","File Settings"]

# These parameters will be changed between experiments
   variables = [""]

# x and y spacing between controls
   dim = [180,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

  
   cleardata(n1)

   pulse(mode,a1,p1,d1)            # 90 RF pulse
  
   delay(d2)                       # 90 - 180 delay
   loop(l1,n1)
      pulse(mode,a2,p2,d1)         # 180 RF pulse
      delay(d3)                    # 180 - acq delay
      acquire("integrate",n2,d4)   # Acquire echo and wait
   endloop("l1")

   lst = endpp() # Return parameter list

# Phase cycle
   phaseList = [0,2,0,2; # -x,x,-x,x : 90 phase
                1,1,3,3; # -y,y,y,-y : 180 phase
                0,2,0,2] # -x,x,-x,x : Acquire phase

endproc(lst,tabs,interface,relationships,variables,dim,phaseList)
