procedure(save_test1,verbose,delay)

  # See load for other file types

   save("oned.emf","emf1d") # save 1D plot to meta file.
   save("twod.emf","emf2d") # save 2D plot to meta file.
   save("threed.emf","emf3d") # Save 3D plot to meta file.

   exec("oned.emf")
   pause(3)
   exec("twod.emf")
   pause(3)
   exec("threed.emf")
   pause(3)
   showwindow(getmainwindow())

   rmfile("oned.emf")
   rmfile("twod.emf")
   rmfile("threed.emf")

endproc(1,"")
