############################################################################################################
# The Simplex class
#
# Provides functions and variables to support a simplex search for optimal duplexer 
# filter component values. The simplex search is based on the Numerical Recipes code in Ch 10.
############################################################################################################


############################################################################################################
# The constructor for the Simplex class
############################################################################################################

procedure(init, self)

   self->SimplexSearch =  "simplex:SimplexSearch"
   self->Amoeba = "simplex:Amoeba"
   self->Amotry = "simplex:Amotry"
   self->Swap = "simplex:Swap"
   self->GetComponentsToModify = "simplex:GetComponentsToModify"
   self->ExtractComponentValues = "simplex:ExtractComponentValues"

   self->iteration = 0
   self->nrComponents = 6
   self->componentValues = matrix(self->nrComponents)
   self->componentDeltas = matrix(self->nrComponents)
   self->componentToOptimise = matrix(self->nrComponents)
   self->bestTargetFound = self->componentValues
   self->componentNames = ["","C1","C2","C3","L1","L2"]
   self->componentDeltaNames = ["","delC1","delC2","delC3","delL1","delL2"]

   self->optPar = null

endproc()

############################################################################################################
# The component algorithm
############################################################################################################

procedure(SimplexSearch, self, simplexStep)


   try

      maxiter = self->maxInterations
      componentDeltas = self->componentDeltas
      componentsToUse = self->componentToOptimise
      nrComponents = size(componentsToUse)
      componentValues = self->componentValues[0:nrComponents-1]

    # Collect those components which are to optimised
      (componentValuesToUse,componentDeltas,componentIndices) = self->GetComponentsToModify(componentValues,componentDeltas,componentsToUse)
      nrComponents = size(componentValuesToUse)

    # Make the parameter matrix for the simplex fitting
    #
    # Example for just x,y,z
    # Each column is a set of components to check for quality
    #
    #  | 0,    0,       0,     0,   0 |
    #  | 0,    x+dx,    x,     x,   0 |
    #  | 0,    y,    y+dy,     y,   0 |
    #  | 0,    z,       z,  z+dz,   0 |
    # 
    # Columns are component values
    # Note this algorithm is 1 based (from NR) and so ignore the first row and colum

      componentPar = matrix(nrComponents+1,nrComponents)      
      for(x = 1 to nrComponents)
         componentPar[x,~] = componentValuesToUse'
      next(x)

    # Diagonal has deltas added
      for(k = 1 to nrComponents-1)
         componentPar[k,k] = componentPar[k,k] + componentDeltas[k]
      next(k)

    # Measure the initial performance
      result = self->measurePerformance(self->psPar)

    # This records the quality (e.g. linewidth) history
      quality = matrix(nrComponents+1)

    # Measure the quality for each component set (as defined in the componentPar columns) 
      for(k = 1 to nrComponents)
         quality[k] = self->checkComponentQuality(abs(componentPar[k,~]'),componentIndices)
      next(k)

      ftol = 1e-8

    # Now apply the simplex search to optmise the components
     (optimizedComponentPar, quality, nfunc) = self->Amoeba(componentPar, quality, ftol, maxiter,componentIndices)

    # Find the best column from the simplex search
      (bestQuality, bestIndex) = min(quality[1:nrComponents])

    # Record the best component settings found
      self->ExtractComponentValues(optimizedComponentPar[bestIndex+1,~]',componentIndices)

   catch

      err = lasterror()
      if(err->type != "Throw")
         pr err
         return
      else 
         if(err->description == "Abort pressed")          
            pr "\n   Optimisation aborted\n"
         else
            pr "\n   Optimisation finished early\n"
         endif
      endif

   endtry 

endproc(self->componentValues)



############################################################################################################
# From the initial current distribution (p) adjust values to optimise y
# See Numerical Recipes in C section 10.4 (Nelder and Mead's algorithm)
############################################################################################################

procedure(Amoeba, self, p, y, ftol, maxiter, componentIndices)

   (mpts,ndim) = size(p)
   t1 = time()
   psum = matrix(ndim)
   nfunk = 0

   psum = (sum(p,"x"))'
   exitflag = 0
   while(exitflag < 1)

      if(wvExpStatus == "stop")
         throw("Abort pressed")
      endif
      if(wvExpStatus == "finish")
         throw("Finish pressed")
      endif

      ilo = 1
     # First we must determine which point is the highest (ihi) (worst), next-highest (inhi), and lowest
     # (ilo) (best), by looping over the points in the simplex.
      if(y[1] > y[2])
         ihi = 1  
         inhi = 2  
      else
         ihi = 2
         inhi = 1
      endif
      for(k = 1 to mpts-1)
         if(y[k] <= y[ilo])
            ilo = k # Initial low index
         endif
         if(y[k] > y[ihi])
            inhi = ihi
            ihi = k
         elseif((y[k] > y[inhi]) & (k!= ihi))
            inhi = k
         endif
      next(k)
      # Compute the SD of the last 10 50% linewidths. If less than 0.005 Hz exit
      # Also compute the simplex fractional range from highest to lowest and return if satisfactory.
      if(size(self->optPar) > 10)
         SD = sd(self->optPar[-10:-1])
      else
         SD = 100
      endif
      rtol = 2*abs(y[ihi]-y[ilo])/(abs(y[ihi])+abs(y[ilo])+1e-10)
      if((rtol < ftol)  | (SD < 0.005)) # If returning, put best point and value in index 1.
         (y[1],y[ilo]) = self->Swap(y[1],y[ilo])
         for(k = 1 to ndim-1)
            (p[1,k], p[ilo,k]) = self->Swap(p[1,k], p[ilo,k])
         next(k)
         exitflag = 1
         pr ("      Reached tolerance, exiting\n")
         exitwhile()
      endif

      # Too many iterations
      if (nfunk > maxiter)
         pr ("      Reaching $maxiter$ iterations, exiting\n")
         exitflag = 2
         exitwhile()
      endif

      # Finishing early
      if(wvExpStatus == "finish")
         exitflag = 2
         exitwhile()
      endif

      # User has asked to abort
      if(wvExpStatus == "stop")
         throw("Abort pressed")
      endif

      nfunk = nfunk + 2

     # Begin a new iteration. First extrapolate by a factor -1 through the face of the simplex
     # across from the high point, i.e., reflect the simplex from the high point.

      (ytry,p,y,psum) = self->Amotry(p,y,psum,ndim,ihi,-1.0,componentIndices)

      if(ytry <= y[ilo])
        # Gives a result better than the best point, so try an additional extrapolation by a
        # factor 2.
        (ytry,p,y,psum) = self->Amotry(p,y,psum,ndim,ihi,2.0,componentIndices)
      elseif(ytry >= y[inhi])
        # The reflected point is worse than the second-highest, so look for an intermediate
        # lower point, i.e., do a one-dimensional contraction.
         ysave = y[ihi]

        (ytry,p,y,psum) = self->Amotry(p,y,psum,ndim,ihi,0.5,componentIndices)
         if(ytry > ysave) # Can't seem to get rid of that high point. Better contract around the lowest (best) point
            for(k = 1 to mpts-1)
               if(k != ilo)
                  for(q = 1 to ndim-1)
                     psum[q] = 0.5*(p[k,q]+p[ilo,q])
                     p[k,q] = psum[q]
                  next(q)
                  y[k] = self->checkComponentQuality(abs(psum),componentIndices)
               endif
            next(k)
            nfunk = nfunk + ndim
            psum =  (sum(p,"x"))'
         endif

      else
         nfunk = nfunk-1
      endif
      
   endwhile
   
endproc(p,y,nfunk) # Return new matrix, quality vector and number of function evaluations performed

############################################################################################################
# Extrapolates by a factor 'fac' through the face of the simplex 'p' across from the high point, tries
# it, and replaces the high point if the new point is better.
############################################################################################################

procedure(Amotry, self,p, y, psum, ndim, ihi, fac, componentIndices)

   ptry = matrix(ndim)
   fac1 = (1-fac)/(ndim-1)
   fac2 = fac1-fac
   for(k = 1 to ndim-1)
      ptry[k] = psum[k]*fac1 - p[ihi,k]*fac2
   next(k)

   ytry = self->checkComponentQuality(abs(ptry), componentIndices)
   if(ytry < y[ihi])
      y[ihi] = ytry
      for(k = 1 to ndim-1)
         psum[k] = psum[k] + ptry[k] - p[ihi,k]
         p[ihi,k]= ptry[k]
      next(k)
   endif

endproc(ytry,p,y,psum)

############################################################################################################
# Swap variables a and b
############################################################################################################
procedure(Swap, self, a, b)

endproc(b, a)

############################################################################################################
# Reduce the component current vectors to just contain those componentvalues we are modifying
############################################################################################################

procedure(GetComponentsToModify,self, componentValues,componentDeltas,componentsToUse)

   componentValuesToUse = [0]
   componentDeltasToUse   = [0]
   componentIndicesToUse  = [0]

   nrComponents = size(componentValues)
   for(k = 1 to nrComponents-1)
      if(componentsToUse[k]) 
         componentValuesToUse = join(componentValuesToUse, [componentValues[k]])
         componentDeltasToUse = join(componentDeltasToUse, [componentDeltas[k]])
         componentIndicesToUse = join(componentIndicesToUse, [k])
      endif
   next(k)

endproc(componentValuesToUse,componentDeltasToUse,componentIndicesToUse)

############################################################################################################
# Copy the components we are modifying back to the full list
############################################################################################################

procedure(ExtractComponentValues, self, bestComponents,componentIndices)

   for(k = 0 to size(componentIndices)-1)
      self->componentValues[componentIndices[k]] = round(bestComponents[k])
   next(k)

endproc()

