procedure(loadpix_test1,verbose,delay)
   dir = getcwd()
   cd(getmacropath())

# Try loading a nonexistent file
   try 
	loadpix("nonexistent.pic")
   catch
      print "Nonexistent picture handled safely\n"
   endtry

# Try loading an existing, non-image file
   try 
	loadpix("notapicture.pic")
   catch
      print "Non-picture file handled safely\n"
   endtry
# Load and display a JPG
   loadpix("kakapo.jpg")   
   pause(1)
# Load and display a PNG
   loadpix("kakapo.png")   
   pause(1)
# Load and display a BMP
   loadpix("kakapo.bmp")
   pause(1)
   # Load and display a GIF
   loadpix("kakapo.gif")
   pause(1)

endproc(1,"")
