# fill function test - needs more cases
procedure(zerofill_test1,verbose,delay)

   x = [0:1:255]/10
   y = exp((i-0.1)*x)
   fy = ft(y)
   zffy = fill(fy,16384,"sides",0)
   zfy = 16384/256*ift(zffy)
   draw1d("false")
      multiplot("1d",1,2)
      curplot("1d",1,1)
      plot(y)
      title("Original (256 points)")
      axes("fontsize",8)
      xlabel("")
      curplot("1d",1,2)
      plot(zfy)
      title("Zero filled (16384 points)")
      axes("fontsize",8)
      xlabel("")
   draw1d("true")
   pause(delay)
 

endproc(1,"")
