########################################################
#
# This pulse sequence will implement a pulsed gradient spin-echo
# and generate an suitable user interface.
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1Freq",       "B1 Frequency (MHz)",        "0","0", "tbw", "freq",
               "repTime",      "Repetition time (ms)",      "0","1", "tbw", "reptime",
               "O1",            "Offset (Hz)",              "0","2", "tbw", "float", 
               "intWidth",     "Integration width (kHz)",   "0","3", "tbw", "float,[0,100]",
               "gradRamp",     "Gradient ramp time (us)",   "0","4", "tbw", "float,[100,10000]",

               "90Amplitude",  "90 amplitude (dB)",         "1","0", "tb",  "pulseamp",
               "180Amplitude", "180 amplitude (dB)",        "1","1", "tb",  "pulseamp",
               "pulseLength",  "Pulse length (us)",         "1","2", "tb",  "pulselength",
               "dampingTime",  "Damping time (us)",         "1","3", "tb",  "sdelay",
               "nrDummyGrad",  "Nr. of dummy gradients",    "1","4", "tb",  "integer, [0,10]",
               "gradSpacing",  "Linear x-axis sampling",    "1","5", "cb",  "linear,squared",

               "bDelta",       "Big DELTA (us)",            "2","0", "tb",  "sdelay",
               "lDelta",       "Little delta (us)",         "2","1", "tb",  "sdelay",
               "gradStab",     "Grad. stab. delay (us)",    "2","2", "tb",  "sdelay",
               "gradDiffTpm",  "Maximum gradient (T/m)",    "2","3", "tb",  "float,[-0.5,0.5]",
               "dirDiff",       "",                         "2.3","3", "tm",  "[\"x\",\"y\",\"z\"]",            
               "nrSteps",      "Nr. of gradient steps",     "2","4", "tb",  "float,[1,512]"]

# Relationships to determine remaining variable values
   relationships = [ "d300 = 2.5",
                     "n300 = round(gradRamp/d300)",
                     "a1 = 90Amplitude",
                     "a2 = 180Amplitude",
                     "d4 = dampingTime",
                     "d1 = pulseLength",
                     "d5 = lDelta",
                     "d6 = gradStab",                    
                     "d2 = (bDelta-d1-d1/2-d5-2*gradRamp-2*pgo)/2",
                     "d3 = (bDelta-d1+d1/2-d5-2*gradRamp-2*d6 )/2",
                     "n40  = PGSE:convertDirToChannel(dirDiff)", 
                    "(gDiffAmp,gDiffAmpShim) = PGSE:setImageGradients(dirDiff,gradDiffTpm,xshim,yshim,zshim,xcal,ycal,zcal)",                     
                     "n41  =  gDiffAmpShim",
                     "n41a =  gDiffAmpShim",                   
                     "n1 = nrPnts",
                     "totPnts = nrPnts",
                     "totTime = acqTime"]

# Define the tabs and their order
   tabs = ["Pulse_sequence","Progress","Acquisition","Processing_Display_Std","File_Settings"]

# These parameters will be changed between experiments
   variables = ["a1","a2","n41"]

# dx,dy
   dim = [170,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list


  # Main pulse program
   pulse(mode,a1,p1,d1)         # 90 pulse

   gradramp(n40,n41a,n41,n300,d300)     # Set Diffusion gradient 
   delay(d5)                            # little delta
   gradramp(n40,n41,n41a,n300,d300)     # Set o shim 

   delay(d2)                    # Big delta delay
   
   pulse(mode,a2,p2,d1)         # 180 pulse

   delay(d3)                    # Big delta delay

   gradramp(n40,n41a,n41,n300,d300)     # Set Diffusion gradient 
   delay(d5)                            # little delta
   gradramp(n40,n41,n41a,n300,d300)     # Set o shim 

   delay(d6)                    # gradient stabilisation delta
   acquire("overwrite",n1)      # Acquire echo and wait

   lst = endpp() # Return parameter list

# Phase cycle
   phaseList = [0,2; # +y,-y,-y,+y : 90 phase
                1,1; # +x,+x,+y,+y : 180 phase
                0,2] # -x,+x,-x,+x : Acquire phase

endproc(lst,tabs,interface,relationships,variables,dim,phaseList)