procedure(segments3d_test1,verbose,delay)

   N = 20
   s1 = matrix(6,N)
   s2 = matrix(6,N)
   s3 = matrix(6,N)
   s4 = matrix(6,N)
   
   for (x = 0 to N-1)
     s1[~,x] = [x,0,0,N-1-x,0,0]
     s2[~,x] = [x,0,N-1,x,0,0]
     s3[~,x] = [x,N-1,0,x,0,0]
     s4[~,x] = [x,N-1,N-1,N-1-x,0,0]
   next (x)
   
   draw3d("false")
   clear3d()
   color3d([1,1,0])
   segments3d(s1)
   segments3d(s2)
   segments3d(s3)
   segments3d(s4)
   rotate3d(0,0,0)
   shift3d(-N/2,-N/2,0)
   viewdistance(3*N)
   draw3d("true")
   pause(delay)

endproc(1,"")
