#####################################################################
# This example script sets pin 3 (AD1) on the TTL trigger box
# to high and then returns. 
# It could be used to trigger a batch process.
#####################################################################

procedure(MouseMove, parameters=null) 
 
   if(EditIfShiftPressed(getmacropath(),getmacroname()))
      return
   else # Add the experiment with interface
      if(parameters == null)
         parameters = ["distance=0","position=0"] 
      endif
      gExpt->addExperiment(getmacropath(),rmext(getmacroname()),parameters)
   endif

endproc()

###########################################################
# The interface control(s) required by Expert when loading
# data from a experimental result
###########################################################

procedure(interface)

   ctrlLayout = ["exptDiv",      "Coarse control",          "dv",           "",       "",
                 "home",         "Move to Home",            "bt",  "string", "homeBD()", 
                 "service",      "Move to Service",         "bt",  "string", "serviceBD()",
                 "exptDiv",      "Fine control",            "dv",           "",       "",
                 "distance",     "Distance to move",        "tb",  "float",   "",
                 "move",         "Move lift",               "bt",  "string", "moveBD()",
                 "position",     "Current position (um)",   "tb",  "readonly_string",  ""]

   plotLayout = listto2d(["pt1"])

endproc(ctrlLayout, plotLayout)

###########################################################
# Move the lift to the service position
###########################################################

procedure(serviceBD)

   ftdiopen("FTDIMagritek001",0xFF) # All TTL pins are outputs
   ftdiwrite(0x01)
   pause(0.02)
   ftdiwrite(0x01) # Was 0x21
   pause(0.001)
   ftdiwrite(0)
   ftdiclose()

endproc()


###########################################################
# Move the lift to the home position
###########################################################

procedure(homeBD)

   ftdiopen("FTDIMagritek001",0xFF) # All TTL pins are outputs
   ftdiwrite(0x02) 
   pause(0.02)
   ftdiwrite(0x02) # Was 0x42
   pause(0.001)
   ftdiwrite(0)
   ftdiclose()
   n = findobj(0,"name","position")
   if(n > 0)
      setpar(0,n,"text","0")
   else
      pr("Position = 0 um\n")
   endif

endproc()

###########################################################
# Move the lift a certain distance up or down relative to 
# the current position
###########################################################

procedure(moveBD, distance=null, position=null)

   if(position == null)
      assignlist(getctrlvalues(0))
   endif

   n = findobj(0,"name","position")
   if(n > 0)
      position = getpar(0,n,"value")
   endif

   y = distance
   if(y == 0)
      return
   endif
   y = abs(y)

   ftdiopen("FTDIMagritek001",0xFF) # All TTL pins are outputs

   if(sign(distance) > 0) # Move up

      slowSteps = trunc((y-50*trunc(y/50))/10)
      :moveUpFast(trunc(y/50),n,position)
      position = position + 50*trunc(y/50)
      :moveUp(slowSteps,n,position)
      position = position + 10*slowSteps

   else # Move down

      slowSteps = trunc((y-50*trunc(y/50))/10)
      :moveDownFast(trunc(y/50),n,position)
      position = position - 50*trunc(y/50)
      :moveDown(slowSteps,n,position)
      position = position - 10*slowSteps

  endif

   ftdiclose()

endproc()


###########################################################
#  Move the lift up in small steps
###########################################################

procedure(moveUp, steps, n, p )

   for(s = 0 to steps-1)
   
      ftdiwrite(0x08) 
      pause(0.02)
      ftdiwrite(0x08) # 0x18
      pause(0.001)
      ftdiwrite(0)
      p = p + 10 
      if(n > 0)
         setpar(0,n,"text","$p$")
      else
         pr("Position = $p$ um\n")
      endif
      pause(0.25)
   next(s)

endproc()

###########################################################
#  Move the lift up in large steps
###########################################################

procedure(moveUpFast, steps, n, p)

   for(s = 0 to steps-1)

      ftdiwrite(0x80) 
      pause(0.02)
      ftdiwrite(0x88) 
      pause(0.001)
      ftdiwrite(0)
      p = p + 50 
      if(n > 0)
         setpar(0,n,"text","$p$")
      else
         pr("Position = $p$ um\n")
      endif
      pause(0.35)
   next(s)

endproc()

###########################################################
#  Move the lift down in small steps
###########################################################

procedure(moveDown, steps, n, p)

   for(s = 0 to steps-1)
   
      ftdiwrite(0x04) 
      pause(0.02)
      ftdiwrite(0x04) #0x24
      pause(0.001)
      ftdiwrite(0)
      p = p - 10 
      if(n > 0)
         setpar(0,n,"text","$p$")
      else
         pr("Position = $p$ um\n")
      endif
      pause(0.25)
   next(s)

endproc()

###########################################################
#  Move the lift down in large steps
###########################################################

procedure(moveDownFast, steps, n, p)

   for(s = 0 to steps-1)

      ftdiwrite(0x80) 
      pause(0.02)
      ftdiwrite(0x84) 
      pause(0.001)
      ftdiwrite(0)
      p = p - 50 
      if(n > 0)
         setpar(0,n,"text","$p$")
      else
         pr("Position = $p$ um\n")
      endif
      pause(0.35)
   next(s)

endproc()


########################################################
# Just cycle the progress bar once each 5 seconds
# since we don't know when the trigger will come
########################################################

procedure(expectedDuration, guipar)

   assignstruct(guipar)
   d = 0.1

endproc(d)