########################################################
# 
# Slice selective spin-echo imaging
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1Freq",        "B1 Frequency (MHz)",        "0","0",   "tbw", "freq",
               "repTime",       "Repetition time (ms)",      "0","1",   "tbw", "float,[1,4e004]",
               "O1",            "Offset (Hz)",               "0","2",   "tbw", "float",
               "SPType",        "Soft pulse shape",          "0","3", "tm",  "60,[\"sinc3\",\"sinc5\",\"gauss\",\"rect\"]",
               "pulseLength90", "90 pulse length (us)",      "0","4", "tb",  "pulselength",
               "a1",            "90 amplitude (dB)",         "0","5", "tb",  "pulseamp",
         
               "estTimeR",      "estabil. Time read (us)",   "1","0", "tb",  "sdelay",
               "acqShiftRead",  "acqShiftRead (us)",         "1","1", "tb",  "float,[-1000,1000]",
               "sliceComp",     "sliceComp(us)",             "1","2", "tb",  "float,[-1000,1000]",
               "repTimeFlash",  "repTimeFlash (ms)",         "1","3", "tb",  "float,[2,1000]",
               "nrDummyScans",  "nrDummyScans",              "1","4", "tb",  "integer,[0,20]",
               "phDss90",       "phase dss 90",              "1","5", "tb",  "float,[-1000,1000]",

               "FoVRead",       "FoV Read (mm)",             "2","0", "tb",  "float,[-10000,10000]",
               "FoVPhase1",     "FoV Phase1 (mm)",           "2","1", "tb",  "float,[-10000,10000]",
               "nrStepsP1",     "nr. pixels phase1",         "2","2", "tb",  "integer,[1,500]",
               "FoVPhase2",     "FoV Phase2 (mm)",           "2","3", "tb",  "float,[-10000,10000]",
               "nrStepsP2",     "nr. pixels phase2",         "2","4", "tb",  "integer,[1,500]",
               "sliceTickness", "Slice thickness (mm)",      "2","5", "tb",  "float,[0,10000]",
               "sliceShift",    "Slice shift (mm)",          "2","6", "tb",  "float,[-10000,10000]",

               "dirRead",       "",                          "2.3","0", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase1",     "",                          "2.3","1", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase2",     "",                          "2.3","3", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirSlice",      "",                          "2.3","5", "tm",  "[\"x\",\"y\",\"z\"]"]      

 # Relationships to determine remaining variable values
  relationships = [ "d600 = 2",     
                    "n600 = round(pulseLength90/d600)",
                    "(t1,t2,gfac) = B1NutSoft:getRFPulse(SPType,a1,n600)",
                    "rampDur = 100",
                    "d300 = 2.5",
                    "n300 = round(rampDur/d300)",
                    "d101 = 100",
                    "d3   = 100",
                    "phDur = d3+4*rampDur",
                    "(del6,del69)   = Flash_3D:getRewindSliceDelay(pulseLength90,sliceComp,rampDur)",
                    "d69=del69",
                    "d6=del6",   
                    "d4   = estTimeR", 
                    "d5   = 1000*acqTime-rxLat + 1000",
                    "d44  = pulseLength90 +d101+d69+pgo+2*rampDur+phDss90",
                    "d10  = repTimeFlash*1000 - d101-d69 -pulseLength90-d3-d4-d5-d6-d44-12*rampDur",
                    "n10  = Flash_3D:convertDirToChannel(dirRead)",
                    "n20  = Flash_3D:convertDirToChannel(dirPhase1)",
                    "n40  = Flash_3D:convertDirToChannel(dirPhase2)",
                    "n30  = Flash_3D:convertDirToChannel(dirSlice)",
                    "(gReadAmp,gReadAmpShim,gPhaseAmp1,gPhaseAmpShim1,gPhaseAmp2,gPhaseAmpShim2,gSliceAmp,gSliceAmpShim,sliceOffSet) = Flash_3D:setImageGradients(dirRead,dirPhase1,dirPhase2,dirSlice,FoVRead,FoVPhase1,FoVPhase2,phDur,sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)",
                    "n31a =  gSliceAmpShim", 
                    "n31  =  gSliceAmp+gSliceAmpShim", 
                    "n32  = -gSliceAmp+gSliceAmpShim",
                    "n11a =  gReadAmpShim",
                    "readGradFac = (0.5*rampDur+d4+1000*acqTime/2-rxLat+acqShiftRead)/(d3+4*rampDur)",
                    "n12a =  gReadAmpShim",
                    "n11  = -readGradFac*gReadAmp+gReadAmpShim",
                    "n12  =  gReadAmp+gReadAmpShim",
                    "n21a =  gPhaseAmpShim1",
                    "t21  =  ([0:1:nrStepsP1]-nrStepsP1/2+1/2)*gPhaseAmp1/((nrStepsP1-1)/2) + gPhaseAmpShim1",         
                    "n41a =  gPhaseAmpShim2",       
                    "n41  =  gPhaseAmp2 + gPhaseAmpShim2",
                    "f1   =  b1Freq+O1/1e6+sliceOffSet",
                    "f2   =  b1Freq+O1/1e6", 
                    "f3   =  b1Freq+O1/1e6-sliceOffSet", 
                    "n0   =  nrDummyScans",                   
                    "n1   =  nrStepsP1",
                    "n2   =  nrPnts",              
                    "totPnts = nrPnts*nrStepsP1",
                    "totTime = repTimeFlash*nrStepsP1"]

# Define the tabs and their order
   tabs = ["Pulse sequence","Acquisition","Processing+Display","File Settings"]

# These parameters will be changed between experiments
   variables = ["n41"]

# dx,dy
   dim = [170,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

# dummy scans
   loop(l0,n0)

      settxfreq(f1)                         
      gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
         delay(d101)                          # stabilization time slice
         shapedrf(mode,t1,t2,p1,n600,d600)    # 90 soft pulse
         delay(d69)
      gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF
      settxfreq(f2) 
      gradramp(n30,n31a,n32,n300,d300)        # SLICE gradient ON 
         delay(d6)
      gradramp(n30,n32,n31a,n300,d300)        # SLICE gradient OFF                      
      
      gradramp(n10,n11a,n11,n300,d300)        # READ gradient ON
      gradramp(n20,n21a,n21a,n300,d300)       # PHASE1 gradient ON
      gradramp(n40,n41a,n41a,n300,d300)       # PHASE2 gradient ON
         delay(d3)
      gradramp(n10,n11,n11a,n300,d300)        # READ gradient OFF
      gradramp(n20,n21a,n21a,n300,d300)       # PHASE1 gradient OFF
      gradramp(n40,n41a,n41a,n300,d300)       # PHASE2 gradient OFF
   
      gradramp(n10,n12a,n12,n300,d300)        # READ gradient ON
         delay(d4)
         acquire("overwrite",n2,d5)
      gradramp(n10,n12,n12a,n300,d300)        # READ gradient OFF

      settxfreq(f3)                         
         delay(d44)           
      settxfreq(f2) 

      delay(d10)

   endloop(l0)

 # end dummy scans

   setindex(t21,0); 

   loop(l1,n1)

      settxfreq(f1)                         
      gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
         delay(d101)                          # stabilization time slice
         shapedrf(mode,t1,t2,p1,n600,d600)    # 90 soft pulse
         delay(d69)
      gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF
      settxfreq(f2) 
      gradramp(n30,n31a,n32,n300,d300)        # SLICE gradient ON 
         delay(d6)
      gradramp(n30,n32,n31a,n300,d300)        # SLICE gradient OFF                      
      
      gradramp(n10,n11a,n11,n300,d300)        # READ gradient ON
      gradramp(n20,n21a,t21,n300,d300)        # PHASE1 gradient ON
      gradramp(n40,n41a,n41,n300,d300)        # PHASE2 gradient ON
         delay(d3)
      gradramp(n10,n11,n11a,n300,d300)        # READ gradient OFF
      gradramp(n20,t21,n21a,n300,d300)        # PHASE1 gradient OFF
      gradramp(n40,n41,n41a,n300,d300)        # PHASE2 gradient OFF
   
      gradramp(n10,n12a,n12,n300,d300)        # READ gradient ON
         delay(d4)
         acquire("append",n2,d5)
      gradramp(n10,n12,n12a,n300,d300)        # READ gradient OFF

      settxfreq(f3)                         
         delay(d44)           
      settxfreq(f2) 

      delay(d10)

    incindex(t21);

   endloop(l1)


   lst = endpp() # Return parameter list

# Phase cycle list
   phaseList = [0; # +x,-x : 90 phase
                0] # +x,-x : Acquire phase


endproc(lst,tabs,interface,relationships,variables,dim,phaseList)