
procedure(axis3d_test1,verbose,delay)

clear3d
axispar3d(0.5,1,1,2)
color3d([1,1,0])
axis3d("x",[0,20],0,0,[0,1],"x")
axis3d("y",[0,20],0,0,[0,2],"y")
axis3d("z",[0,20],0,0,[0,5],"z")
viewdistance(70)
rotate3d(-18,326,0)
pause(delay)

 

clear3d
axispar3d(0.5,1,0.8,1)
color3d([0,1,1])
axis3d("x",[0,20],10,10,[-1,1],"x","positive_end")
axis3d("y",[0,20],10,10,[-1,1],"y","positive_end")
axis3d("z",[0,20],10,10,[-1,1],"z","positive_end")
shift3d(-10,-10,-10)
viewdistance(50)
rotate3d(-18,326,0)
pause(delay)

endproc(1,"")