########################################################
#
# Frequency sweep pulse program used for probe tuning
#
########################################################

procedure(pulse_program,dir,mode)

# Modify mode for wobble
  mode = "w" + mode

# Interface description (name, label, x, y)
  interface = ["repTime",   "Repetition time (ms)",     "0","0","tb", "reptime",
               "lowFreq",   "Lower frequency (MHz)",    "1.1","0","tb", "freq",
               "upFreq",    "Upper frequency (MHz)",    "1.1","1","tb", "freq",
               "freqSteps", "Number of freq. steps",    "1.1","2","tb", "integer",
               "a1",        "RF amplitude",             "2","1","tb", "float,[-72,-30]"]

# Relationships to determine remaining variable values
   relationships = ["n1 = nrPnts",
                    "n2 = freqSteps",
                    "b1Freq = lowFreq",
                    "f1 = lowFreq",
                    "f2 = 10*f1",
                    "f3 = (upFreq-lowFreq)/(freqSteps-1)",
                    "f4 = 10*f3",
                    "totPnts = n2",
                    "d1 = 10",
                    "d2 = 2000",
                    "totTime = acqTime",
                    "specialMode = \"wobble\""]

# Define the tabs and their order
   tabs = ["Pulse sequence","Acquisition","amplitude_control","File Settings"]

# These parameters will be changed between experiments
   variables = [""]

# x and y spacing between controls
   dim = [170,26]

# Pulse sequence
   initpp(dir)                    # Reset internal parameter list

      cleardata(n2)                # Clear data space
   #   settxfreq(f1)                # Set the start Tx freq.
   #   setrxfreq(f2)                # Set the start Rx freq.
    #  txon(mode,a1,p1)             # Switch on Tx in wobble mode
      loop(l1,n2)                  # Measure at n2 frequency steps
         txon(mode,a1,p1)          # Switch on Tx 
         delay(d1)                 # Wait for stability
         acquire("integrate",n1)   # Acquire and integrate n1 data points
         txoff(w)                  # Switch off the Tx
         inctxfreq(f3)             # Increment Tx frequency
         incrxfreq(f4)             # Increment Rx frequency
         delay(d2)                 # Wait for HPA to recover
      endloop(l1)                  # Next measurement
      txoff(w)                     # Switch off the transmitter

   lst = endpp()                  # Return parameter list

# Phase cycle
   phaseList = [0;
                0]

endproc(lst,tabs,interface,relationships,variables,dim,phaseList)
