procedure(submatrix_test1,verbose,delay)

# 1D real test
   m = noise(100)
   v = noise(10)
   m = insert(m,v,20,0)
   n = submatrix(m,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #1")
   endif

# 2D real test
   m = noise(100,100)
   v = noise(10,10)
   m = insert(m,v,20,20)
   n = submatrix(m,20,29,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #2")
   endif

# 3D real test
   m = noise(100,100,100)
   v = noise(10,10,10)
   m = insert(m,v,20,20,20)
   n = submatrix(m,20,29,20,29,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #3")
   endif

# 1D complex test
   m = noise(100)+i*noise(100)
   v = noise(10)+i*noise(10)
   m = insert(m,v,20,0)
   n = submatrix(m,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #4")
   endif

# 2D real test
   m = noise(100,100)+i*noise(100,100)
   v = noise(10,10)+i*noise(10,10)
   m = insert(m,v,20,20)
   n = submatrix(m,20,29,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #5")
   endif

# 3D real test
   m = noise(100,100,100)+i*noise(100,100,100)
   v = noise(10,10,10)+i*noise(10,10,10)
   m = insert(m,v,20,20,20)
   n = submatrix(m,20,29,20,29,20,29)
   if(n != v)
       return(0, "Invalid result for: submatrix_test1 #6")
   endif

endproc(1,"")
