#####################################################################
# Update information about current probehead, spacer, etc.
#
# Based on corresponding macro from PMXX MOUSE Prospa folder
#
# Initial version
#
# - added callback to set up the lists in the interface
# - it uses the "selectedProbeHEad.par" file to fill in parameters
#
# Bulat Gizatullin
# August 2026
#
# Copyright (c) Magritek Ltd 2025
#####################################################################

procedure(selectProbeHead, parameters=null) 
 
   if(EditIfShiftPressed(getmacropath(),getmacroname()))
      return
   else # Add the experiment with interface


   (selectedProbeHead,error) = :checkSelectedProbeHeadFile()

      if (error)
         return()
      elseif ((parameters == null)&(selectedProbeHead != null))

         assignlist(selectedProbeHead)
         spacerName = rmsubstr(Spacer,".par")
         print ("The current selected probe configuration is:\n Sensor: $Sensor$\n Probe:  $Probe$\n Spacer: $spacerName$\n")

         sensorList = :getParList("Sensor")

         selectText = "select.."

         if (size(sensorList) == 1)

            probeList = :getParList("Probe",sensorList[0])
         else
            Sensor  = selectText
            probeList = ""
         endif


         if ((size(probeList) == 1) & (size(sensorList) == 1))
            Probe = probeList[0]
         else
            Probe  = selectText
         endif

         parameters = [
                       "Sensor  = \"$Sensor$\"",
                       "Probe   = \"$Probe$\"",
                       "Spacer  = \"$selectText$\""
                      ] 

      elseif ((parameters == null)&(selectedProbeHead == null))

         print ("The current selected probe configuration is not set up! Run selectProbeHead protocol!\n")
         selectText = "select.."
         selectText1 = "select previous.."
         parameters = [
                       "Sensor  = \"$selectText$\"",
                       "Probe   = \"$selectText1$\"",
                       "Spacer  = \"$selectText1$\""
                      ] 
      endif

      gExpt->addExperiment(getmacropath(),rmext(getmacroname()),parameters)
   endif

#pr "end of start\n"

endproc()

###########################################################
# The interface control(s) required by Expert when loading
# data from a experimental result
###########################################################

procedure(interface)

#pr "in INTERFACE \n"
#   parameters = getctrlvalues(0)
#pr parameters
#
#   try
##     (sensorList, probeList, spacerList) = :getHardwareLists() # lists are for the menus, values from that list are in updateUI procedure
#           (sensorList, probeList, spacerList) = :getProbeHeadsList() # just get any possible configuration to set up interface
#   catch
#         pr lasterror()
#     (sensorList, probeList, spacerList) = :getSelectedHardwareLists() # if selected from the menu and there is another protocol in the gui
#
#   endtry

   sensorList = :getParList("Sensor")
   
   
   if ((size(sensorList)) == 1)
      probeList = :getParList("Probe",sensorList[0])
   
   else
      probeList = ""
   endif
   
   
   if ((size(probeList) == 1) & (size(sensorList) == 1))
      spacerList = :getParList("Spacer",sensorList[0],probeList[0])
   else
      spacerList = ""
   endif


   ctrlLayout = ["",             "Hardware configuration","dv",            "",                   "",
#                 "Sensor",       "Sensor",               "tm_wide,proc",   "readonly_string",    "$sensorList$", 
#                 "Probe",        "Probe",                "tm_wide,proc",   "readonly_string",    "", 
#                 "Spacer",       "Spacer",               "tm_wide",   "readonly_string",    "", 
                 "Sensor",       "Sensor",               "tm_wide,proc",   "readonly_string",    "$sensorList$", 
                 "Probe",        "Probe",                "tm_wide,proc",   "readonly_string",    "$probeList$", 
                 "Spacer",       "Spacer",               "tm_wide",   "readonly_string",    "$spacerList$", 
                 "",             "Edit parameters list", "bt",             "string",             "editProbeHead()"
                  ]

   plotLayout = ["pt1"]

endproc(ctrlLayout, plotLayout)


########################################################
# Parameter callback - called when protocol or parameter
# to change menu selected
########################################################

procedure(parameterCallBack)

   parameters = getctrlvalues(0)
   assignlist(parameters)

   ctrlName = parentCtrl->name

  if(parentCtrl->event == "enter" | parentCtrl->event == "undefined")

      bak = getcwd()
      try
         :upDateParameterUI(ctrlName)
      catch
         pr lasterror()
      endtry
      cd(bak)

   endif
  
endproc()


########################################################
# Regenerate the UI 
#######################################################

procedure (upDateParameterUI,ctrlName)

      macroDir = getmacropath()

      cd(getmacropath())
      cd(".ProbeHeads")
      sensorDir = macroDir + "\.ProbeHeads"


      if (ctrlName == "Sensor")
               
         obj = findobj(0,"name","Sensor")
         Sensor = getpar(0, obj,"text")
#         pr "Sensor in call back is $Sensor$\n"

         probeList = :getParList("Probe",Sensor)

         obj = findobj(0,"name","Probe")
         setpar(0,obj,"menu",probeList) #set up new list for Probe based on Sensor
         setpar(0,obj,"text","select..") # reset selected value for Probe


         obj = findobj(0,"name","Spacer")
         setpar(0,obj,"menu",[""]) #set up new list for Probe based on Sensor
         setpar(0,obj,"text","select..") # reset selected value for Probe


      elseif (ctrlName == "Probe")

         obj = findobj(0,"name","Sensor")
         Sensor = getpar(0, obj,"text")

         obj = findobj(0,"name","Probe")
         Probe = getpar(0, obj,"text")

#         pr "Sensor in callback is $Sensor$\n"
#         pr "Probe in callback is $Probe$\n"

         spacerList = :getParList("Spacer",Sensor,Probe)

         obj = findobj(0,"name","Spacer")
         setpar(0,obj,"text","select..") # reset selected value for Probe
         setpar(0,obj,"menu",spacerList) #set up new list for Probe based on Sensor

      endif

    


  #    gExpt->addExperiment(getmacropath(),rmext(getmacroname()),parameters)

endproc()



################################################################
# Come here when the run button is pressed
################################################################

procedure(backdoor, parameters)

   assignstruct(parameters)

   bak = getcwd() 
   
   macroDir = getmacropath()
   spacerDir = macroDir + "\.ProbeHeads" + "\\$Sensor$" + "\\$Probe$"
   cd(spacerDir)     

   if (isfile(Spacer))
      
      newProbeHead = load(Spacer)
      macroDir = getmacropath()
      sensorDir = macroDir + "\.ProbeHeads"
      setcwd(sensorDir)
      spacerName = rmsubstr(Spacer,".par")
      if(query("Warning","The following configuration will be set up:\r Sensor: $Sensor$\r Probe:  $Probe$\r Spacer: $spacerName$\rDo you wish to continue?","no") == "no")
         return
      endif      
      save("selectedProbeHead.par", newProbeHead)

      message("info","The probeHead has been updated to:\r Sensor: $Sensor$\r Probe:  $Probe$\r Spacer: $spacerName$","info")
      print ("The parameters for the probehead $Sensor$/$Probe$/$Spacer$ are set up. \n")
   else   
      message("Error","No valid configuration is selected!\rFollow prevoius instructions or contact Magritek!","error")
      return()
   endif
   cd(bak)

endproc()



###########################################################
# Edit probe head file in the current editor window
###########################################################

procedure(editProbeHead)


   (selectedProbeHead,error) = :checkSelectedProbeHeadFile(queries="no")

   if (error)
      return()
   endif

   obj = findobj(0,"name","Spacer")
   Spacer = getpar(0, obj,"text")

   obj = findobj(0,"name","Probe")
   Probe = getpar(0, obj,"text")

   obj = findobj(0,"name","Sensor")
   Sensor = getpar(0, obj,"text")


   bak = getcwd() 
   macroDir = getmacropath()

   spacerDir = macroDir + "\.ProbeHeads" + "\\$Sensor$" + "\\$Probe$"

   cd (spacerDir)

   if (isfile(Spacer))
      try
         editorWin()
         edit(Spacer)
      catch
         pr lasterror()
      endtry
   else
      message("Error","The Spacer is not defined!\rSelect Spacer configuration form the menu!","error")
      return()
   endif

   cd(bak)

endproc()


###########################################################
# Get the hardware parameters to the interface
# when selected from the menu
###########################################################

procedure(getSelectedHardwareLists)

   bak = getcwd() 

   cd(getmacropath())
   cd(".ProbeHeads")

   if(isfile("selectedProbeHead.par"))   

         selectedProbeHead = load("selectedProbeHead.par")
         assignlist(selectedProbeHead)
      
         obj = findobj(0,"name","Sensor")
      
         macroDir = getmacropath()
         sensorDir = macroDir+"\\.ProbeHeads"
         cd(sensorDir)
         sensorList = getdirlist(".")
      
         obj = findobj(0,"name","Probe")
         probeDir = sensorDir + "\\$Sensor$"
         cd(probeDir)
         probeList = getdirlist(".")
      
      
         obj = findobj(0,"name","Spacer")
         spacerDir = probeDir + "\\$Probe$"
         cd(spacerDir)
         spacerList = getfilelist(".")

   else
         (sensorList, probeList, spacerList) = :getProbeHeadsList() # lists are for the menus, values from that list are in updateUI procedure
   endif

   cd(bak)

endproc(sensorList, probeList, spacerList)


###########################################################
# Get the hardware parameters to the interface
# after callback
###########################################################

procedure(getHardwareLists)
pr "in getHardwareLists\n"
   bak = getcwd() 

   obj = findobj(0,"name","Sensor")
   Sensor = getpar(0, obj,"text")

   macroDir = getmacropath()
   sensorDir = macroDir+"\\.ProbeHeads"
   cd(sensorDir)
   sensorList = getdirlist(".")

   obj = findobj(0,"name","Probe")
   Probe = getpar(0, obj,"text")
   probeDir = sensorDir + "\\$Sensor$"
   cd(probeDir)
   probeList = getdirlist(".")

   obj = findobj(0,"name","Spacer")
   Spacer = getpar(0, obj,"text")
   spacerDir = probeDir + "\\$Probe$"
   cd(spacerDir)
   spacerList = getfilelist(".")

   cd(bak)

endproc(sensorList, probeList, spacerList)

###########################################################
# Get the probe heads list from the .ProbeHeads
# folder structure
###########################################################

procedure(getProbeHeadsList)

   bak = getcwd() 



   macroDir = getmacropath()

   lsList1 = ls("PM*","directories")
  # pr lsList1
   Sensor = lsList1[0]   

#   return()

   sensorDir = macroDir+"\\.ProbeHeads"
   cd(sensorDir)
   sensorList = getdirlist(".")


   Sensor = sensorList[0]   

#   obj = findobj(0,"name","Probe")
#   Probe = getpar(0, obj,"text")

   probeDir = sensorDir + "\\$Sensor$"
   cd(probeDir)
   probeList = getdirlist(".")
   Probe = probeList[0]


   spacerDir = probeDir + "\\$Probe$"


   cd(spacerDir)
   spacerList = getfilelist(".")

   cd(bak)

endproc(sensorList, probeList, spacerList)


#################################################################
# Get the list from the .ProbeHead folder content
#################################################################

procedure(getParList,parName,Sensor = null,Probe = null)

     (selectedProbeHead,error) = :checkSelectedProbeHeadFile(queries="no")
      
      if (error)
         return(null)
      endif

      macroDir = getmacropath()
      sensorDir = macroDir+"\\.ProbeHeads"

   if (parName == "Sensor")
     # parList = ["Sensor1","Sensor2","Sensor3"]
   
      cd(sensorDir)
      parList = getdirlist(".")
   
   elseif (parName == "Probe")
      if (Sensor == null)
         pr "Error: sensor is NULL\n"
         return(null)
      endif
 
      if(issubstr(Sensor,"PM"))
         probeDir = sensorDir + "\\$Sensor$"
         cd(probeDir)
         parList = getdirlist(".")
   
      else
         message("Error","Select Sensor first!","error")
         return(null)
      endif

   elseif (parName == "Spacer")

      if (Sensor == null)
         pr "Error: sensor is NULL\n"
         return(null)
      endif

      if (Probe == null)
         pr "Error: sensor is NULL\n"
         return(null)
      endif
   
      if((issubstr(Sensor,"PM"))&((Probe == "1H-S")|(Probe == "1H-L")|(Probe == "19F-S")|(Probe == "19F-L")|(Probe == "31P-S")|(Probe == "31P-L")))

         probeDir = sensorDir + "\\$Sensor$"
         spacerDir = probeDir + "\\$Probe$"


         cd(spacerDir)
         parList = getfilelist(".")

   
      else
         message("Error","Select Probe and Sensor first!","error")
         return(null)
      endif
   
   endif


endproc(parList)



###############################################################
# Check whether selectedProbeHead file exist
# and return list of parameters nand error status
# Provide the option to navigate to the ProbeHeads folder
###############################################################

procedure(checkSelectedProbeHeadFile,queries="yes")

   error = 1
   selectedProbeHead = null
   cd(getmacropath())

   if (isdir(".ProbeHeads"))
      cd(".ProbeHeads")

      if(:checkFolderValidity(queries="yes"))
         return(selectedProbeHead,error)
      endif

      if(isfile("selectedProbeHead.par"))   # if file already exist set up selected config
         error = 0
         selectedProbeHeadPars = load("selectedProbeHead.par")
      
      else # 
         error = 0

         if(queries="yes")
            message("Error","File with selected probe head parameters is not found!\rPlease set up correct configuration first!","error")
         endif

         return(selectedProbeHead,error)
      endif
  else

      message("Error","Folder .ProbeHeads with parameter files is not found!\r You need to copy the .ProbeHeads folder to NMR-Mouse folder.","error")

      if(query("Warning","Do you want to navigate to the .ProbeHeads folder?","no") == "yes")
         path = "$appdir$\\Macros"
         probeHeadPath = getfolder(path,"Select .ProbeHeads folder")
         copydir(probeHeadPath,".ProbeHeads")
         cd(".ProbeHeads")

         errorFolder = :checkFolderValidity()

    #     pr errorFolder

         result = rmfile("selectedProbeHead.par")

        (selectedProbeHead,error) = :checkSelectedProbeHeadFile(queries="no")    
     #    pr "error after seconf CHECK is $error$\n"

      endif   
         return(selectedProbeHead, error)
  endif
  # print error
endproc(selectedProbeHeadPars, error)



##############################################################
# Check whether the copied folder is valid
##############################################################

procedure(checkFolderValidity, queries="yes")
   error = 1
   if ((isdir("PM2"))|(isdir("PM5"))|(isdir("PM10"))|(isdir("PM25")))
      error = 0
   else
         if(queries="yes")
            message("Error",".ProbeHeads folder is corrupted!\rCannot find the folders corresponding to\rSensor, Probe or Spacer!\rCheck and remove .ProbeHeads folder if necessary.","error")
            if(query("Warning","Do you want to navigate to the .ProbeHeads parent folder?","no") == "yes")
               exec("explorer",getmacropath())
            endif
         endif
   endif

endproc(error)