#####################################################################
# Runs SSE experiment for set up in the list depths
#
# Copyright (c) Magritek GmbH 2013
# 
#
# Release version for FX3 PM systems
#
# Based on the macros from Prospa version for DSP
#
# Last update: Bulat Gizatullin 24.08.2026
####################################################################

procedure(SSEAuto, parameters=null) 
 
   if(EditIfShiftPressed(getmacropath(),getmacroname()))
      return
   else # Add the experiment with interface


   cd(getmacropath())
   cd(".ProbeHeads")

    if(isfile("selectedProbeHead.par"))   
      selectedProbeHead = load("selectedProbeHead.par")
    else
      message("Error!","File with selected probe head parameters is not found!\rPlease run SelectProbeHead first!","info")
      return()
    endif

      if(parameters == null)
         parameters = ["Sensor      =\"PM25\"",
                       "Probe       =\"1H-L\"",
                       "Spacer   =\"PM25-20mm\"",
                       "nrScans     =4",
                       "nrEchoes    =16", 
                       "repTime     =500", 
                       "resolution  =90", 
                       "refSignal   =5",
                       "depths      =4500",
                       "maxDepth    =5500",
               #        "position = """,
                       "DEst = 2",
                       "tauMin = 0.02",
                       "tauMax = 0.2", 
                       "DELTA = 10",
                       "nrPntsTau = 8", 
                       "index       = \"exp\"",

# parametesr for processing tab of CPMGFast
                      "alpha          = 1",
                      "autoPhase      = \"no\"",
                      "fitMode        = \"manual\"",
                      "fitType        = \"exp\"",
                      "ignoreFirstPnt = \"yes\"",
                      "enableLift = \"yes\"",
                      "normalize      = \"yes\"",
                      "phaseMethod    = \"maxreal\"",
                      "x_maximum      = 100",
                      "x_minimum      = 1"
                     ] 

      loadedPars = :loadLastPar()
#      pr loadedPars
#
#      loadedPars = rmfromlist(loadedPars,"expName")
#      loadedPars = rmfromlist(loadedPars,"softwareVersion")
#      pr loadedPars

#pr "1\n"
      parameters = sortlist(mergelists(loadedPars,parameters))
#
#pr "2\n"

      parameters = sortlist(mergelists(selectedProbeHead,parameters))

#pr "3\n"
#pr parameters
      endif
      
      gExpt->addExperiment(getmacropath(),rmext(getmacroname()),parameters)
   endif


   #:updateDepths()

endproc()

###########################################################
# The interface control(s) required by Expert when loading
# data from a experimental result
###########################################################

procedure(interface)

  
#   bak = getcwd()
#   cd(getmacropath())
#   depthList = load("depthListCPMGFastAuto.lst","list")
#   pr depthList

   ctrlLayout = ["",             "Main",                    "dv",       "",          "",
                 "Sensor",       "Sensor",                  "tb",     "readonly_string",    "", 
                 "Probe",        "Probe",                   "tb",     "readonly_string",    "", 
                 "Spacer",       "Spacer",                  "tb",     "readonly_string",    "", 
                 "resolution",   "Resolution (um)",         "tb",       "float",     "", 
                 "repTime",      "Repetition time (ms)",    "tb",       "float",     "",
                 "nrScans",      "Number of scans",         "tb",       "integer",   "",
                 "nrEchoes",     "Number of echoes",        "tb",       "integer",   "[1,8192]",
                 "normalize",    "Normalize?",              "cb",       "string",    "no,yes",
                 "refSignal",    "Normalization",           "tb",       "float",     "",
                  "",            "SSE",                   "dv",       "",          "",
                 "DEst",         "D estimation (10-9m^2/s)","tb",       "float",     "", 
                 "tauMin",       "Min. tau (ms)",           "tb",       "float",     "",
                 "tauMax",       "Max. tau (ms)",           "tb",       "float",     "",
                 "DELTA",        "DELTA (ms)",              "tb",       "float",     "",
                 "nrPntsTau",    "Number of tau. steps",    "tb",       "integer",   "",
                 "index",        "Time increment",          "tm",       "readonly_string",    "[\"lin\",\"exp\"]",

                  "",            "Depths",                  "dv",       "",          "",
                 "enableLift",    "Enable lift",              "cb",       "string",    "no,yes",
#                 "depths",       "Depth list (um)",         "tm",       "integer",   "$depthList$",
                 "depths",       "Depth list (um)",         "tm",       "integer",   "",
                 "maxDepth",     "Maximum depth (um)",      "tb",       "float",     "",
                 "",             "Edit depth list",         "bt",       "string",    "editDepths()",

                 "",             "Update depth list",      "bt",       "string",    "updateDepths()"]
          #       "position",     "Current position (um)",   "tb",       "readonly_string",  ""]

#   processingInterface = [
#                 "",             "Processing",              "dv",       "",          "",
#         #        "fitMode",      "Fit mode?",               "tm",       "readonly_string",    "[\"realTime\"]",
#           #      "autoPhase",    "Auto phase?",             "cb",       "string",    "no,yes",
#        #         "phaseMethod",  "Phase method?",           "tm",       "readonly_string",    "[\"minsd\",\"maxreal\",\"minimag\"]",
#                 "normalize",    "Normalize?",              "cb",       "string",    "no,yes",
#          #       "ignoreFirstPnt","Ignore first point?",    "cb",       "string",    "no,yes",
#           #      "fitType",      "Type of fit",             "tm",       "readonly_string",    "[\"exp\",\"biexp\",\"nnls\",\"none\"]",
##                 "fit",          "Manual Fit",              "bt",       "string",    "ManualFit()",
#          #       "x_minimum",    "Min. relax. time (ms)",   "tb",       "float",     "[0.001,100]",
#         #        "x_maximum",    "Max. relax. time (ms)",   "tb",       "float",     "[0.001,10000]",
#          #       "alpha",        "Alpha",                   "tb",       "float",     "[0.0001,1000]"
#                        ]
   
   
#   ctrlLayout = ctrlLayout + processingInterface
   

   procLayout =   struct(
                         
                         buttonLabel = "Row",   plotName = "im1", macroToRun = "func2d(\"select row\")";
                         buttonLabel = "Phase",   plotName = "pt1", macroToRun = "manualPhase1D()"
                        )

 #  "Select row data\tCtrl+Shift+H", "select_row", func2d("select row"),

   plotLayout = ["pt1","pt2","pt3";"im1"]
#   plotLayout = ["im1"]

#   :updateDepths()

endproc(ctrlLayout, plotLayout,procLayout)


########################################################
# Get the name of a plot file given the region name
# or return the whole list. 
########################################################

procedure(getPlotInfo, plotRegion)

   info = ["pt1","echo.pt1",
           "pt2","sseLin.pt1",
           "pt3","sseLog.pt1",
           "im1","sse2d.pt2"          
            ]

   if(plotRegion == "all")
      return(info)
   endif

   idx = getlistindex(info,plotRegion)
   if(idx != -1)
      return(info[idx+1])
   endif

endproc(null)



################################################################
# Come here when the run button is pressed
################################################################

procedure(backdoor, parameters)

   assignstruct(parameters)
#pr parameters
#   pr "in BD\n"
#
   (pt1,pt2,pt3,im1) = InitPlot(["pt1","pt2","pt3";"im1"])

   cd(getmacropath())
   cd(".ProbeHeads")
   selectedProbeHead = load("selectedProbeHead.par")
#pr "selProbe loaded...........................\n"
#pr selectedProbeHead
   assignlist(selectedProbeHead)


   loadedPars = :loadLastPar()
#pr vartype(loadedPars)

#pr vartype(parameters)
 #  pr loadedPars

   
   cd(gData->curExpt->dataPath)  
   acquAuto = load("acqu.par")
   save("acquAUTO.par",acquAuto) # backup of acqu.par for AUTO parameters


   if(:checkInterfaceHardwareConfig(parameters) == 1)
      return()
   endif

   depthList = getobj(0,findobj(0,"name","depths"))->menu
   
   if(:checkDepthList(depthList) == 1)
      return()
   endif

   :saveDepthList(depthList)#############
   :saveLastPar(acquAuto)###################



   dwell = 0.5
   nrPnts   = round(1e6/(gradient*dwell*resolution))
   echoTime = echoTime0 + round(dwell*nrPnts)-pulseLength

############ Check for total RF duty cycle################################################################################################
   TDC=pulseLength*nrEchoes/repTime

# for PM25----------------------------------------------
    if ((TDC>1.6)&(Sensor == "PM25")) 
    message("Error","RF duty cycle is too high, reduce nrEchoes or increase repTime. Total duty cycle is currently $TDC$. Maximum allowed is 1.6","error") 
    return(0)
# for PM5----------------------------------------------
    elseif ((TDC>3) & ((Sensor == "PM5")|(Sensor == "PM10"))) 
    message("Error","RF duty cycle is too high, reduce nrEchoes or increase repTime. Total duty cycle is currently $TDC$. Maximum allowed is 3","error") 
    return(0)
    endif

###############################################################################################################################################



   if(resolution < bestResol)
     message("ERROR","resolution < bestResol\n increase resolution","error")
     return
   endif

   if(nrPnts/2 < pulseLength)
     message("ERROR","resolution > excited slice\n decrease resolution","error")
     return
   endif


   result = struct()
   result->tauArray = matrix(nrPntsTau)
   result->qAxis = matrix(nrPntsTau)
   result->ampAxis = matrix(nrPntsTau)
   result->E0 = 0
   result->T1 = 0



   parameters = list(parameters)
   newPar = mergelists(parameters,selectedProbeHead)
   newPar = mergelists(newPar,loadedPars)



#   newPar = setlistvalue(newPar,"bandwidth","2000")
#   newPar = setlistvalue(newPar,"bandwidthFile","0.5")
   newPar = setlistvalue(newPar,"dwellTime","0.5")
   newPar = setlistvalue(newPar,"nrPnts","$nrPnts$")
   newPar = setlistvalue(newPar,"echoTime","$echoTime$")

   newPar = setlistvalue(newPar,"b1FreqCh1","$b1Freq$")
   newPar = setlistvalue(newPar,"pulseLengthCh1","$pulseLength$")
   newPar = setlistvalue(newPar,"90AmplitudeCh1","$90Amplitude$")
   newPar = setlistvalue(newPar,"180AmplitudeCh1","$180Amplitude$")

#   newPar = setlistvalue(newPar,"acqTime","$dw*nrPnts/1000$")



   newPar = setlistvalue(newPar,"showFreqDomain","\"no\"")
   newPar = setlistvalue(newPar,"autoPhase","\"no\"")
#   newPar = setlistvalue(newPar,"fitMode","\"manual\"") # to make all fits here in macro
 #  newPar = setlistvalue(newPar,"saveData","\"false\"")
#   newPar = setlistvalue(newPar,"excecutedBackdoor","\"yes\"")

pr "newPar before load \n"
pr newPar
   assignlist(newPar)
#   if(refSignalCheck == "no")
#      newPar = setlistvalue(newPar,"refSignal","1")
#   endif

##   cd(getmacropath())
##   cd(".ProbeHeads")
##   cd(sensor)
##   cd(probe)
##   exptPar = load(probeHead+".par")
##   exptPar = sortlist(mergelists(list(parameters),exptPar))
#
## Get the plot layout
#   plotProc = "CPMGInt_Interface:plot_run_layout"
#   plotLayout = plotProc()
#   InitPlot(plotLayout)
#
## Move to home
#   MouseMove:homeBD()
#   pr "\n   Mouse going home ...\n"
#   pause(0.0035*(maxDepth)+ 0.5)  # Wait for home completion
#
#   oldDepth = 0
#
############################################# from PM5 ####################################

#   oldDepth = 0
   depth = 0
   if(enableLift == "yes")

      MouseMoveKea:MoveBD(-100,depth)
pr "moved -100\n"
  #    :Move(-100)   # Move down 100 us to unblock the sensor

  #    MoveHome(-1) # Go home
      MouseMoveKea:homeBD()   # Go home
pr "moved to home\n"
pr maxDepth
      pr "\nMouse going home...\n"
      pause(0.0035*(maxDepth)+ 12)  # Wait for home completion
    # :Move(-70)   # Move down 70 um
      MouseMoveKea:MoveBD(-70,depth)
pr "moved -70\n"
#   
#      oldDepth = maxDepth
      depth = maxDepth
   endif
#################################################################################

   nrSteps = size(depthList)
   data2D   = matrix(nrPntsTau,nrSteps)
   resultsFit = list(nrSteps)
   stats = list(nrSteps)


#################### Start depth changes and data acq.###########################
   for(k = 0 to nrSteps-1)

pr depth

      newDepth = eval(depthList[k])
#      offset = oldDepth-newDepth
      moveOffset = - (depth - newDepth)

   if(enableLift == "yes")   
      MouseMoveKea:MoveBD(moveOffset,depth)
   else
        if(query("Positioning","Set initial position to: $depthList[k]$ um") == "no")
        return
        endif
   endif 
pr "====Moved $moveOffset$\n"

#      oldDepth = newDepth
     depth = newDepth

     result =  RunExpt("SSEpm", newPar)

   qAxis = result->qAxis
   tauArray = result->tauArray
   ampArray = result->ampAxis

   depthStr = depthList[k]

   if(result->stats != null)
      stats[k] = "Depth = $depthStr$ um:\n" + result->stats
   else
      stats[k] = ""
   endif

   if(result->results != null)
      resultsFit[k] = "Depth = $depthStr$ um:\n" + result->results
   else
      resultsFit[k] = ""
   endif

   #   resultsFit[k] = "Depth = $depthStr$ um:\n" + result->results



   data2D[~,k] = real(ampArray)
   
   im1->image(data2D)


#   :saveData(newPar,tauArray,ampArray,depthStr,data2D,resultsFit)


#
    ucsFiles:savePlot(pt1,:getPlotInfo("pt1"),newPar,"simpleReport")
    ucsFiles:savePlot(pt2,:getPlotInfo("pt2"),newPar,"simpleReport")
    ucsFiles:savePlot(pt3,:getPlotInfo("pt3"),newPar,"simpleReport")
    ucsFiles:saveImage(im1,:getPlotInfo("im1"),newPar,"simpleReport")

   :saveData(newPar,tauArray,qAxis,ampArray,depthStr,data2D,resultsFit,stats)



   next(k)

   cd(gData->curExpt->dataPath)
   acquCPMG = load("acqu.par")
   acquCombined = acquAuto + acquCPMG
   save("acquCombined.par",acquCombined)
   save("acqu.par",acquAuto)
   save("acquCPMG.par",acquCPMG)


endproc()


########
# Save Last parameters to the file
#######
procedure(saveLastPar, parameters)

    assignlist(parameters)
#pr "saving...\n"
#pr parameters
    bak =  getcwd()
    name = getmacroname()
    name = rmext(name)
    cd(getmacropath())
#pr parameters
    save("$name$LastExp.par",parameters)
    cd(bak)

endproc()

########
# Save depths List to the file
#######
procedure(saveDepthList, depthList)

   bak =  getcwd()
   
   cd(gData->curExpt->dataPath)
   
   save("depthList.par",depthList)

   cd(bak)

endproc()


########
# Load Last parameters from the file
#######

procedure(loadLastPar)

    back =  getcwd()
   
    name = getmacroname()
    name = rmext(name)
    cd(getmacropath())

    if(isfile("$name$LastExp.par"))
      pars = load("$name$LastExp.par")

      pars = rmfromlist(pars,"expName")
      pars = rmfromlist(pars,"softwareVersion")

    else
      message("Warning!!!","File with initital parameters not found!\rPlease set up correct parameters in the interface and run it!","info")
      pars = null
    endif
    
   setcwd(back)



endproc(pars)



##################################
# Compare hardware parameters in teh interface with selected ones
##################################

procedure(checkInterfaceHardwareConfig,parameters)

   assignlist(parameters)

   cd(getmacropath())
   cd(".ProbeHeads")
   selectedProbeHead = load("selectedProbeHead.par")

   if ((Sensor!=(getlistvalue(selectedProbeHead,"Sensor")))|(Probe!=(getlistvalue(selectedProbeHead,"Probe")))|(Spacer!=(getlistvalue(selectedProbeHead,"Spacer"))))
      message("Error","Sensor-Probe-Spacer do not match selected ones!\r Check the selectProbeHead macro! ","error")
      return(1)
   endif

endproc(0)


########################################
# Check validity of the depths list
###########################################
procedure(checkDepthList,depthListPar)

  guipar = getctrlvalues(0)
  assignlist(guipar)

#pr depthListPar

   depthList = getobj(0,findobj(0,"name","depths"))->menu
#pr depthList

   if ((depthList!=depthListPar)|(depthList == null)|(depthListPar == null))
     message("Error!!!","Depth lists are differnet or empty!\rUpdate and check the depth list first!","error")
  #   print("\n Depth lists are differnet or empty! Update and check the depth list first!\n")
     return(1)     
#     lstDepths =:updateDepths()
   endif

  nrDepths = size(depthList)
  depthArray = matrix(nrDepths)

   

  for (m=0 to nrDepths-1)
    depthArray[m]=eval(depthList[m])
  next(m)
  
  for (m=0 to nrDepths-1)
   
    if(depthArray[m] < -500)
       message("Error!!!","List of depths contains a value < 0","error")
       return(1) 
    endif()

    if(depthArray[m] > maxDepth)
       message("Error!!!","List of depths contains a value > $maxDepth$ um.","error")
       return(1) 
    endif()

    if(depthArray[m]%10 != 0)
       message("Error!!!","List of depths contains a value not multiple of 10 um","error")
       return(1)
    endif()
 
    if(m < nrDepths-1)
       if(depthArray[m]<depthArray[m+1])
          message("Error!!!","List of depths must sorted in desending order","error")
          return(1)
       endif
    endif

   
  next(m)

endproc(0)

###########################################################
# Edit deprths
###########################################################

procedure(editDepths)

#   editorWin()
   bak = getcwd() 
   cd(getmacropath())
   EditorWin()
   edit("depthListSSEAuto.lst")
   cd(bak)

endproc()


###########################################################
# Upgrade depths value in the interface
###########################################################

procedure(updateDepths)

   bak = getcwd()
   cd(getmacropath())
   depthListPar = load("depthListSSEAuto.lst","list")
   obj = findobj(0,"name","depths")
   setpar(0,obj,"menu",depthListPar)
   setpar(0,obj,"text",depthListPar[0])
   cd(bak)

endproc(depthListPar)


###########################################################
# Save data and parameters rleated to CPMGFast, fitting and depth
###########################################################

procedure(saveData,newPar,totalTime,qAxis,data1D,depthStr,data2D,resultsFit,stats)

   guipar = getctrlvalues(0)
   assignlist(guipar)

#   obj = findobj(0,"name","depths")
#pr obj
#   depthListValues = getpar(0,obj,"list")
   depthListValues = getobj(0,findobj(0,"name","depths"))->menu
   guipar = setlistvalue(guipar,"depthListValues","$depthListValues$")



   bak =  getcwd()
   
   cd(gData->curExpt->dataPath)
   




## Save data and plot in chosen folder
#   bak = getcwd()

#   cd(dataDirectory)
#   mkdir(expName)
#   cd(expName)
#   mkdir("$expNr$")
#   cd("$expNr$")

   save("GUI.par",guipar)              # Save acq. parameters
   save("acq.par",newPar)              # Save acq. parameters
   
  # if(fitType=="biexp" | fitType =="exp")
      save("resultsFit.par",resultsFit)  # Save results of the fit
 #  endif


  # if(fitType != "none")
      save("stats.par",stats)  # Save results of the fit
 #  endif
#
   n = size(data1D)
   m = matrix(3,n)
   m[0,~] = (totalTime/1000)'
   m[1,~] = real(data1D)'
   m[2,~] = imag(data1D)'

  
      save("data-$depthStr$um.1d",data1D)     # Save data in Prospa format
      save("data-$depthStr$um.pt1")           # Save plot
      save("data-$depthStr$um.emf","emf1d")   # Save plot as picture

      export2dpar("ab","ascii","xyrc","real","delimiter","tab")
      export2d(m,"data-$depthStr$um.dat")  # Save data for origin
     
      export1dpar("ab", "ascii",  "xyrc", "real")
      export1d(totalTime, "TauAxis.dat")
      export1d(qAxis, "QAxis.dat")

      export2dpar("ab","ascii","xyrc","real","delimiter","tab")
      export2d(data2D,"data2D.dat")  # Save data for origin

      save("2Ddata.2d",data2D)     # Save 2d data in Prospa format
      save("2Ddata.pt2")           # Save 2d plot
      save("2Ddata.emf","emf2d")   # Save 2d plot as picture
   

# Restore cwd
   cd(bak)

endproc("saveData")
