####################################################
# Returns 1 if number is a power of 2, 0 otherwise
####################################################

procedure(ispower2,number)

 l2 = log2(number)

endproc(abs(l2 - round(l2)) < 0.00001)

####################################################
# Returns 0 if number is a power of 2, 1 otherwise
####################################################

procedure(is_not_power2,number)

 l2 = log2(number)

endproc(abs(l2 - round(l2)) > 0.00001)