procedure(importpar,type, xyrc)


   if(nrArgs == 1)
      xyrc = "complex"
   endif

   if(type == "Avance")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)


      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

   elseif(type == "AMX" | type == "Paravision" | type == "Paravision-LittleEndian")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

  elseif(type == "Paravision-BigEndian")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)


   elseif(type == "Prospa")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",28)

     elseif(type == "Float-BigEndian")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

     elseif(type == "Float-LittleEndian")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","littleend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",0)

  
    elseif(type == "Varian")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",60)

      import2dpar("ab","binary",
                 "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "fileheader",32,
                  "rowheader",28)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "fileheader",32,
                  "rowheader",28)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","long",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

    elseif(type == "VarianFloat")

      import1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "rowheader",0,
                  "fileheader",60)

      import2dpar("ab","binary",
                 "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "fileheader",32,
                  "rowheader",28)

      import3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "fileheader",32,
                  "rowheader",28)

      export1dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

      export2dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

      export3dpar("ab","binary",
                  "xyrc",xyrc,
                  "fls","float",
                  "machine","bigend",
                  "delimiter","space",
                  "fileheader",60)

   endif




endproc()


