procedure(loopTest3)
cnt = 0
   time(0)
   for(jj = 0 to 9999)
      for(ii = 0 to 999) 
         cnt = cnt + ii
      next()
   next()
   print(time())
   print(cnt)

endproc(cnt)


procedure(loopTest2)

   cd(getmacropath())
   cachemacro(getmacroname())
   cacheproc("true")
   cnt = 0
   time(0)
   for(ii = 0 to 99999) 
     cnt = :loopTest1(cnt)
   next()
   print(time())
   print(cnt)

endproc() 

procedure(loopTest1,cnt)

  for(jj = 0 to 999) 
     cnt = cnt + jj
   next()

endproc(cnt)

procedure(loopTestA)



endproc()


