#pl = [1,-3;
#     2,-2;
#     1,0;
#     2,2]
#time(0)
#(w,h) = size(pl)
#pr w,h
#N = 1024
#x = linspace(-5,15,N)
#y = matrix(N)
#for(k = 0 to h-1) # Loop over peaks
#  a0 = pl[0,k]
#  a1 = pl[1,k] 
# # a2 = pl[2,k]
#  for(q = 0 to N-1) # Loop over x axis
#     fac = (x[q]-a1)
#     y[q] = y[q] + a0/(1+1000*fac^2)
#  next(q)
#next(k)
plot(x,y)
f = peakfit(x,real(y),pl)
hold("on")
plot(x,f,"color",red)
hold("off")

