procedure(lines3d_test1,verbose,delay)

   clear3d
   N = 4000
   k = [0:1:N]
   x = sin(k/10).*sin(-2*pi*k/N)
   y = cos(k/10).*sin(-2*pi*k/N)
   z = 4*(k-N/2)/N
   
   draw3d("false")
   color3d([1,1,0])
   lines3d(x,y,z)
   viewdistance(10)
   
   color3d([1,0,0])
   lines3d(z,y,x)
   color3d([0,0,1])
   lines3d(x,z,y)
   draw3d("true")
   
   for(k = 0 to 360*4)
      rotate3d(50,330,k)
   next(k)

endproc(1,"")



