

procedure(rmext_test1,verbose,delay)

   file = "text.txt"
   if(rmext(file) != "text")
     return(0, "Invalid result for: rmext_test1 #1")
   endif 

   file = "text"
   if(rmext(file) != "text")
     return(0, "Invalid result for: rmext_test1 #2")
   endif 

   file = "text.fdshfiwehfui"
   if(rmext(file) != "text")
     return(0, "Invalid result for: rmext_test1 #3")
   endif 

   file = "text.txt.another"
   if(rmext(file) != "text.txt")
     return(0, "Invalid result for: rmext_test1 #4")
   endif 

endproc(1,"")

