procedure(dspread,memBank,address,dataSize,port)

# x memory
   if(memBank == "x")
     if(address == 0x22085)
        return(matrix(1,1))
     else
	  throw("Simulated read from 'x:$address$' not supported")
     endif

# p memory
   elseif(memBank == "p")
      if(address == 0xD3FF00) # Check for DSP info
         v = matrix(138)
         v[0:11] = [1,2,6,3,13,43,0,0,2,1,0,0]
         v[12:20] = strtoascii("Simulator")
         return(v)
       else
	   throw("Simumated read from 'p:$address$' not supported")
       endif

# y memory
   elseif(memBank == "y")
      if(address == 0x10000) # read NMR data

         name = gData->curExpt->protocol  
         if(isproc(gData->curExpt->ppPath,"$name$_pp","simulateNMR"))
            bak = getcwd()
            cd(gData->curExpt->ppPath)
            proc = "$name$_pp:simulateNMR"
            data = proc(dataSize)
            cd(bak)
         endif

      endif
   endif


endproc(data)



	