procedure(dspwrite,memBank,address,vec,port)

   if(memBank == "x")
      if(address == 0) # Write NMR parameters - in this case to the SimulationInfo window variable

         sz = size(vec);

         tx = vec[13]*65536.0d + vec[14]
         freq = tx/42949672.96d
         SimulationInfo->b1Freq = freq

         if(SimulationInfo->flatFilter)
            SimulationInfo->dwellTime = vec[2]/50.0
         else
            SimulationInfo->dwellTime = vec[2]/100.0
         endif

         SimulationInfo->receiverPhase = 360-vec[17]/65535.0*360
         idx = round(vec[0]/256)*16+round(vec[1]/256)
         rxAmpGain = 10.0^(ucsSim:getRxGain(idx)/20.0)

         filterGain = gData->digFilterCor
         rxDigCal = gData->specParameters->receiverCal
         preampGain = gData->specParameters->preampGain
         rxAmpCorr = gData->specParameters->rxAmpCor
         SimulationInfo->receiverGain = rxDigCal/filterGain*rxAmpGain*preampGain/rxAmpCorr/1000.0

         SimulationInfo->ppList = vec
         SimulationInfo->name = gData->curExpt->protocol

      endif
   endif

   if(memBank == "y" & address == 0x10) # Write filter info
      sz = size(vec)
      SimulationInfo->flatFilter = (sz != 1)
   endif

endproc()
