procedure(setupsim, sample, b0Freq, T2Star, rxNoise, pulseAmp, pulseLength, sigAmp)

   info = struct()
   info->b0Freq = b0Freq
   info->T2Star = T2Star
   info->sample = sample
   info->noiseAmplitude = rxNoise
   info->pulse90Integral = :convertTxFromDb(pulseAmp)*pulseLength
   info->signalAmplitude = sigAmp

   assign("SimulationInfo",info,"window")

endproc()

procedure(convertTxFromDb,tx)

   dig = 16384*10.0^(tx/20.0)-1.0

endproc(dig)

