procedure(MoveHome,n)

   bak = getcwd()
   cd(getmacropath())
   cd("LiftControl")

   guipar = ["b1Freq = 1",
             "bandwidthFile = 1.0",
             "flatFilter = \"yes\"",
             "rxPhase = 0",
             "rxGain = 40",
             "nrScans =1",
             "repTime = 10",
             "noHPA = \"true\"",
             "usePhaseCycle = \"no\"",
             "TTL1 = 3",
             "TTL2 = 3",
             "d1 = 20000",
             "d2 =  1000"]

   guipar=setlistvalue(guipar,"steps","$1$")
   guipar=setlistvalue(guipar,"n","$-1$")
   guipar=setlistvalue(guipar,"p","$0$")
   guipar=setlistvalue(guipar,"modir","100")
   guipar=setlistvalue(guipar,"dataDirectory","\"move\"")
   guipar=setlistvalue(guipar,"expName","\"move\"")
   guipar=setlistvalue(guipar,"expNr","1")
   guipar=setlistvalue(guipar,"dwellTime","0.5")
   rel = ["b1 = ttltranslate(TTL1)",
          "b2 = ttltranslate(TTL1)+ttltranslate(TTL2)"]
       
   var = [""]
   pp_list = ["b1","d1","b2","d2"]
   pp_name = "twoTTLpulses.p"
   phase_list = [0]


   twoTTLpulses:backdoor(guipar)

   cd(bak)





#   (guipar,ppList,pcList,pcIndex,varList) = keaNMR:initialisePPNoGUI(dir,guipar,rel,var,pp_list,pp_name,phase_list)
#   
#
#   (ppList,pAcq) = keaNMR:setPPPhase(ppList,0,pcList,pcIndex)
#
#    # Send phase parameters to DSP
#      dspwritepar("x",0x00,ppList)
#
#   # Run pulse program return "ok" or "abort"
#      status = dsprunpp(0x2000,1)
#
##   if(n > 0)
##      setpar(0,n,"text","position = $0$ um")
##   endif

endproc()
