procedure(MoveDown,steps,n,p)

   dir = getmacropath()

   guipar = ["b1Freq = 1",
             "bandwidthFile = 1.0",
             "flatFilter = \"yes\"",
             "rxPhase = 0",
             "rxGain = 40",
             "nrScans =1",
             "repTime = 10",
             "noHPA = \"true\"",
             "usePhaseCycle = \"no\"",
             "TTL1 = 4",
             "TTL2 = 4",
             "d1 =  1000",
             "d2 =  1000"
                  ]


guipar=setlistvalue(guipar,"steps","$steps$")
guipar=setlistvalue(guipar,"n","$n$")
guipar=setlistvalue(guipar,"p","$p$")
guipar=setlistvalue(guipar,"modir","4")
guipar=setlistvalue(guipar,"dataDirectory","\"move\"")
guipar=setlistvalue(guipar,"expName","\"move\"")
guipar=setlistvalue(guipar,"expNr","1")
guipar=setlistvalue(guipar,"dwellTime","0.5")


   rel = ["b1 = ttltranslate(TTL1)",
          "b2 = ttltranslate(TTL1)+ttltranslate(TTL2)"]
       
   var = [""]
   pp_list = ["b1","d1","b2","d2"]
   pp_name = "twoTTLpulses.p"
   phase_list = [0]



twoTTLpulses:backdoor(guipar)


   
endproc()
