########################################################
#
# Stimulated spin echo + CPMG detection.
#
########################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, x, y, ctrlType, varType)
   interface = ["b1FreqCh1",      "B1 Frequency (MHz)",   "tb",     "freq";

               "90AmplitudeCh1",  "90 amplitude (dB)",    "tb",     "float,[-85,-6]";
               "180AmplitudeCh1", "180 amplitude (dB)",   "tb",     "pulseamp";
               "pulseLengthCh1",  "Pulse length (us)",    "tb",     "pulselength";

               "echoTime",        "Echotime (us)",        "tb",     "sdelay";
               "nrEchoes",        "Number of echoes",     "tb",     "integer,[1,16000]";
               "echoShift",       "Echo shift (us)",      "tb",     "float,[-20,20]";
               "gradient",        "Gradient (kHz/mm)",    "tb",     "float";

               "DEst",            "D (10-9 m^2/s)",       "tb",     "float";
               "tauMin",          "tau min (ms)",         "tb",     "float,[0.001,100]";
               "tauMax",          "tau max (ms)",         "tb",     "float,[0.001,100]";
               "DELTA",           "DELTA (ms)",           "tb",     "float,[0.001,10000]";
               "nrPntsTau",       "Number of tau incr.",  "tb",     "integer,[1,1000]";
               "index",           "Time increment",       "tm",     "string,[\"lin\",\"exp\"]";
               "repTime",         "Repetition time (ms)", "tb",     "reptime"]


  tabs = ["Pulse sequence","Acquisition","File Settings"]

# Relationships between pulse-sequence and GUI parameters
   relationships = ["a1 = 90AmplitudeCh1",
                    "a2 = 180AmplitudeCh1",
                    "d1 = pulseLengthCh1",
                    "d2 = 1000*tauMin+echoTime/2-d1-pgo",
                    "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
                    "d4 = echoTime-d1-pgo-d3",
                    "d5 = 1000*tauMin-d1-pgo",
                    "w1 = 1000*DELTA",
                    "n1 = nrEchoes",
                    "n2 = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# These parameters will be changed between experiments
   variables = ["d5","d2"]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   cleardata(n2)

   pulse(mode,a1,p1,d1)        # 90 pulse
   delay(d5)                   # small delta
   pulse(mode,a1,p2,d1)        # 90 pulse
     
   wait(w1)                    # DELTA - Diffusion time

   pulse(mode,a1,p3,d1)        # 90 pulse
   delay(d2)                   # small delta + TE/2

   loop(l1,n1)
      pulse(mode,a2,p4,d1)     # 180 internal pulse
      delay(d3)                # 180 - acq delay
      acquire("sum",n2,d4)     # Acquire echo and wait
   endloop(l1)

   lst = endpp() # Return parameter list

# Phase cycle
   phaseList = [0,2, 0,2, 0,2, 0,2, 1,3, 1,3, 1,3, 1,3; # 90 excitation
                0,0, 2,2, 0,0, 2,2, 0,0, 2,2, 0,0, 2,2; # 90 storing
                0,0, 0,0, 2,2, 2,2, 0,0, 0,0, 2,2, 2,2; # 90 reading
                1,1, 1,1, 1,1, 1,1, 0,0, 0,0, 0,0, 0,0; # 180 CPMG
                2,0, 0,2, 0,2, 2,0, 1,3, 3,1, 3,1, 1,3] # Acquire phase

endproc(lst,tabs,interface,relationships,variables,null,phaseList)


#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   specPar = gData->specParameters
   if(specPar == null)
      return(null)
   endif
   assignlist(specPar)

   par = ["rxGain           = $rxOptGaindB$",
          "pulseLengthCh1   = $pulseLengthCh1$",
          "90AmplitudeCh1   = $pulseAmplitudeCh1$",
          "180AmplitudeCh1  = $pulseAmplitudeCh1$+6",
          "b1FreqCh1        = $frequencyCh1$"]

endproc(par)
 