procedure(interp_test1,verbose,delay)

# Interpolate 1D
   clear1d()
   m = noise(10)
   for(k = 10 to 1000 step 10)
      draw1d("false")
      plot(interp(m,k))
      title("$k$ points")
      draw1d("true")
   next(k)

# Interpolate 2D
   clear2d()
   m = noise(10,10)
   for(k = 10 to 100)
      draw2d("false")
      image(interp(m,k,k))
      title("$k$ by $k$")
      draw2d("true")
   next(k)
 
endproc(1,"")



