procedure(grid_test1,verbose,delay)
  
 clear1d()
 f = [1:100:50000]
 R = 10000
 C = 10e-9
 w = 2*pi*f
 m = 1/sqrt(1+(w*R*C)^2)
 plot(f,m)
 grid("xgridstatus","on",
      "ygridstatus","on",
      "finexgridstatus","on",
      "fineygridstatus","on",
      "gridcolor",[255,0,0],
      "finegridcolor",[128,0,0])
 axes("xmapping","log")
 axes("ymapping","log")
 autorange("off")
 zoom1d(1,20e3,0.05,1.1)
 xlabel("Frequency (Hz)")
 ylabel("Attenuation")
 title("Low pass filter")
  

endproc(1,"")
