procedure(trace_test1,verbose,delay)

   x = [0:1:99]
   y = 10*noise(100) + x 
   plot(x,y)  # Plot a noisy data set
   trace("tracetype", "none", "symbolshape", "opensquare",
          "symbolcolor", [255,0,0]) 
   
   hold("on")
   plot(x,x) # Plot ideal data set
   trace("tracetype", "lines", "symbolshape", "none",
         "tracecolor", [255,255,0],"tracewidth",2) 
   
   title("trace command test")
   ylabel("y")
   hold("off")


endproc(1,"")
