procedure(evalsubexp_test1,verbose,delay)

b = 10
a = "2+$3*b$"
if(evalsubexp(a) != "2+30")
    return(0, "Invalid result for: evalsubexp_test1 #1")
endif

b = 10+i
a = "2+$3*b$"
if(evalsubexp(a) != "2+30+3i")
    return(0, "Invalid result for: evalsubexp_test1 #1")
endif

b = [1,2,3,4]
a = "2+$3*b$"
if(evalsubexp(a) != "2+[3,6,9,12]")
    return(0, "Invalid result for: evalsubexp_test1 #2")
endif

b = {1+i,2+2i,3+3i,4+4i}
a = "2+$3*b$"
if(evalsubexp(a) != "2+{3+3i,6+6i,9+9i,12+12i}")
    return(0, "Invalid result for: evalsubexp_test1 #2")
endif

b = [1,2;3,4]
a = "2+$3*b$"
if(evalsubexp(a) != "2+[3,6;9,12]")
    return(0, "Invalid result for: evalsubexp_test1 #3")
endif

b = {1+i,2+2i;3+3i,4+4i}
a = "2+$3*b$"
if(evalsubexp(a) != "2+{3+3i,6+6i;9+9i,12+12i}")
    return(0, "Invalid result for: evalsubexp_test1 #2")
endif

endproc(1,"")
