# Make a desktop icon for Kea Expert - note that the icon may need to be updated
procedure(makeDesktopLink)

   linkPath = "$desktop$\\KeaExpert.lnk";
   execPath = "$appdir$\\Prospa.exe";
   arguments = "\"$appdir$\\Macros\\Kea-Expert\\KeaExpertInterface.pex\"";
   
   iconSrc = "$appdir$\\Macros\\Kea-Expert\\Other Macros\\Bitmaps\\KeaExpert.ico"
   iconDst = "$prefdir$\Icons\\KeaExpert.ico"
   mkdir("$prefdir$\Icons")
   copyfile(iconSrc,iconDst)

   makelink(linkPath, execPath, arguments, iconDst)
   
endproc()