###################################################################################
# acquireoff command - dummy function not required by fx3
##################################################################################

procedure(acquireoff, arg1=0, arg2=0)

   if(wvFX3Info->mode == "run")

      wvFX3Info->currentTTL = wvFX3Info->currentTTL & inv(0x01)
       
   elseif(wvFX3Info->mode == "compile")

      addPSParameters(nrPnts)

   endif

endproc()

