###################################################################################
# FX3/TRex pulse program macros (alternative to DSP DLL keaPPRun.dll)
#
# Add a delay 'duration' in us to the sequence by shifting the next command time
# Note that the wait command is the same as delay in FX3 mode
###################################################################################

procedure(wait, duration)

   delay(duration)

endproc()

