procedure(while_test1,verbose,delay)

   m = matrix(10)
   a = 10
   c = 0
   while(a > 0)
     m[c] = a
     c = c + 1
     a = a -1
   endwhile

   if(m != [10:-1:1])
      return(0,"Invalid result for: while_test1 #1")
   endif 

   a = 10
   c = 0
   while(a > 0)
     m[c] = a
     if( a == 19)
        exitwhile
     endif
     c = c + 1
     a = a + 1
   endwhile

   if(m != [10:19])
      return (0,"Invalid result for: while_test1 #2")
   endif 
   
endproc(1,"")
