

procedure(return_test1,verbose,delay)

   (radius,theta) = :polar(1,1)
   if(radius != sqrt(2) | theta != pi/4)
      return(0, "Invalid result for: return_test1 #1")
   endif 


   (radius,theta) = :polar(0,1)
   if(radius != 1 | theta != pi/2)
      return(0, "Invalid result for: return_test1 #2")
   endif 
endproc (1,"")

 

procedure(polar,u,v)

   r = sqrt(u^2+v^2)
   if(u == 0)
      return(r,pi/2)
   endif
   t = atan(v/u)


endproc(r,t)
