########################################################
# 
# Slice selective spin-echo imaging
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1Freq",        "B1 Frequency (MHz)",        "0","0", "tbw", "freq",
               "repTime",       "Repetition time (ms)",      "0","1", "tbw", "reptime",
               "O1",            "Offset (Hz)",               "0","2", "tbw", "float",
               "a1",            "90 amplitude (dB)",         "0","3", "tb",  "pulseamp",
               "PulseLength90", "90 pulse length (us)",      "0","4", "tb",  "pulselength",
               "SPType",        "Soft pulse shape",          "0","5", "tm",  "60,[\"sinc3\",\"sinc5\",\"gauss\",\"rect\"]",
               "a2",            "180 amplitude (dB)",        "0","6", "tb",  "pulseamp",
               "PulseLength180","180 pulse length (us)",     "0","7", "tb",  "pulselength",

               "echoTime",      "Echotime (us)",             "1","0", "tb",  "sdelay",
               "acqShift",      "acquisition Shift(us)",     "1","1", "tb",  "float,[-1000,1000]",
               "sliceComp",     "sliceComp(us)",             "1","2", "tb",  "float,[-1000,1000]",
               "nrStepsP1",     "nro. pts. phase 1",         "1","3", "tb",  "integer,[1,500]",
               "nrStepsP2",     "nro. pts. phase 2",         "1","4", "tb",  "integer,[1,500]",
               "nrStepsP3",     "nro. pts. phase 3",         "1","5", "tb",  "integer,[1,500]",
               "phDur",         "phDur (us)",                "1","6", "tb",  "sdelay",

               "FoVPhase1",     "FoV Phase 1 (mm)",          "2","0", "tb",  "float,[-10000,10000]",
               "FoVPhase2",     "FoV Phase 2 (mm)",          "2","1", "tb",  "float,[-10000,10000]",
               "FoVPhase3",     "FoV Phase 3 (mm)",          "2","2", "tb",  "float,[-10000,10000]",
               "sliceTickness", "Slice thickness (mm)",      "2","3", "tb",  "float,[0,10000]",
               "sliceShift",    "Slice shift (mm)",          "2","4", "tb",  "float,[-10000,10000]",

               "dirPhase1",     "Phase Dir. 1",              "3","0", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase2",     "Phase Dir. 2",              "3","1", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase3",     "Phase Dir. 3",              "3","2", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirSlice",      "Slice Dir.",                "3","3", "tm",  "[\"x\",\"y\",\"z\"]"]      

 # Relationships to determine remaining variable values
  relationships = [ "d1 = PulseLength90",
                    "d500 = 2",     # time step soft pulse modulation
                    "n500 = round(PulseLength90/d500)",
                    "(t1,t2,gfac) = B1NutSoft:getRFPulse(SPType,a1,n500)",
                    "d2 = PulseLength180",
                    "rampDur = 100",
                    "d300 = 2.5",
                    "n300 = round(rampDur/d300)",
                    "d100 = 50",
                    "(del9,del99) = SPI_3D:getRewindSliceDelay(PulseLength90,sliceComp,rampDur)",
                    "d99=del99",
                    "d9=del9",   
                    "d3   = phDur-3*rampDur",
                    "d4   = echoTime/2-PulseLength90/2-d9-d99-PulseLength180/2-pgo-3*rampDur",
                    "d5   = echoTime/2-d3-6*rampDur+1000*acqTime/2-PulseLength180/2+rxLat+acqShift",
                    "n10  = SPI_3D:convertDirToChannel(dirPhase3)",
                    "n20  = SPI_3D:convertDirToChannel(dirPhase1)",
                    "n30  = SPI_3D:convertDirToChannel(dirSlice)",
                    "n40  = SPI_3D:convertDirToChannel(dirPhase2)",
                    "(gPhaseAmp1,gPhaseAmpShim1,gPhaseAmp2,gPhaseAmpShim2,gPhaseAmp3,gPhaseAmpShim3,gSliceAmp,gSliceAmpShim,sliceOffSet) = SPI_3D:setImageGradients(dirPhase1,dirPhase2,dirPhase3,dirSlice,FoVPhase1,FoVPhase2,FoVPhase3,phDur,sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)",
                    "n31 =  gSliceAmp+gSliceAmpShim", 
                    "n31a = gSliceAmpShim", 
                    "n32 = -gSliceAmp+gSliceAmpShim",
                    "n11  =  gPhaseAmp3+gPhaseAmpShim3",
                    "n11a =  gPhaseAmpShim3",
                    "n21  =  gPhaseAmp1+gPhaseAmpShim1",
                    "n21a =  gPhaseAmpShim1",
                    "n41  =  gPhaseAmp2+gPhaseAmpShim2",
                    "n41a =  gPhaseAmpShim2",
                    "f1  =  b1Freq+O1/1e6+sliceOffSet",
                    "f2  =  b1Freq+O1/1e6",                  
                    "n1  = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# Define the tabs and their order
   tabs = ["Pulse sequence","Acquisition","Processing+Display","File Settings"]

# These parameters will be changed between experiments
   variables = ["n21","n41","n11"]

# dx,dy
   dim = [170,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   settxfreq(f1)                         
   gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
      delay(d100)                          # stabilization time slice
      shapedrf(mode,t1,t2,p1,n500,d500)    # 90 soft pulse
      delay(d99)
   gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF
   
   settxfreq(f2)                       
   
   gradramp(n30,n31a,n32,n300,d300)  # SLICE gradient ON
      delay(d9)
   gradramp(n30,n32,n31a,n300,d300)  # SLICE gradient OFF  
          
   delay(d4) 

   pulse(mode,a2,p2,d2)        #180 pulse
   
   gradramp(n10,n11a,n11,n300,d300)   # PHASE3 gradient ON
   gradramp(n20,n21a,n21,n300,d300)   # PHASE1 gradient ON
   gradramp(n40,n41a,n41,n300,d300)   # PHASE2 gradient ON
      delay(d3)
   gradramp(n10,n11,n11a,n300,d300)   # PHASE3 gradient ON
   gradramp(n20,n21,n21a,n300,d300)   # PHASE1 gradient OFF
   gradramp(n40,n41,n41a,n300,d300)   # PHASE2 gradient OFF   
   delay(d5)

   acquire("overwrite",n1)


   lst = endpp() # Return parameter list

# Phase cycle list
   phaseList = [0,2; # +x,-x : 90 phase
                1,1; # +y,+y : 180 phase
                0,2] # +x,-x : Acquire phase


endproc(lst,tabs,interface,relationships,variables,dim,phaseList)