(x,a) = getplotdata("1d")
a = real(a)
   G        = [0.0114708,
               0.0280976,
               0.0380443,
               0.0458831,
               0.0525657,
               0.0584898,
               0.0638666,
               0.0688247,
               0.0734489,
               0.0777987,
               0.0819178,
               0.0858395,
               0.0895897,
               0.0931891,
               0.0966546,
               0.1]
   delta = 0.007
   Delta = 0.05

   diffAxis = -(gamma*G*delta)^2*(Delta-delta/3)

   a0 = a[0]
a = a/a0

pr diffAxis,a
   (D,c) = linfit:fit(diffAxis,loge(a))

pr D,c

   fit = a0*exp(diffAxis*D)

   hold("on")

   plot(x,fit)
