
procedure(drawAccelPlot)

   time(0)
   draw3d("off")
   bkcolor3d([0,0,0])
   clear3d
   aa3d("on")
   color3d([1,0,0])
   axispar3d(0.02,0.05,0.1,0.1)
   axis3d("x",[0,3],0,0,[0,1],"x")
   axis3d("y",[0,1],0,0,[0,1],"y")
   axis3d("z",[0,2],0,0,[0,1],"z")
   
   N = 8192
   x = [0:N-1]/N
   y = cos(x*2*pi*10) .* exp(-x*4)
   plot(x,y)
   z = matrix(N)
   M = 20
   linewidth3d(0.5)
   for(k = 0 to M)
   color3d([0,k/M,1-k/M])
   lines3d(x*3,(y)*(1-k/M),z+k/10)
   next(k)
   viewdistance(10)
   rotate3d(30,00,0)
   shift3d(-1.5,0,0)
   draw3d("on")
   print(time())

endproc()
