procedure(sendtoprospaTest)

# Load a help file into help viewer
   exec("$appdir$\\Prospa.exe","\"$appdir$\\Macros\\coreMacros\\ProspaHelpViewer.pex\"")
   pause(1)
   sendtoprospa("Prospa Help Viewer Application","Commands","acos.htm")

# Load a 1D plot file into plotting calculator
   exec("$appdir$\\Prospa.exe","\"$appdir$\\Macros\\PEX_macros\\PlottingCalculator.pex\"")
   pause(1)
   sendtoprospa("Plotting calculator","$appdir$\\Example Data\\Plots","fid.pt1")

endproc()
