procedure(matrixdim_test1,verbose,delay)

   a = matrix(10)
   b = matrix(10,10)
   c = matrix(10,10,10)
   
   ac = cmatrix(10)
   bc = cmatrix(10,10)
   cc = cmatrix(10,10,10)
   
   if(matrixdim(a) != 1 | matrixdim(ac) != 1)
     return(0, "Invalid result for: matrixlist_test1 #1")
   endif  
   
   if(matrixdim(b) != 2 | matrixdim(bc) != 2)
     return(0, "Invalid result for: matrixlist_test1 #2")
   endif 
   
   if(matrixdim(c) != 3 | matrixdim(cc) != 3)
     return(0, "Invalid result for: matrixlist_test1 #3")
   endif 

endproc(1,"")
