procedure(matrix_test1,verbose,delay)

# 1D matrix test
   m = matrix(100)
   w = size(m)

   if(w != 100)
      return(0, "Invalid result for: matrix_test1 #1")
   endif  

# 2D matrix test
   m = matrix(100,50)
   (w,h) = size(m)

   if(w != 100 | h != 50)
      return(0, "Invalid result for: matrix_test1 #5")
   endif  

# 3D matrix test
   m = matrix(50,20,10)
   (w,h,d) = size(m)

   if(w != 50 | h != 20 | d != 10)
      return(0, "Invalid result for: matrix_test1 #9")
   endif  

# 1D cmatrix test
   m = cmatrix(100)
   w = size(m)

   if(w != 100)
      return(0, "Invalid result for: matrix_test1 #1")
   endif  

# 2D cmatrix test
   m = matrix(100,50)
   (w,h) = size(m)

   if(w != 100 | h != 50)
      return(0, "Invalid result for: matrix_test1 #5")
   endif  

# 3D cmatrix test
   m = matrix(50,20,10)
   (w,h,d) = size(m)

   if(w != 50 | h != 20 | d != 10)
      return(0, "Invalid result for: matrix_test1 #9")
   endif  

endproc(1,"")
