############################################################
#
# Pulse program to generate ttl pulse
#
############################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, ctrltype, vartype)
   interface = ["pinNr",        "TTL pin number",         "tm",   "integer,[2,3,4,5,6,7,8,9]";
               "onTime",        "LED on time (ms)",       "tb",   "ldelayms";
               "ieTime",        "Inter-expt. time (ms)",  "tb",   "reptime"]

# Relationships to determine remaining variable values
   relationships = [ "freqCh1 = b1FreqCh1",
                     "w1      = onTime*1000",
                     "b1      = ttltranslate(pinNr)"]

# Define the parameter groups and their order
   groups = ["Pulse_sequence","Acquisition"]

# These parameters will be changed between experiments
   variables = [""]
  
   initpp(dir)  

      ttlon(b1)
      wait(w1)
      ttloff(b1)

   lst = endpp(0) # Return parameter list

# Phase cycle list
  phaseList  = [0]   # Acquire phase

endproc(lst,groups,interface,relationships,variables,0,phaseList)

#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   specPar = gData->specParameters
   if(specPar == null)
      return(null)
   endif
   assignlist(specPar)

   par = ["rxGain         = $rxOptGaindB$"]

endproc(par)