############################################################
#
# Pulse program to generate ttl pulse
#
############################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, ctrltype, vartype)
   interface = ["b1FreqCh1",    "B1 Frequency (MHz)",   "tb",   "float,[0.5,30]";
   #            "TTL1",         "TTL1",                 "tm",   "string,[ \"0x01\", \"0x02\", \"0x04\", \"0x08\", \"0x10\", \"0x20\", \"0x40\", \"0x80\"]";
               "d1",           "delay (us)",          "tb",   "sdelay";
               "repTime",      "Repetition time (ms)", "tb",   "float,[20,1e8]"]

# Relationships to determine remaining variable values
   relationships = [ "freqCh1   = 2",
                #     "b1 = $TTL1$",
                     "d1 = d1"]


# Define the parameter groups and their order
   groups = ["Pulse_sequence","Acquisition"]

# These parameters will be changed between experiments
   variables = [""]

#   if(gData->procType == "DSP")
#      ttl = [0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80]
#   else #(FX3)
#      ttl = [0x01, 0x20, 0x08, 0x02, 0x04, 0x10, 0x80, 0x40]
#   endif
            
   initpp(dir)
      
 #     ttlon(b1)
      ttlon(0x01) # pin 5
      delay(d1)
      ttloff(0x01)
 #     ttloff(b1)
      delay (20)

   lst = endpp(0) # Return parameter list

# Phase cycle list
  phaseList  = [0]   # Acquire phase

endproc(lst,groups,interface,relationships,variables,0,phaseList)

#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   specPar = gData->specParameters
   if(specPar == null)
      return(null)
   endif
   assignlist(specPar)

   par = ["rxGain         = $rxOptGaindB$",
          "pulseLengthCh1 = $pulseLengthCh1$",
          "90AmplitudeCh1 = $pulseAmplitudeCh1$",
          "b1FreqCh1      = $frequencyCh1$"]

endproc(par)