procedure(ethanol)

   peakList = [5.39, 3.63, 1.19]
   
   splittingAmpList = [1/4,2/4,1/4,-1,-1,-1;
                       1/8,4/8,3/8,3/8,4/8,1/8;
                       1*3/4,2*3/4,1*3/4,-1,-1,-1]
   
   splittingFreqList = [-4.6,0,4.6,-1,-1,-1;
                         -9,-4.5,-0.75,0.75,4.5,9;
                         -7.5,0,7.5,-1,-1,-1]
   T1 = 1
   T2 = 1

   result = struct("local")

endproc(result)

