########################################################
#
# CPMGAddPM pulse sequence with dummy pulses
# (following a dummy 180-pulse data is not collected)
#
# 90 - delay - {180 - delay - acq - {180 - delay}}
#
########################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, ctrlType, varType)
   interface = ["b1FreqCh1",         "B1 Frequency (MHz)",    "tb",  "freq";
                "90AmplitudeCh1",  "90 amplitude (dB)",     "tb",  "float,[-85,-6]";
                "180AmplitudeCh1", "180 amplitude (dB)",    "tb",  "pulseamp";
                "pulseLengthCh1",  "Pulse length (us)",     "tb",  "float,[1,500]";
                "echoTime",        "Echotime (us)",         "tb",  "sdelay";
                "nrEchoes",        "Number of echoes",      "tb",  "integer,[1,8192]";
                "echoShift",       "Echo shift (us)",       "tb",  "float,[-20,20]";
                "dummyEchoes",     "Dummy echoes",          "tb",  "integer,[0,100]";
                "dummies",         "Dummy scans",           "tb",  "integer,[0,20]";
                "repTime",         "Repetition time (ms)",  "tb",  "float,[20,1e8]"]

   groups = ["Pulse_sequence","Acquisition","Laplace_CPMG","File_Settings"]


# Relationships between pulse-sequence and GUI parameters
   relationships = ["nxShim = 0", #xcal*xshim/1000", # x shim value
                    "nyShim = 0", #ycal*yshim/1000", # y shim value
                    "nzShim = 0", #zcal*zshim/1000", # z shim value
                    "noShim = 0", #ocal*oshim/1000", # o shim value
                    "a90            = 90AmplitudeCh1",
                    "a180           = 180AmplitudeCh1",
                    "dRF            = pulseLengthCh1",
                    "d90_180        = echoTime/2-(pgo+dRF+1)",
                    "d180_acq       = echoTime/2-acqTime*500-(dRF/2+1)+rxLat+echoShift",
                    "dAcq           = echoTime-d180_acq-(pgo+dRF+1)",
                    "dAcq2          = dAcq+1",
                    "dDummy         = echoTime-(pgo+dRF+1)",
                    "nEchoes        = nrEchoes",
                    "nPnts          = nrPnts",
                    "nZeroDummy     = (dummyEchoes==0)",
                    "nOneDummy      = (dummyEchoes==1)",
                    "nManyDummies   = (dummyEchoes>1)",
                    "nDummies       = dummyEchoes-1",
                    "totPnts        = nrPnts",
                    "totTime        = nrEchoes*echoTime*(dummyEchoes+1)"]

# These parameters will be changed between experiments
   variables = [""]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   gradon("x",nxShim)                    # Set x shim
   gradon("y",nyShim)                    # Set y shim
   gradon("z",nzShim)                    # Set z shim 
   gradon("o",noShim)                    # Set o shim 

   cleardata(nPnts,nEchoes)            # Intialise data for sum/stack mode

# Three options are required to get the timing exact in all cases
# because the loop and skip statments all require 1 us.
   iftrue("s1",nZeroDummy)             # No dummy loop if dummyEchoes == 0
      pulse(mode,a90,p1,dRF)               # 90 RF pulse
      delay(d90_180)                       # 90 - 180 delay
      loop("l1",nEchoes)                   # CPMGAddPM echo loop
         pulse(mode,a180,p2,dRF)              # 180 RF pulse
         delay(d180_acq)                      # 180 - acq delay
         acquire("sum",nPnts,dAcq)         # Acquire echo and add to previous one
      endloop("l1")                        # End CPMGAddPM loop
   endiftrue("s1")

   iftrue("s2",nOneDummy)              # Add dummy loop if dummyEchoes == 1
      pulse(mode,a90,p1,dRF)               # 90 RF pulse
      delay(d90_180)                       # 90 - 180 delay
      loop("l2",nEchoes)                   # CPMGAddPM echo loop
         pulse(mode,a180,p2,dRF)               # 180 RF pulse
         delay(d180_acq)                       # 180 - acq delay
         acquire("sum",nPnts,dAcq2)            # Acquire echo and add to previous one
         pulse(mode,a180,p2,dRF)               # 180 internal pulse
         delay(dDummy)                         # Dummy echo time delay
      endloop("l2")                        # End CPMGAddPM loop
   endiftrue("s2")

   iftrue("s3",nManyDummies)            # Add dummy loop if dummyEchoes > 1
      pulse(mode,a90,p1,dRF)               # 90 RF pulse
      delay(d90_180)                       # 90 - 180 delay
      loop("l3",nEchoes)                   # CPMGAddPM echo loop
         pulse(mode,a180,p2,dRF)              # 180 RF pulse
         delay(d180_acq)                      # 180 - acq delay
         acquire("sum",nPnts,dAcq)            # Acquire echo and add to previous one
         loop("l4",nDummies)                  # Dummy echo loop
            pulse(mode,a180,p2,dRF)               # 180 internal pulse
            delay(dDummy)                         # Dummy echo time delay
         endloop("l4")                        # End dummy loop
         pulse(mode,a180,p2,dRF)              # 180 internal pulse
         delay(dDummy)                        # Dummy echo time delay
      endloop("l3")                        # End CPMGAddPM loop
   endiftrue("s3")

  gradoff("x")                    # Set x shim
  gradoff("y")                    # Set y shim
  gradoff("z")                    # Set z shim 
  gradoff("o")                    # Set o shim 

   lst = endpp(0) # Return parameter list

# Phase cycle

   phaseList = [2,0,2,0; # -x,x,-x,x : 90 phase
                3,1,1,3; # -y,y,y,-y : 180 phase
                2,0,2,0] # -x,x,-x,x : Acquire phase

endproc(lst,groups,interface,relationships,variables,0,phaseList)


#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   probeHeadPars = CPMGAddPM:loadProbeHeadPars()
   assignlist(probeHeadPars)

   specPar = gData->specParameters
   if(specPar == null)
      return(null)
   endif

   par = ["rxGain          = 31",
          "dwellTime       = 0.5",
          "pulseLengthCh1  = $pulseLength$",
          "90AmplitudeCh1  = $90Amplitude$",
          "180AmplitudeCh1 = $180Amplitude$",
          "echoShift       = $echoShift$",
          "rxPhase         = $rxPhase$",
          "b1FreqCh1       = $b1Freq$",
          "gradient        = $gradient$"]

endproc(par)


#####################################################
# Generate some simulated CPMGFast data based on the
# values stored in SimulationInfo and the UI
#####################################################

procedure(simulateNMR, dataSize)

   assignstruct(SimulationInfo) # Get spectrometer parameters

   p90 = round(ppValues->p1/(2*pi)*4)
   p180 = round(ppValues->p2/(2*pi)*4)

   nrPnts    = exptPar->nrPnts
   nrEchoes  = exptPar->nrEchoes
   echoTime  = exptPar->echoTime
   dwellTime = exptPar->dwellTime

# Non-experiment specific parameters
   DW = dwellTime*1e-6 #  This is the dwell time
   sigAmp = signalAmplitude*receiverGain #*nrPnts #  the signal amplitude
   ph = receiverPhase #  the receiver phase
   offFreq = 1e6*(single(b1Freq)-b0Freq) 

   if(p90 == 2 & (p180 == 3 | p180 == 1)) # Phase cycling changes the detected phase
      ph = ph - 180
   endif

   nl = noiseAmplitude*receiverGain*sqrt(1.0/dwellTime) # Generate some noise

   cd(getmacropath())
   cd("$appdir$\\Macros\\KeaExpert\\SimulatorMacros\\Simulated Samples")

   result = sample() # Get sample T2
   T2 = result->T2

   # Central echo times
   te = linspace(echoTime,echoTime*nrEchoes,nrEchoes)*1e-6
   sumEnhancement = sum(exp(-te/T2))

   # Time axis for phase offset
   t1 = ([0:1:nrPnts-1])*dwellTime*1e-6

   # Time axis for calculating echo shape
   t2 = ([0:1:nrPnts-1]-nrPnts/2)*dwellTime*1e-6
   cmat = cmatrix(nrPnts)

   cmat = sigAmp*sumEnhancement*exp(-(t2/T2+t2/T2Star)^2).*exp(i*(2*pi*offFreq*t1 + ph/180*pi))

   mat = ctor(cmat)

   # Add in some noise
   mat = mat + nl*noise(nrPnts*2)*sqrt(sumEnhancement)

endproc(mat)


