#########################################################
# 
# Cal
#
# Cal
# CPMG sequence for calibration.
# www.magritek.com, March 2013
# Prospa V3.12
#
# Copyright (c) Magritek GmbH 2014
#
# U.I. V3
#########################################################

procedure(Cal, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   n = :windowdefinition()

   windowvar(wv_dispMode,wv_ctrls,wv_shift,wv_other,wv_rel,
             wv_pp_list,wv_pp_name,wv_var,wv_tabs,wv_phase_list)

   wv_tabs  = ["Pulse Sequence","acquisition","File settings"] # Tab names
   wv_ctrls = [2,26,27,50,51,71,72,81] # Control groups
   wv_shift = [-14,123,260,263] # Amount to shift control groups
   wv_other = [80,205,462]  # Collapse control and window size
   wv_saved = "false"

   (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar()

   if(nrArgs == 0)
      guipar = "show"
   endif

   keaCtrl:setUp(n,"Cal",getmacropath(),guipar)
   if(guipar == "hide")
      return(n)
   elseif(guipar == "show")
      try; :initGUI(n); catch; endtry;
      showwindow(n)
      return(n)
   else
      setwindowpar(n,"type","dialog")
      guipar = showdialog(n)
      return(guipar)
   endif

endproc()

#########################################################
# 
# Returns important pulse sequence parameters
#
# rel ......... relationship between pulse sequence parameters
# var ......... variable which change during the pulse sequence
# pp_list ..... list of pulse sequence parameters sent to DSP
# pp_name ..... name of DSP pulse program to run
# phase_list .. phase cycling information
#
#########################################################

procedure(getseqpar)

   rel = ["a1 = 90Amplitude",
          "a2 = 180Amplitude",
          "d1 = pulseLength",
          "d2 = echoTime/2-d1-pgo",
          "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
          "d4 = echoTime-d1-pgo-d3",
          "d5 = 2*d1",
          "n1 = nrEchoes",
          "n2 = nrPnts",
          "totPnts = nrPnts",
          "totTime = acqTime"]
   var = ["d1","d2","d3","d4"]
   pp_list = ["a1","p1","d1","d2","n1","l1","a2","p2","d3","n2","d4"]
   pp_name = "Cal.p"
   phase_list = [0,2;1,1;0,2]

endproc(rel,var,pp_list,pp_name,phase_list)


#########################################################
# 
# Provide an interface to this macro which does not
# require the use of the window interface
#
# User must supply a list of parameter (see help file)
# and the pulse program name if different from 
# "$macro$_ext.p"
#
#########################################################

procedure(backdoor, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   (rel,var,pp_list,pp_name,phase_list) = :getseqpar()
  
   (guipar,ppList,pcList,pcIndex,varList) = keaCtrl:initialisePP(getmacropath(),getmacroname(),guipar,rel,var,pp_list,pp_name,phase_list)
   
   r = keaCtrl:runBDPP(guipar,ppList,pcList,pcIndex,varList)

endproc(r)

#########################################################
# 
# Define the window gui
#
#########################################################

procedure(windowdefinition)

   # Automatically generated window definition procedure.
   # Any code added manually will be removed if layout modified interactively
   n = window("Cal", -1, -1, 603, 459)

      # Define all controls with basic parameters
      getmessage(0,
        keaCtrl:processMessage();)
      tab(1, 6, 7, 585, 193,
         which = getpar(0,1,"currenttab");)
      groupbox(2, "Pulse sequence", 9, 9, 577, 130)
      statictext(3, 66, 27, "center", "B1 Frequency (MHz)")
      textbox(4, 43, 41, 46)
      statictext(5, 66, 67, "center", "Repetition time (ms)")
      textbox(6, 43, 82, 46)
      statictext(7, 221, 35, "right", "90 amplitude (dB)")
      textbox(8, 227, 31, 40)
      statictext(9, 221, 61, "right", "180 amplitude (dB)")
      textbox(10, 227, 57, 40)
      statictext(11, 221, 87, "right", "Pulse length (us)")
      textbox(12, 227, 83, 40)
      statictext(13, 376, 35, "right", "Echotime (us)")
      textbox(14, 382, 31, 40)
      statictext(15, 376, 61, "right", "Number of echoes")
      textbox(16, 382, 57, 40)
      statictext(17, 376, 87, "right", "Echo shift (us)")
      textbox(18, 382, 83, 40)
      statictext(19, 376, 113, "right", "Auto-phase")
      checkbox(20, 382, 113, "no,yes", "no")
      statictext(21, 531, 35, "right", "Init. Puls. (us)")
      textbox(22, 537, 31, 40)
      statictext(23, 531, 61, "right", "Increment (us)")
      textbox(24, 537, 57, 40)
      statictext(25, 531, 87, "right", "Number of increm.")
      textbox(26, 537, 83, 40)
      groupbox(27, "Acquisition", 9, 146, 577, 130)
      statictext(28, 91, 166, "center", "Rx Gain (dB)")
      textmenu(29, 74, 184, 39, 200)
      statictext(30, 91, 215, "center", "Rx Phase (degrees)")
      textbox(31, 74, 231, 39)
      statictext(32, 199, 168, "center", "Number of")
      statictext(33, 199, 181, "center", "complex points")
      textmenu(34, 246, 170, 62, 200,
         keaCtrl:updateAcqTime();)
      statictext(35, 199, 200, "center", "Dwell time")
      statictext(36, 199, 213, "center", "(us)")
      textmenu(37, 246, 203, 62, 200,
         keaCtrl:updateFilters();)
      statictext(38, 199, 234, "center", "Number of")
      statictext(39, 199, 247, "center", "scans")
      textbox(40, 246, 235, 62)
      statictext(41, 373, 182, "center", "Flat filter")
      checkbox(42, 409, 183, "no,yes", "no",
           keaCtrl:setDwellTimeMenu();
           keaCtrl:updateFilters();)
      statictext(43, 373, 206, "center", "Accumulate")
      checkbox(44, 409, 207, "no,yes", "no")
      statictext(45, 373, 230, "center", "Phase cycle")
      checkbox(46, 409, 232, "no,yes", "yes")
      statictext(47, 501, 166, "center", "Spectral width (kHz)")
      textbox(48, 472, 180, 56)
      statictext(49, 501, 217, "center", "Acquisition time (ms)")
      textbox(50, 472, 231, 56)
      groupbox(51, "File_Settings", 9, 283, 577, 130)
      statictext(52, 94, 321, "right", "Working")
      statictext(53, 94, 334, "right", "directory")
      textbox(54, 110, 322, 215)
      button(55, 330, 322, 22, 22, "...",
         keaFiles:setWorkingDir();)
      statictext(56, 101, 358, "right", "Experiment")
      statictext(57, 86, 371, "right", "name")
      textbox(58, 110, 361, 105)
      button(59, 221, 361, 22, 22, "...",
         keaFiles:setExpName();)
      statictext(60, 323, 358, "right", "Experiment")
      statictext(61, 313, 371, "right", "number")
      textbox(62, 331, 361, 25)
      button(63, 361, 361, 22, 22, "...",
         keaFiles:setExpNr();)
      statictext(64, 385, 320, "center", "Save")
      statictext(65, 385, 333, "center", "data")
      checkbox(66, 413, 327, "false,true", "true")
      statictext(67, 429, 358, "center", "Auto")
      statictext(68, 429, 371, "center", "increment")
      checkbox(69, 464, 366, "no,yes", "no")
      button(70, 450, 315, 40, 36, "Load Data",
         keaFiles:loadData();)
      button(71, 505, 315, 40, 50, "Open data folder",
         keaFiles:openDataFolder();)
      colorbox(72, 33, 426, 10, 10, [255,255,255,255])
      colorbox(73, 33, 439, 10, 10, [255,255,255,255])
      button(74, 53, 423, 54, 29, "Run",
         (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar();
         keaCtrl:runPP(getmacropath(),wv_pp_name);)
      button(75, 118, 423, 54, 29, "Abort",
         setwindowpar(0,"title","Wait for macro to abort ...");
         wvExpStatus = "stop";)
      button(76, 183, 423, 54, 29, "Finish",
         setwindowpar(0,"title","Wait for phase-cycling to complete ...");
         wvExpStatus = "finish";)
      button(77, 248, 423, 54, 29, "Load Par.",
         keaFiles:loadParameters();)
      button(78, 313, 423, 54, 29, "Help",
         help("Macros\NMR-Mouse","Cal.htm");)
      button(79, 378, 423, 54, 29, "Kea Pref.",
         keaCtrl:showPreferences();)
      button(80, 443, 423, 54, 29, "Collapse",
         keaCtrl:toggleWindowSize(1);)
      button(81, 508, 423, 54, 29, "Close",
         guipar = getctrlvalues(0);
         if(getwindowpar(0,"type") == "dialog");
         guipar = keaFiles:addWindowSpecifics(guipar);
         keaFiles:saveCommonPar(guipar);
         closedialog(guipar);
         else;
         keaFiles:saveParameters();
         closewindow(0);
         endif;)
      menu(82, "bkgMenu", "Edit macro\tCtrl+Dbl-Click", edit("$getmacroname()$"),
                "Show compiler\tCtrl+Shift+Dbl-Click", MakePulseProgram("$getmacropath()$","$rmext(getmacroname())$"))

     # Set other control parameters
      setpar(n,1,"active","true",
                  "inittabs",[""])
      setpar(n,4,"valueID","b1Freq",
                  "tag","freqRange",
                  "type","double",
                  "range",[1,400])
      setpar(n,6,"valueID","repTime",
                  "type","float",
                  "range",[20,1e+008])
      setpar(n,8,"valueID","90Amplitude",
                  "type","float",
                  "range",[-72,0])
      setpar(n,10,"valueID","180Amplitude",
                  "type","float",
                  "range",[-85,0])
      setpar(n,12,"valueID","pulseLength",
                  "type","float",
                  "range",[1,500])
      setpar(n,14,"valueID","echoTime",
                  "type","float",
                  "range",[2,327670])
      setpar(n,16,"valueID","nrEchoes",
                  "type","integer",
                  "range",[1,16000])
      setpar(n,18,"valueID","echoShift",
                  "type","float",
                  "range",[-20,20])
      setpar(n,20,"valueID","autoPhase")
      setpar(n,22,"valueID","p90Ini",
                  "type","float",
                  "range",[1,500])
      setpar(n,24,"valueID","p90Incr",
                  "type","float",
                  "range",[0,500])
      setpar(n,26,"valueID","nrIncr",
                  "type","integer",
                  "range",[1,1000])
      setpar(n,29,"valueID","rxGain",
                  "type","integer",
                  "tooltip","20-40 dB gives optimal SNR.\rDecrease if overload occurs.",
                  "range",[-20,70],
                  "menu",["-20","-17","-14","-11","-8","-5","-2","1","4","7","10","13","16","19","22","25","28","31","34","37","40","43","46","49","52","55","58","61","64","67","70"])
      setpar(n,31,"valueID","rxPhase",
                  "type","float",
                  "tooltip","Applies a fixed phase shift to collected data.\rIgnored if autophasing.")
      setpar(n,34,"valueID","nrPnts",
                  "type","integer",
                  "range",[2,65536],
                  "menu",["2","4","8","16","32","64","128","256","512","1024","2048","4096","8192","16384","32768","65536"])
      setpar(n,37,"valueID","dwellTime",
                  "type","float",
                  "menu",[""])
      setpar(n,40,"valueID","nrScans",
                  "type","integer",
                  "range",[1,1e+006])
      setpar(n,42,"valueID","flatFilter",
                  "tooltip","On: all frequencies equally weighted.\rOff: center frequencies enhanced.")
      setpar(n,44,"valueID","accumulate")
      setpar(n,46,"valueID","usePhaseCycle")
      setpar(n,48,"valueID","bandwidth",
                  "tag","disable")
      setpar(n,50,"valueID","acqTime",
                  "tag","disable")
      setpar(n,54,"valueID","dataDirectory",
                  "type","string",
                  "tooltip","Where experimental data will be stored.")
      setpar(n,58,"valueID","expName",
                  "type","string",
                  "tooltip","A subdirectory of the data working directory to store different experiments.")
      setpar(n,62,"valueID","expNr",
                  "tooltip","A numbered subdirectory below the experiment name.\rNot made if entry is blank.")
      setpar(n,66,"valueID","saveData")
      setpar(n,69,"valueID","incExpNr",
                  "tooltip","Increment the experiment number after each experiment.")
      setpar(n,70,"tooltip","Load and display the data specified in the directories fields")
      setpar(n,71,"tooltip","View the data directory in Windows Explorer.")
      setpar(n,72,"objID","ppStatus",
                  "tooltip","Experiment Status Indicator\rGreen: running\rBlue: processing\rYellow: waiting")
      setpar(n,73,"objID","rxOverflow",
                  "tooltip","Receiver Overflow Indicator\rRed: overflow")
      setpar(n,74,"valueID","run",
                  "tooltip","Start the experiment.")
      setpar(n,75,"valueID","stop",
                  "tooltip","Stop the experiment without saving data.",
                  "active","true")
      setpar(n,76,"valueID","finish",
                  "tooltip","Finish the current phase cycle and save data.",
                  "active","true")
      setpar(n,77,"valueID","load",
                  "tooltip","Load a parameter set for a similar experiment.")
      setpar(n,78,"valueID","help",
                  "tooltip","Display HTML help for this experiment.",
                  "active","true")
      setpar(n,79,"valueID","showPref",
                  "tooltip","Display a preferences dialog for the Kea spectrometer.")
      setpar(n,80,"valueID","size",
                  "tooltip","Expand or collapse the window size to show all or fewer controls.",
                  "active","true")
      setpar(n,81,"valueID","close",
                  "tooltip","Close the window saving all parameters.")

     # Set other window parameters
      setwindowpar(n,"bkgmenu",82)

endproc(n)



#######################################################
# Execute the pulse program, collecting nrScans of 
# data and displaying the result in the 1D plot. 
#
# This procedure can be modified to perform more
# complex functions using the passed parameters:
#
# guipar ..... all parameters from the user interface
# ppList ..... the pulse program parameter list
# pcList ..... phase-cycle list
# pcIndex .... indices of phase parameters in ppList
# varIndex ... indices of variable parameters in ppList
#
#######################################################

procedure(execpp,guipar,ppList,pcList,pcIndex,varIndex)


# Make all gui parameters available
   assignlist(guipar)

# Check for total RF duty cycle
# for PM25----------------------------------------------
     if((p90Incr*(nrIncr-1)+p90Ini)*nrEchoes/repTime>1.6)
# for PM5----------------------------------------------
    # if((p90Incr*(nrIncr-1)+p90Ini)*nrEchoes/repTime>3)
       message("Error","RF duty cycle is too high, reduce nrEchoes or increase repTime","error") 
       return
     endif

# Check for p.s. duty cycle should be < 20%
  if(d1/(echoTime) > 0.30)
      message("Error","Duty cycle is too high in pulse sequence!\rshould be < 30%\rIncrease echo time\ror reduce pulse length.","error")
      return
   endif


# calculate the time axis 
   totalTime = matrix(totPnts)
   totalTime = ([0:1:totPnts-1]/totPnts)*totTime*1000

# Storage for output data   
   nutTime = matrix(nrIncr)
   nutAmp = cmatrix(nrIncr)
   nutTime = [0:1:nrIncr-1]*p90Incr+p90Ini
   
# Define plot regions
  (prt,prn) = wvPP->multiplot(2,1)

# Reset the timer
   time(0)  

   obj = findobj(0,"name","pulseLength")

#  loop number of experiments
   for(m = 0 to nrIncr-1)

  # calculates new d1,d2,d3,d4 values
      d1 = nutTime[m]
      d2 = echoTime/2-d1-pgo
      d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift
      d4 = echoTime-d1-pgo-d3

   if(0==:checkDelay(d1,1)); return; endif
   if(0==:checkDelay(d2,1)); return; endif
   if(0==:checkDelay(d3,1)); return; endif
   if(d4-keaNMR:getAcqTime(guipar) < 1)
      message("Error","Pulse sequence timing error!\rReduce acquisition time or increase echotime.","error")
      abort("")
   endif

  # program new d1,d2,d3,d4 values
      ppList = keaNMR:setPPDelay(ppList,varIndex[0],d1)
      ppList = keaNMR:setPPDelay(ppList,varIndex[1],d2)
      ppList = keaNMR:setPPDelay(ppList,varIndex[2],d3)
      ppList = keaNMR:setPPDelay(ppList,varIndex[3],d4) 

     setpar(0,obj,"text","$d1$")

  # reset sumData
     sumData = cmatrix(totPnts)

   # Accumulate scan
      for(scan = 0 to nrScans-1)
     
       # Note the time at scan start
         t1 = time()   
   
       # Set phases for this scan
         (ppList,pAcq) = keaRun:setPPPhase(ppList,scan,pcList,pcIndex)
      
       # Send phase parameters to DSP
          dspwrite("x",0x00,ppList,wvPort)

       # Collect the data
         (status,data) = keaRun:getData(totPnts,guipar)
         data = data/nrEchoes

        if(status != "ok")
         return(0)
        endif

   
      # Accumlate the data
         sumData = keaNMR:accumulate(accumulate,pAcq,sumData,data)
      # Plot time data 
         :graphTimeLocal(prt,totalTime,sumData,scan,guipar)
      
      # Check timing
         check = keaRun:checkTimeAndAbort(guipar,t1,scan,pcList)
          if(check == "abort")
             return(0)
          elseif(check == "finish")
            exitfor()
          endif
   
      next(scan)
   
      # Plot nutation data
          nutAmp[m]  = sum(sumData)/nrPnts/nrScans

          :graphNutationLocal(prn,nutTime,nutAmp,m,guipar)

   next(m)
#save data
  if(saveData == "true")
         :saveData(guipar,nutTime,nutAmp,m)
      endif

# Increment the experiment number
   keaNMR:incrementExperiment(incExpNr)
        
   keaNMR:titleReset()

endproc("execpp")

#######################################################
# Save the accumulated data
# Either pass the parameters to save or use
# window variables of the same name.
#######################################################

procedure(saveData,guipar,nutTime,nutAmp,count)

# Make all gui parameters available
   assignlist(guipar)

# Save data and plot in chosen folder
   bak = getcwd()

   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   mkdir("$expNr$")
   cd("$expNr$")

   save("data.1d",nutAmp)        # Save data in Prospa format
   save("data.pt1")              # Save plot
   save("data.emf","emf1d")      # Save plot as picture

   n = size(nutAmp)
   m = matrix(3,n)
   m[0,~] = nutTime'
   m[1,~] = real(nutAmp)'
   m[2,~] = imag(nutAmp)'
   
# Save data as aschii file
   export2dpar("ab","ascii","xyrc","real","delimiter","tab")
   export2d(m,"data.dat")  

# Output information to the CLI

  if count==0
   pr "\n  data saved in:"
   pr "\n  $dataDirectory$\\$expName$\\$expNr$"
endif
# Restore cwd
   cd(bak)

endproc("saveData")
#--------------------------------------------------------------------------
procedure(graphTimeLocal,prt,tAxis,fidData,n,guipar,
                    txtTime,xLabel,yLabel,tscale)

   xMap = "lin"
   yMap = "lin"

   assignlist(guipar)

   if(isvar("tscale") == 0)
      tscale = 1
   endif

# Allow for accumulations
   if(accumulate == "yes")
      sf = 1/(n+1)
   else
      sf = 1
   endif

# Select units
   if(wvUnits == "uV")
      timeUnits = "\G(m)V"
      ampMin = wvTimeMin
      ampMax = wvTimeMax
   elseif(wvUnits == "mV")
      timeUnits = "mV"
      ampMin = wvTimeMin/1000
      ampMax = wvTimeMax/1000
    else
      timeUnits = "raw"
      ampMin = wvTimeMin/1000
      ampMax = wvTimeMax/1000
   endif

# Select time axis
   if(tscale == 1 & acqTime > 8) # Switch from us to ms at 5 ms
      tfac = 0.001
   else
      tfac = 1
   endif

# Accumulate text
   if(accumulate == "yes")
      accTxt = "Acc"
   else
      accTxt = "Scan"
   endif

# Select y label
   if(wvApplyPreampFactor == "yes")
      yTxt = "Probe output amplitude"
   elseif(wvApplyRxampFactor == "yes")
      yTxt = "Rx Amp input amplitude"
   else
      yTxt = "Transceiver input amplitude"
   endif

   prt->draw("false")

    # Display time domain data
      prt->plot(tAxis*tfac,fidData*sf)


      if(nrArgs >= 6)
         txtTime = replacestr(txtTime,"SCANS","($accTxt$: $n+1$/$nrScans$)")
         prt->title(txtTime)
      else
         prt->title("Echo Sum data ($accTxt$: $n+1$/$nrScans$)")
      endif

      if(nrArgs >= 7)
         prt->xlabel(xLabel)
      else
         if(tfac == 1)
            prt->xlabel("Time (\G(m)s)")
         else
            prt->xlabel("Time (ms)")
         endif
      endif

     if(nrArgs >= 8)
         prt->ylabel(yLabel)
      else
         prt->ylabel("$yTxt$ ($timeUnits$)")
      endif

      if(wvAutoScale == "no")
         prt->zoom(min(tAxis)*tfac,max(tAxis)*tfac,ampMin,ampMax)
      endif

      prt->axes("xmapping",xMap)
      prt->axes("ymapping",yMap)

   prt->draw("true")


endproc()
#--------------------------------------------------------------------------
procedure(graphNutationLocal,prt,tAxis,fidData,n,guipar,
                    txtTime,xLabel,yLabel,tscale)

   xMap = "lin"
   yMap = "lin"

   assignlist(guipar)

   if(isvar("tscale") == 0)
      tscale = 1
   endif

# Fully accumulated and normalized Data
  sf = 1
   

# Select units
   if(wvUnits == "uV")
      timeUnits = "\G(m)V"
      ampMin = wvTimeMin
      ampMax = wvTimeMax
   elseif(wvUnits == "mV")
      timeUnits = "mV"
      ampMin = wvTimeMin/1000
      ampMax = wvTimeMax/1000
    else
      timeUnits = "raw"
      ampMin = wvTimeMin/1000
      ampMax = wvTimeMax/1000
   endif

# Select time axis
   if(tscale == 1 & acqTime > 8) # Switch from us to ms at 5 ms
      tfac = 0.001
   else
      tfac = 1
   endif

# Accumulate text
   if(accumulate == "yes")
      accTxt = "tp Inc"
   else
      accTxt = "Scan"
   endif

# Select y label
   if(wvApplyPreampFactor == "yes")
      yTxt = "Probe output amplitude"
   elseif(wvApplyRxampFactor == "yes")
      yTxt = "Rx Amp input amplitude"
   else
      yTxt = "Transceiver input amplitude"
   endif

   prt->draw("false")

    # Display time domain data
      prt->plot(tAxis*tfac,fidData*sf,
                  "tracetype","lines",
                  "tracecolor",wvDataSymbolColor,
                  "symbolshape","opensquare",
                  "symbolcolor",wvDataSymbolColor)
               

      if(nrArgs >= 6)
         txtTime = replacestr(txtTime,"SCANS","($accTxt$: $n+1$/$nrIncr$)")
         prt->title(txtTime)
      else
         prt->title("Echo Int ($accTxt$: $n+1$/$nrIncr$)")
      endif

      if(nrArgs >= 7)
         prt->xlabel(xLabel)
      else
         if(tfac == 1)
            prt->xlabel("pulse length (\G(m)s)")
         else
            prt->xlabel("Time (ms)")
         endif
      endif

     if(nrArgs >= 8)
         prt->ylabel(yLabel)
      else
         prt->ylabel("$yTxt$ ($timeUnits$)")
      endif

      if(wvAutoScale == "no")
         prt->zoom(min(tAxis)*tfac,max(tAxis)*tfac,ampMin,ampMax)
      endif

      prt->axes("xmapping",xMap)
      prt->axes("ymapping",yMap)

   prt->draw("true")


endproc()
#--------------------------------------------------------------------------


procedure(checkDelay,dx,limit)
 
   if (dx<= limit)
      message("error","Pulse sequence timing error","error")
      return (0)
   endif 
endproc(1)

