########################################################
# 
# Slice selective spin-echo imaging
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1Freq",        "B1 Frequency (MHz)",        "0","0", "tbw", "freq",
               "repTime",       "Repetition time (ms)",      "0","1", "tbw", "reptime",
               "O1",            "Offset (Hz)",               "0","2", "tbw", "float",
               "a1",            "90 amplitude (dB)",         "0","3", "tb",  "pulseamp",
               "PulseLength90", "90 pulse length (us)",      "0","4", "tb",  "pulselength",
               "SPType",        "Soft pulse shape",          "0","5", "tm",  "60,[\"sinc3\",\"sinc5\",\"gauss\",\"rect\"]",
               "a2",            "180 amplitude (dB)",        "0","6", "tb",  "pulseamp",
               "PulseLength180","180 pulse length (us)",     "0","7", "tb",  "pulselength",

               "echoTime",      "Echotime (us)",             "1","0", "tb",  "sdelay",
               "acqShift",      "acquisition Shift(us)",     "1","1", "tb",  "float,[-1000,1000]",
               "estTimeR",      "estabil. Time read (us)",   "1","2", "tb",  "sdelay",
               "acqShiftRead",  "acqShiftRead (us)",         "1","3", "tb",  "float,[-1000,1000]",
               "sliceComp",     "sliceComp(us)",             "1","4", "tb",  "float,[-1000,1000]",

               "FoVRead",       "FoV Read (mm)",             "2","0", "tb",  "float,[-10000,10000]",
               "FoVPhase1",     "FoV Phase 1 (mm)",          "2","1", "tb",  "float,[-10000,10000]",
               "nrStepsP1",     "nr. pixels phase 1",        "2","2", "tb",  "integer,[1,500]",
               "FoVPhase2",     "FoV Phase 2 (mm)",          "2","3", "tb",  "float,[-10000,10000]",
               "nrStepsP2",     "nr. pixels phase 2",        "2","4", "tb",  "integer,[1,500]",
               "sliceTickness", "Slice thickness (mm)",      "2","5", "tb",  "float,[0,10000]",
               "sliceShift",    "Slice shift (mm)",          "2","6", "tb",  "float,[-10000,10000]",

               "dirRead",       "",                          "2.3","0", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase1",     "",                          "2.3","1", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase2",     "",                          "2.3","3", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirSlice",      "",                          "2.3","5", "tm",  "[\"x\",\"y\",\"z\"]",

               "bDelta",        "BIG delta (us)",            "3.3","0", "tbw",  "sdelay",
               "gradDiffTpm",   "gradient (T/m)",            "3.3","1", "tb",  "float,[-0.35,0.35]",
               "tauDiff",       "little delta (us)",         "3.3","2", "tb",  "sdelay",
               "rampDiff",      "rampDiff (us)",             "3.3","3", "tb",  "sdelay",
               "dirDiff",       "",                          "3.6","1", "tm",  "[\"x\",\"y\",\"z\"]",
               "calc_b",        "calculate b",               "3.3","5", "bt",  "70,25,:calc_b();"]       
     

 # Relationships to determine remaining variable values
  relationships = [ "d1 = PulseLength90",
                    "d500 = 2",     
                    "n500 = round(PulseLength90/d500)",
                    "(t1,t2,gfac) = B1NutSoft:getRFPulse(SPType,a1,n500)",
                    "d2 = PulseLength180",
                    "rampDur = 100",
                    "d300 = 2.5",
                    "n300 = round(rampDur/d300)",
                    "d500 = 2.5",
                    "n500 = round(rampDiff/d500)",
                    "d100 = 100",
                    "d101 = 100",
                    "d20 = tauDiff",
                    "(del9,del99) = SE_3D_DWI:getRewindSliceDelay(PulseLength90,sliceComp,rampDur)",
                    "d99=del99",
                    "d9=del9",   
                    "d6   = estTimeR", 
                    "d3   = 1000*acqTime/2 + d6 - 2.5*rampDur - acqShiftRead",
                    "phDur = d3+2*rampDur+2*0.5*rampDur",
                    "d4   = echoTime/2-PulseLength90/2-d101-d9-d99-d3-PulseLength180/2-pgo-9*rampDur-2*rampDiff-d20",
                    "d5   = bDelta-4*rampDur-d3-d4-pgo-PulseLength180-2*rampDiff-d20",    
                    "d7   = echoTime/2-1000*acqTime/2-d6-PulseLength180/2-1*rampDur+rxLat+acqShift-2*rampDiff-d20-d5",
                    "n10  = SE_3D_DWI:convertDirToChannel(dirRead)",
                    "n20  = SE_3D_DWI:convertDirToChannel(dirPhase1)",
                    "n30  = SE_3D_DWI:convertDirToChannel(dirSlice)",
                    "n40  = SE_3D_DWI:convertDirToChannel(dirPhase2)",
                    "n50  = SE_3D_DWI:convertDirToChannel(dirDiff)",
                    "(gReadAmp,gReadAmpShim,gPhaseAmp1,gPhaseAmpShim1,gPhaseAmp2,gPhaseAmpShim2,gSliceAmp,gSliceAmpShim,sliceOffSet,gDiffAmp,gDiffAmpShim) = SE_3D_DWI:setImageGradients(dirRead,dirPhase1,dirPhase2,dirSlice,dirDiff,FoVRead,FoVPhase1,FoVPhase2,gradDiffTpm,phDur,sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)",
                    "n31 =  gSliceAmp+gSliceAmpShim", 
                    "n31a = gSliceAmpShim", 
                    "n32 = -gSliceAmp+gSliceAmpShim",
                    "n11  =  gReadAmp+gReadAmpShim",
                    "n11a =  gReadAmpShim",
                    "n12  =  gReadAmp+gReadAmpShim",
                    "n12a =  gReadAmpShim",
                    "n21  =  gPhaseAmp1+gPhaseAmpShim1",
                    "n21a =  gPhaseAmpShim1",
                    "n41  =  gPhaseAmp2+gPhaseAmpShim2",
                    "n41a =  gPhaseAmpShim2",
                    "n51  =  gDiffAmp+gDiffAmpShim",
                    "n51a =  gDiffAmpShim",
                    "f1  =  b1Freq+O1/1e6+sliceOffSet",
                    "f2  =  b1Freq+O1/1e6",                  
                    "n1  = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# Define the tabs and their order
   tabs = ["Pulse sequence","Acquisition","Processing+Display","File Settings"]

# These parameters will be changed between experiments
   variables = ["n21","n41"]

# dx,dy
   dim = [170,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list


   settxfreq(f1)                         
   gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
      delay(d100)                          # stabilization time slice
      shapedrf(mode,t1,t2,p1,n500,d500)    # 90 soft pulse
      delay(d99)
   gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF
   
   delay(d101)

   settxfreq(f2)                       
   
   gradramp(n30,n31a,n32,n300,d300)  # SLICE gradient ON
      delay(d9)
   gradramp(n30,n32,n31a,n300,d300)  # SLICE gradient OFF  


   gradramp(n50,n51a,n51,n500,d500)   # Diff gradient ON
      delay(d20)
   gradramp(n50,n51,n51a,n500,d500)   # Diff gradient OFF


   gradramp(n10,n11a,n11,n300,d300)   # READ gradient ON
   gradramp(n20,n21a,n21,n300,d300)   # PHASE gradient ON
   gradramp(n40,n41a,n41,n300,d300)   # PHASE2 gradient ON
      delay(d3)
   gradramp(n10,n11,n11a,n300,d300)   # READ gradient OFF
   gradramp(n20,n21,n21a,n300,d300)   # PHASE gradient OFF
   gradramp(n40,n41,n41a,n300,d300)   # PHASE2 gradient OFF           
   
   delay(d4) 

   pulse(mode,a2,p2,d2)        #180 pulse
   
   delay(d5)

   gradramp(n50,n51a,n51,n500,d500)   # Diff gradient ON
      delay(d20)
   gradramp(n50,n51,n51a,n500,d500)   # Diff gradient OFF

   delay(d7) 

   gradramp(n10,n12a,n12,n300,d300)   # READ gradient ON
      delay(d6)
      acquire("overwrite",n1)
   gradramp(n10,n12,n12a,n300,d300)   # READ gradient OFF


   lst = endpp() # Return parameter list

# Phase cycle list
   phaseList = [0,2; # +x,-x : 90 phase
                1,1; # +y,+y : 180 phase
                0,2] # +x,-x : Acquire phase


endproc(lst,tabs,interface,relationships,variables,dim,phaseList)