procedure(replacestr_test1,verbose,delay)

   txt = "[1 2 3 4 5 6]"
   if(replacestr(txt, " ", ",") != "[1,2,3,4,5,6]")
      return(0, "Invalid result for: replacestr_test1 #1")
   endif  

   txt = "[1 2 3 4 5 6]"
   if(replacestr(txt, " ", ",a") != "[1,a2,a3,a4,a5,a6]")
      return(0, "Invalid result for: replacestr_test1 #2")
   endif  

   txt = "This is a test of the replacestr function"
   if(replacestr(txt, "a test", "not a test") != "This is not a test of the replacestr function")
      return(0, "Invalid result for: replacestr_test1 #3")
   endif 

endproc(1,"")
