

procedure(rmvar_test1,verbose,delay)

   a_loc = 23
   b_loc = 45.45
   c_loc = "hi there"
   d_loc = [1,2;3,4]
   e_loc = {1,2;3,4}
   f_loc = ["1","2","3","4"]
   
   if(not(isvar("a_loc")) | not(isvar("b_loc")) | not(isvar("c_loc")) | 
      not(isvar("d_loc")) | not(isvar("e_loc")) | not(isvar("f_loc"))) 
      return(0, "Invalid result for: rmvar_test1 #1")
   endif 

   rmvar("a_loc","b_loc","c_loc","d_loc","e_loc","f_loc")

   if(isvar("a_loc") | isvar("b_loc") | isvar("c_loc") | isvar("d_loc") | isvar("e_loc") | isvar("f_loc")) 
      return(0, "Invalid result for: rmvar_test1 #2")
   endif 

endproc(1,"")

