

procedure(retvar_test1,verbose,delay)


   if(retvar(:test_call(),1) != 1)
      return(0, "Invalid result for: retvar_test1 #1")
   endif 

   if(retvar(:test_call(),2) != 2)
      return(0, "Invalid result for: retvar_test1 #2")
   endif 

   if(retvar(:test_call(),3) != 3)
      return(0, "Invalid result for: retvar_test1 #3")
   endif 

   if(retvar(:test_call(),4) != 4)
      return(0, "Invalid result for: retvar_test1 #4")
   endif 

endproc(1,"")

procedure(test_call)


endproc(1,2,3,4)
