#########################################################
# 
# autoshim
#
# 1pulse - acq
#
# Auto shim, order 1
# Copyright (c) Magritek Ltd 2014
#
# U.I. V3
#########################################################

procedure(autoshim, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   n = :windowdefinition()

   windowvar(wv_dispMode,wv_ctrls,wv_shift,wv_other,wv_rel,
             wv_pp_list,wv_pp_name,wv_var,wv_tabs,wv_phase_list)

   wv_tabs  = ["Pulse Sequence","acquisition","processing+display","File settings"] # Tab names
   wv_ctrls = [2,30,31,54,55,68,69,89,90,99] # Control groups
   wv_shift = [-14,137,288,439,442] # Amount to shift control groups
   wv_other = [98,219,655]  # Collapse control and window size
   wv_saved = "false"

   (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar()

   if(nrArgs == 0)
      guipar = "show"
   endif

   keaCtrl:setUp(n,"autoshim",getmacropath(),guipar)
   if(guipar == "hide")
      return(n)
   elseif(guipar == "show")
      try; :initGUI(n); catch; endtry;
      showwindow(n)
      return(n)
   else
      setwindowpar(n,"type","dialog")
      guipar = showdialog(n)
      return(guipar)
   endif

endproc()

#########################################################
# 
# Returns important pulse sequence parameters
#
# rel ......... relationship between pulse sequence parameters
# var ......... variable which change during the pulse sequence
# pp_list ..... list of pulse sequence parameters sent to DSP
# pp_name ..... name of DSP pulse program to run
# phase_list .. phase cycling information
#
#########################################################

procedure(getseqpar)

   rel = ["a1 = 90Amplitude",
          "d1 = pulseLength",
          "d2 = 50",
          "n1 = nrPnts",
          "n10 = xcal*xshim",
          "n11 = ycal*yshim",
          "n12 = zcal*zshim",
          "n13 = ocal*oshim",
          "totPnts = nrPnts",
          "totTime = acqTime"]
   var = ["n10","n11","n12","n13"]
   pp_list = ["n10","n11","n12","n13","a1","p1","d1","d2","n1"]
   pp_name = "autoshim.p"
   phase_list = [0;0]

endproc(rel,var,pp_list,pp_name,phase_list)


#########################################################
# 
# Provide an interface to this macro which does not
# require the use of the window interface
#
# User must supply a list of parameter (see help file)
# and the pulse program name if different from 
# "$macro$_ext.p"
#
#########################################################

procedure(backdoor, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   (rel,var,pp_list,pp_name,phase_list) = :getseqpar()
  
   (guipar,ppList,pcList,pcIndex,varList) = keaCtrl:initialisePP(getmacropath(),getmacroname(),guipar,rel,var,pp_list,pp_name,phase_list)
   
   r = keaCtrl:runBDPP(guipar,ppList,pcList,pcIndex,varList)

endproc(r)

#########################################################
# 
# Define the window gui
#
#########################################################

procedure(windowdefinition)

   # Automatically generated window definition procedure.
   # Any code added manually will be removed if layout modified interactively
   n = window("autoshim", -1, -1, 577, 652)

      # Define all controls with basic parameters
      getmessage(0,
        keaCtrl:processMessage();)
      tab(1, 6, 7, 559, 207,
         which = getpar(0,1,"currenttab");
         if(which == 2);
         fn = findobj(0,"name","filter");
         keaCtrl:enableControls(fn+1,fn+3,fn);
         fn = findobj(0,"name","showFreqDomain");
         keaCtrl:enableControls(fn+1,fn+4,fn);
         endif();)
      groupbox(2, "Pulse sequence", 9, 9, 551, 144)
      statictext(3, 66, 27, "center", "B1 Frequency (MHz)")
      textbox(4, 43, 42, 46)
      statictext(5, 66, 67, "center", "Repetition time (ms)")
      textbox(6, 43, 82, 46)
      statictext(7, 66, 104, "center", "Offset (Hz)")
      textbox(8, 43, 119, 46)
      statictext(9, 221, 35, "right", "90 amplitude (dB)")
      textbox(10, 227, 31, 40)
      statictext(11, 221, 61, "right", "Pulse length (us)")
      textbox(12, 227, 57, 40)
      statictext(13, 221, 87, "right", "nr Shim Loops")
      textbox(14, 227, 83, 40)
      statictext(15, 376, 35, "right", "xstep")
      textbox(16, 382, 31, 40)
      statictext(17, 376, 61, "right", "ystep")
      textbox(18, 382, 57, 40)
      statictext(19, 376, 87, "right", "zstep")
      textbox(20, 382, 83, 40)
      statictext(21, 376, 113, "right", "ostep")
      textbox(22, 382, 109, 40)
      statictext(23, 531, 35, "right", "shim x")
      checkbox(24, 537, 35, "no,yes", "no")
      statictext(25, 531, 61, "right", "shim y")
      checkbox(26, 537, 61, "no,yes", "no")
      statictext(27, 531, 87, "right", "shim z")
      checkbox(28, 537, 87, "no,yes", "no")
      statictext(29, 531, 113, "right", "shim o")
      checkbox(30, 537, 113, "no,yes", "no")
      groupbox(31, "Acquisition", 9, 160, 551, 144)
      statictext(32, 78, 187, "center", "Rx Gain (dB)")
      textmenu(33, 61, 205, 39, 200)
      statictext(34, 78, 236, "center", "Rx Phase (degrees)")
      textbox(35, 61, 252, 39)
      statictext(36, 186, 189, "center", "Number of")
      statictext(37, 186, 202, "center", "complex points")
      textmenu(38, 233, 191, 62, 200,
         keaCtrl:updateAcqTime();)
      statictext(39, 186, 221, "center", "Dwell time")
      statictext(40, 186, 234, "center", "(us)")
      textmenu(41, 233, 224, 62, 200,
         keaCtrl:updateFilters();)
      statictext(42, 186, 255, "center", "Number of")
      statictext(43, 186, 268, "center", "scans")
      textbox(44, 233, 256, 62)
      statictext(45, 360, 203, "center", "Flat filter")
      checkbox(46, 396, 204, "no,yes", "no",
           keaCtrl:setDwellTimeMenu();
           keaCtrl:updateFilters();)
      statictext(47, 360, 227, "center", "Accumulate")
      checkbox(48, 396, 228, "no,yes", "no")
      statictext(49, 360, 251, "center", "Phase cycle")
      checkbox(50, 396, 253, "no,yes", "yes")
      statictext(51, 488, 187, "center", "Spectral width (kHz)")
      textbox(52, 459, 201, 56)
      statictext(53, 488, 238, "center", "Acquisition time (ms)")
      textbox(54, 459, 252, 56)
      groupbox(55, "Processing_Display", 9, 311, 551, 144)
      statictext(56, 208, 346, "right", "Filter time domain")
      checkbox(57, 216, 347, "no,yes", "no",
           fn = findobj(0,"name","filter");
           keaCtrl:enableControls(fn+1,fn+3,fn);)
      statictext(58, 90, 377, "right", "Filter")
      textmenu(59, 97, 373, 108, 200)
      button(60, 214, 373, 22, 22, "...",
         filters();)
      statictext(61, 208, 409, "right", "Time domain magnitude")
      checkbox(62, 216, 410, "no,yes", "no")
      statictext(63, 479, 344, "right", "Show frequency domain data")
      checkbox(64, 487, 345, "no,yes", "no",
           fn = findobj(0,"name","showFreqDomain");
           keaCtrl:enableControls(fn+1,fn+4,fn);)
      statictext(65, 479, 374, "right", "Frequency domain magnitude")
      checkbox(66, 487, 375, "no,yes", "no")
      statictext(67, 429, 407, "right", "Display range (kHz)")
      textbox(68, 439, 404, 61)
      groupbox(69, "File_Settings", 9, 462, 551, 144)
      statictext(70, 81, 507, "right", "Working")
      statictext(71, 81, 520, "right", "directory")
      textbox(72, 97, 508, 215)
      button(73, 317, 508, 22, 22, "...",
         keaFiles:setWorkingDir();)
      statictext(74, 88, 544, "right", "Experiment")
      statictext(75, 73, 557, "right", "name")
      textbox(76, 97, 547, 105)
      button(77, 208, 547, 22, 22, "...",
         keaFiles:setExpName();)
      statictext(78, 310, 544, "right", "Experiment")
      statictext(79, 300, 557, "right", "number")
      textbox(80, 318, 547, 25)
      button(81, 348, 547, 22, 22, "...",
         keaFiles:setExpNr();)
      statictext(82, 372, 506, "center", "Save")
      statictext(83, 372, 519, "center", "data")
      checkbox(84, 400, 513, "false,true", "true")
      statictext(85, 416, 544, "center", "Auto")
      statictext(86, 416, 557, "center", "increment")
      checkbox(87, 451, 552, "no,yes", "no")
      button(88, 437, 501, 40, 36, "Load Data",
         keaFiles:loadData();)
      button(89, 492, 501, 40, 50, "Open data folder",
         keaFiles:openDataFolder();)
      colorbox(90, 20, 619, 10, 10, [255,255,255,255])
      colorbox(91, 20, 632, 10, 10, [255,255,255,255])
      button(92, 40, 616, 54, 29, "Run",
         (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar();
         keaCtrl:runPP(getmacropath(),wv_pp_name);)
      button(93, 105, 616, 54, 29, "Abort",
         setwindowpar(0,"title","Wait for macro to abort ...");
         wvExpStatus = "stop";)
      button(94, 170, 616, 54, 29, "Finish",
         setwindowpar(0,"title","Wait for phase-cycling to complete ...");
         wvExpStatus = "finish";)
      button(95, 235, 616, 54, 29, "Load Par.",
         keaFiles:loadParameters();)
      button(96, 300, 616, 54, 29, "Help",
         help("Macros\Tomograph","autoshim.htm");)
      button(97, 365, 616, 54, 29, "Kea Pref.",
         keaCtrl:showPreferences();)
      button(98, 430, 616, 54, 29, "Collapse",
         keaCtrl:toggleWindowSize(1);)
      button(99, 495, 616, 54, 29, "Close",
         guipar = getctrlvalues(0);
         if(getwindowpar(0,"type") == "dialog");
         guipar = keaFiles:addWindowSpecifics(guipar);
         keaFiles:saveCommonPar(guipar);
         closedialog(guipar);
         else;
         keaFiles:saveParameters();
         closewindow(0);
         endif;)
      menu(100, "bkgMenu", "Edit macro\tCtrl+Dbl-Click", edit("$getmacroname()$"),
                "Show compiler\tCtrl+Shift+Dbl-Click", MakePulseProgram("$getmacropath()$","$rmext(getmacroname())$"))

     # Set other control parameters
      setpar(n,1,"active","true",
                  "inittabs",[""])
      setpar(n,4,"valueID","b1Freq",
                  "type","float",
                  "range",[0.5,50])
      setpar(n,6,"valueID","repTime",
                  "type","float",
                  "range",[20,1e+008])
      setpar(n,8,"valueID","O1",
                  "type","float",
                  "range",[-1e+006,1e+006])
      setpar(n,10,"valueID","90Amplitude",
                  "type","float",
                  "range",[-72,0])
      setpar(n,12,"valueID","pulseLength",
                  "type","float",
                  "range",[1,500])
      setpar(n,14,"valueID","nrLoops",
                  "type","integer",
                  "range",[1,300])
      setpar(n,16,"valueID","xstep",
                  "type","float",
                  "range",[-1,1])
      setpar(n,18,"valueID","ystep",
                  "type","float",
                  "range",[-1,1])
      setpar(n,20,"valueID","zstep",
                  "type","float",
                  "range",[-1,1])
      setpar(n,22,"valueID","ostep",
                  "type","float",
                  "range",[-20,20])
      setpar(n,24,"valueID","xEnable")
      setpar(n,26,"valueID","yEnable")
      setpar(n,28,"valueID","zEnable")
      setpar(n,30,"valueID","oEnable")
      setpar(n,33,"valueID","rxGain",
                  "type","integer",
                  "tooltip","20-40 dB gives optimal SNR.\rDecrease if overload occurs.",
                  "range",[-20,70],
                  "menu",["-20","-17","-14","-11","-8","-5","-2","1","4","7","10","13","16","19","22","25","28","31","34","37","40","43","46","49","52","55","58","61","64","67","70"])
      setpar(n,35,"valueID","rxPhase",
                  "type","float",
                  "tooltip","Applies a fixed phase shift to collected data.\rIgnored if autophasing.")
      setpar(n,38,"valueID","nrPnts",
                  "type","integer",
                  "range",[2,65536],
                  "menu",["2","4","8","16","32","64","128","256","512","1024","2048","4096","8192","16384","32768","65536"])
      setpar(n,41,"valueID","dwellTime",
                  "type","float",
                  "menu",[""])
      setpar(n,44,"valueID","nrScans",
                  "type","integer",
                  "range",[1,1e+006])
      setpar(n,46,"valueID","flatFilter",
                  "tooltip","On: all frequencies equally weighted.\rOff: center frequencies enhanced.")
      setpar(n,48,"valueID","accumulate")
      setpar(n,50,"valueID","usePhaseCycle")
      setpar(n,52,"valueID","bandwidth",
                  "tag","disable")
      setpar(n,54,"valueID","acqTime",
                  "tag","disable")
      setpar(n,57,"valueID","filter")
      setpar(n,59,"valueID","filterType",
                  "menu",[""])
      setpar(n,62,"valueID","timeMag")
      setpar(n,64,"valueID","showFreqDomain")
      setpar(n,66,"valueID","freqMag")
      setpar(n,68,"valueID","dispRange",
                  "type","float")
      setpar(n,72,"valueID","dataDirectory",
                  "type","string",
                  "tooltip","Where experimental data will be stored.")
      setpar(n,76,"valueID","expName",
                  "type","string",
                  "tooltip","A subdirectory of the data working directory to store different experiments.")
      setpar(n,80,"valueID","expNr",
                  "tooltip","A numbered subdirectory below the experiment name.\rNot made if entry is blank.")
      setpar(n,84,"valueID","saveData")
      setpar(n,87,"valueID","incExpNr",
                  "tooltip","Increment the experiment number after each experiment.")
      setpar(n,88,"tooltip","Load and display the data specified in the directories fields")
      setpar(n,89,"tooltip","View the data directory in Windows Explorer.")
      setpar(n,90,"objID","ppStatus",
                  "tooltip","Experiment Status Indicator\rGreen: running\rBlue: processing\rYellow: waiting")
      setpar(n,91,"objID","rxOverflow",
                  "tooltip","Receiver Overflow Indicator\rRed: overflow")
      setpar(n,92,"valueID","run",
                  "tooltip","Start the experiment.")
      setpar(n,93,"valueID","stop",
                  "tooltip","Stop the experiment without saving data.",
                  "active","true")
      setpar(n,94,"valueID","finish",
                  "tooltip","Finish the current phase cycle and save data.",
                  "active","true")
      setpar(n,95,"valueID","load",
                  "tooltip","Load a parameter set for a similar experiment.")
      setpar(n,96,"valueID","help",
                  "tooltip","Display HTML help for this experiment.",
                  "active","true")
      setpar(n,97,"valueID","showPref",
                  "tooltip","Display a preferences dialog for the Kea spectrometer.")
      setpar(n,98,"valueID","size",
                  "tooltip","Expand or collapse the window size to show all or fewer controls.",
                  "active","true")
      setpar(n,99,"valueID","close",
                  "tooltip","Close the window saving all parameters.")

     # Set other window parameters
      setwindowpar(n,"bkgmenu",100)

endproc(n)


#######################################################
# Execute the pulse program, collecting nrScans of 
# data and displaying the result in the 1D plot. 
#
# This procedure can be modified to perform more
# complex functions using the passed parameters:
#
# guipar ..... all parameters from the user interface
# ppList ..... the pulse program parameter list
# pcList ..... phase-cycle list
# pcIndex .... indices of phase parameters in ppList
# varIndex ... indices of variable parameters in ppList
#
#######################################################

procedure(execpp,guipar,ppList,pcList,pcIndex,varIndex)

# Make all gui parameters available
   assignlist(guipar)

   wvPP->multiplot(4,1)
   winNr1d = wvPP->parent()->winnr()
   winNr2d = wvPP2->parent()->winnr()

   time(0)  

   shimMode = 10

   bufferLW50 = matrix(nrScans)
   bufferLW10 = matrix(nrScans)

   shimLst =:loadValues()
   assignlist(shimLst)

   xshim0    = xshim
   yshim0    = yshim
   zshim0    = zshim
   oshim0    = oshim

   dummyScans = 4
   nrPntsShim = 3
   nrChannels = 4 

   shimAxis= matrix(nrPntsShim)

   count = 0
   for(m=0 to nrLoops-1)

      if(m>0) ;dummyScans = 0; endif

      k = -1
      while(k<nrChannels+1)
   
         LWAxis  = matrix(nrPntsShim)
   
         if(k==-1)
            scanIni = -dummyScans
            scanFin = -1
         endif
         if(k==0)  
            channel  = "x"
            if eval("$channel$Enable") == "no"; k=k+1;endif
            scanIni = 0
            scanFin = nrPntsShim-1
         endif
         if(k==1)
            channel  = "y"
            if eval("$channel$Enable") == "no"; k=k+1;endif
         endif
         if(k==2)
            channel  = "z"
            if eval("$channel$Enable") == "no"; k=k+1;endif
         endif
         if(k==3)
            channel  = "o"
            if eval("$channel$Enable") == "no"; k=k+1;endif
         endif
           if(k==4)
            scanIni = -100
            scanFin = -99
         endif
            
            bestLW = 0
            dir = 1
            scans = scanIni
   
            if (k>-1)
               nextShimVal = eval("$channel$shim0")
               shimStep    = eval("$channel$step")
               shim0       = eval("$channel$shim0")
            endif
   
            while(scans<scanFin+1)

             # Note the time at scan start
               t1 = time()
   
               if(scans>-1)
                  shimLst = setlistvalue(shimLst,"$channel$shim","$nextShimVal$")
               endif
             
               (LW50,LW10) = :runExp(shimLst,guipar,ppList,pcList,pcIndex,varIndex)
   
               if((scans==-dummyScans)&(m==0)); bufferLW50 = bufferLW50+LW50; endif
               if((scans==-dummyScans)&(m==0)); bufferLW10 = bufferLW10+LW10; endif

               bufferLW50[0] =  LW50; bufferLW50  = rotate(bufferLW50,-1);# bufferLW50[0] = 0
               bufferLW10[0] =  LW10; bufferLW10  = rotate(bufferLW10,-1);# bufferLW10[0] = 0
         
            # plots line width at 50%
               pd = curplot("1d",2,1)
               if(shimMode==50)
                  lb = pd->title()
                  lb->color(blue)
                  lb->size(16)
               endif      
               pd->draw("false")
               pd->plot(bufferLW50,"tracewidth",1.5)
               if((scans>-1)&(shimMode==50))
                     pd->title("LW_(50) = $0.01*round(100*bufferLW50[size(bufferLW50)-1])$ Hz, $channel$shim:$nextShimVal$")
               else
                     pd->title("LW_(50) = $0.01*round(100*bufferLW50[size(bufferLW50)-1])$ Hz")
               endif
               pd->xlabel("text","n")
               pd->ylabel("text","LW(Hz)")
               pd->draw("true")

            # plots line width at 10%
               pd = curplot("1d",3,1)
               if(shimMode==10)
                  lb = pd->title()
                  lb->color(blue)
                  lb->size(16)
               endif         
               pd->draw("false")
               pd->plot(bufferLW10,"tracewidth",1.5)
               if((scans>-1)&(shimMode==10))
                  pd->title("text","LW_(10) = $0.1*round(10*bufferLW10[size(bufferLW10)-1])$ Hz, $channel$shim:$0.001*round(1000*nextShimVal)$")
               else
                  pd->title("text","LW_(10) = $0.1*round(10*bufferLW10[size(bufferLW10)-1])$ Hz")
               endif
               pd->xlabel("text","n")
               pd->ylabel("text","LW(Hz)")
               pd->draw("true")
   
               if(shimMode==50)
                  LW = LW50
               endif
               if(shimMode==10)
                  LW = LW10
               endif
            #------------------------------------------
               if(scans==0)
                  bestLW      = LW
                  LWAxis[1]   = LW
                  shimAxis[1] = nextShimVal
                  nextShimVal = nextShimVal + dir*shimStep
               endif
            #------------------------------------------
               if(scans==1)
                  LWAxis[2]   = LW
                  shimAxis[2] = nextShimVal
                  if(LW<bestLW)
                     bestLW      = LW
                     shimAxis = rotate(shimAxis,-1)
                     LWAxis = rotate(LWAxis,-1)
                     nextShimVal = nextShimVal + dir*shimStep
                  else
                     dir = -dir
                     nextShimVal = nextShimVal + 2*dir*shimStep
                  endif
               endif
            #------------------------------------------
               if(scans==2)  
                  LWAxis[1+dir]   = LW
                  shimAxis[1+dir] = nextShimVal             
                  if(LW>bestLW)

                  else
                     bestLW = LW 
                     shimAxis = rotate(shimAxis,-dir)
                     LWAxis   = rotate(LWAxis,-dir)
                     nextShimVal = nextShimVal + dir*shimStep 
                     scans = scans-1
                  endif
               endif
               scans = scans+1
               count = count+1

   
               szBufLW = size(bufferLW50)
   
               if(count> szBufLW-2)
                 bufferLWcopy = bufferLW50
                 bufferLW50 = matrix(szBufLW+nrScans)
                 bufferLW50 = bufferLW50 + bufferLWcopy[0]
                 for l=0 to szBufLW-1 
                   bufferLW50[l+nrScans] = bufferLWcopy[l]
                 next l
               endif

               szBufLW = size(bufferLW10)
   
               if(count> szBufLW-2)
                 bufferLWcopy = bufferLW10
                 bufferLW10 = matrix(szBufLW+nrScans)
                 bufferLW10 = bufferLW10 + bufferLWcopy[0]
                 for l=0 to szBufLW-1 
                   bufferLW10[l+nrScans] = bufferLWcopy[l]
                 next l
               endif
 
               check = keaRun:checkTimeAndAbort(guipar,t1,scans,pcList)
               if(check == "abort")
                  return(0)
               elseif(check == "finish")
                  scans = scans+1
                  k = nrChannels +100
                  exitwhile()
               endif
   
            endwhile()
   
            if((-1<k)&(k<nrChannels))
               newshim = :fitShim(shimAxis,LWAxis,shim0,channel,shimMode)
               shimLst = setlistvalue(shimLst,"$channel$shim","$newshim$")       
            endif
   
            k = k+1

         endwhile()

         :saveValues(shimLst)

   #  best shim values
   
         xshim0    = eval(getlistvalue(shimLst,"xshim"))
         yshim0    = eval(getlistvalue(shimLst,"yshim"))
         zshim0    = eval(getlistvalue(shimLst,"zshim"))
         oshim0    = eval(getlistvalue(shimLst,"oshim"))


         pr "\n"
         pr "loop = $m$, L50 = $0.01*round(100*LW50)$ Hz, L10 = $0.1*round(10*LW10)$ Hz\n"

         if(saveData == "true")
            :saveData(guipar,shimLst)
         endif

      next(m)

endproc("execpp")
#--------------------------------------------------------------------
procedure(saveData,guipar,shimLst)

   assignlist(guipar)
   name = getmacroname()
   name = rmext(name)

   str = getmacropath()
   sz = size(str)
   nada = "c\\a"
   for k = sz-1 to 0 step -1
      if str[k] == nada[1]
       kini = k 
       exitfor
      endif
   next k
   folder = submatrix(str,kini+1,sz-1)

   fullpath = "$prefdir$\\keaParameters\\Experiments\\$folder$\\$name$"
   cd(fullpath)

   lastPar = load("$name$LastExp.par")
   expNr = eval(getlistvalue(lastPar,"expNr"))
   lastPar =  setlistvalue(lastPar,"expNr","$expNr+1$")
   save("$name$LastExp.par",lastPar)

   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   mkdir("$expNr$")
   cd("$expNr$")
   save("shims.par",shimLst)
   save("guipar.par",guipar)

   cd(bak)

# Increment the experiment number
   keaNMR:incrementExperiment(incExpNr)

endproc("saveData")

#-----------------------------
procedure(measureLineWidth,level,x,y,kmax)

   level = level/100
   amp = y[kmax]
   kL = findindex2(y,kmax,"left",amp*level)

   if(y[kL]>amp*level)
      xL = :findRoot(x[kL],y[kL],x[kL-1],y[kL-1],amp*level)
   else
      xL = :findRoot(x[kL],y[kL],x[kL+1],y[kL+1],amp*level)
   endif

   kR = findindex2(y,kmax,"right",amp*level)

   if(y[kR]>amp*level)
      xR = :findRoot(x[kR],y[kR],x[kR+1],y[kR+1],amp*level)
   else
      xR = :findRoot(x[kR],y[kR],x[kR-1],y[kR-1],amp*level)
   endif

   linewidth = (xR-xL)

endproc(linewidth)
#----------------------------------------------------------
procedure(findRoot,x1,y1,x2,y2,y0)
     x0 = x1 + (y0-y1)*(x2-x1)/(y2-y1)
endproc(x0)
#-------------------------------------------------------------------------------
procedure(runExp,shimsLst,guipar,ppList,pcList,pcIndex,varIndex)

# Make all gui parameters available
   assignlist(guipar)
   assignlist(shimsLst)

   sumData = cmatrix(totPnts)
   
   zf = 16*:FFTsize(nrPnts)
   f = ([0:1:zf-1]-zf/2)*bandwidth/zf
  (fIni,fFin) = findindex(f,-dispRange/2,dispRange/2)

   ppList = keaRun:setPPNumber(ppList,varIndex[0],xshim*xcal/1000)
   ppList = keaRun:setPPNumber(ppList,varIndex[1],yshim*ycal/1000)
   ppList = keaRun:setPPNumber(ppList,varIndex[2],zshim*zcal/1000)
   ppList = keaRun:setPPNumber(ppList,varIndex[3],oshim*ocal/1000)
#pr xshim*ocal/1000
#pr yshim*ocal/1000
#pr zshim*ocal/1000

# Accumulate scans
   nrScans = 1
   for(scans = 0 to nrScans-1)

    # Note the time at scan start
      t1 = time()

    # Set phases for this scan
      (ppList,pAcq) = keaRun:setPPPhase(ppList,scans,pcList,pcIndex)

    # Send phase parameters to DSP
      dspwrite("x",0x00,ppList)
       
    # Collect the data
      (status,data) = keaRun:getData(totPnts,guipar)

      if(status != "ok")
         keaRun:enableButtons()
         abort("")
      endif
      data = rotate(data,1)
      data[nrPnts-1]=0
      
      # Accumlate the data
      sumData = keaRun:accumulate(accumulate,pAcq,sumData,data)


   # get cordinates of the peak, freq and amplitude
      (y2,x2)=  max(mag(spectrum))

       a_m = y2
       f_m = f[x2]

   # measure linewidth 
      LW50 = 1000*:measureLineWidth(50,f,real(spectrum),x2)
      LW10 = 1000*:measureLineWidth(10,f,real(spectrum),x2)

   # plots spectrum

      pd = curplot("1d",1,1)

      pd->draw("false")
      if(freqMag=="yes") 
          pd->plot(f,mag(spectrum))
      else
          pd->plot(f,spectrum,"realcolor",[0,0,0],"imagcolor",[255,0,0])
      endif
      pd->zoom(f_m-dispRange/2,f_m+dispRange/2)
      pd->title("text","spectrum")
      pd->xlabel("text","frequency (kHz)")
      pd->ylabel("text","amplitide")
      pd->draw("true")

   next(scans)

endproc(LW50,LW10)
#------------------------------------------------------------

procedure(fitShim,dx,Ax,shim0,channel,shimMode)
      
   nrPntsX = size(dx)
   center = (dx[nrPntsX-1]+dx[0])/2
   range = dx[nrPntsX-1]-dx[0]
   dx = dx-center
   
   (fit,a0,a1,a2,e0,e1,chq) = polyfit(dx,Ax,2,1,1,"false")        
   fac = 8
   dxNew = [-(fac*nrPntsX-1)/2:1:(fac*nrPntsX-1)/2]*range/(fac*nrPntsX)
   
   fit2 = a0 + a1*dxNew + a2*dxNew^2
   (nada,ind) = min(fit2)
   newxshim = dxNew[ind]

   pd = curplot("1d",4,1)
   lb = pd->title()
   lb->color(blue)
   lb->size(14)
   pd->draw("false")
   pd->plot(dx,Ax,"tracetype","none","symbolshape","square","symbolcolor",black)
   pd->hold("on")
   pd->plot(dxNew,fit2,"tracecolor",red)
   pd->title("text","$channel$shim   OLD:$0.001*round(1000*shim0)$,   NEW:$0.001*round(1000*(newxshim+center))$")
   pd->xlabel("text","\G(D) $channel$shim")
   pd->ylabel("text","LW_($shimMode$)(Hz)")
   pd->hold("off")
   pd->draw("true")

endproc(newxshim+center)
#----------------------------------------------------
procedure(updateShimController,prefLst)

   n = ShimsController:ShimsController() 
   pause(1)
   assignlist(prefLst)
   newPar = ["g0Slider = $xshim$","g0Text = $xshim$"]
   newPar = setlistvalue(newPar,"g1Slider","$yshim$")
   newPar = setlistvalue(newPar,"g1Text"  ,"$yshim$")
   newPar = setlistvalue(newPar,"g2Slider","$zshim$")
   newPar = setlistvalue(newPar,"g2Text"  ,"$zshim$")
   newPar = setlistvalue(newPar,"g3Slider","$z2shim$")
   newPar = setlistvalue(newPar,"g3Text"  ,"$z2shim$")
   newPar = setlistvalue(newPar,"g4Slider","$xzshim$")
   newPar = setlistvalue(newPar,"g4Text"  ,"$xzshim$")
   newPar = setlistvalue(newPar,"g5Slider","$yzshim$")
   newPar = setlistvalue(newPar,"g5Text"  ,"$yzshim$")
   newPar = setlistvalue(newPar,"g6Slider","$x2y2shim$")
   newPar = setlistvalue(newPar,"g6Text"  ,"$x2y2shim$")
   newPar = setlistvalue(newPar,"g7Slider","$xyshim$")
   newPar = setlistvalue(newPar,"g7Text"  ,"$xyshim$")
   setctrlvalues(n,newPar)
   pause(1)
   ShimsController:saveShims()
   closewindow(n)

endproc()
#--------------------------------------------------------
procedure(closeShimController)

# close shim controller
   for k =1 to 100
     try
         if (getwindowpar(k,"title")=="Shims Controller")
           closewindow(k)
         endif
     catch
         exitfor
     endtry
   next k

endproc()
#-----------------------------
procedure(FFTsize,nrPnts)

  m=1
  a = nrPnts
  while(a>1)
     a = nrPnts/2^m
     m = m+1
  endwhile
  r = 2^(m-1)

endproc(r)

#-----------------------------------
procedure(loadValues)

   lst = keaNMR:loadPref()
   assignlist(lst)

   par = ["xshim = $xshim$",
          "yshim = $yshim$",
          "zshim = $zshim$",
          "oshim = $oshim$"]
   

endproc(par)
#----------------------------------------
procedure(saveValues,newshims)

   lst = keaNMR:loadPref()
   assignlist(newshims)

   lst = setlistvalue(lst,"xshim","$xshim$")
   lst = setlistvalue(lst,"yshim","$yshim$") 
   lst = setlistvalue(lst,"zshim","$zshim$") 
   lst = setlistvalue(lst,"oshim","$oshim$") 

   keaNMR:savePref(lst)

endproc()
