#########################################################
# 
# EPI_2D
# 
# Slice selective spin-echo imaging
#
# Copyright (c) Magritek Ltd 2014
#
# U.I. V3
#########################################################

procedure(EPI_2D, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   n = :windowdefinition()

   windowvar(wv_dispMode,wv_ctrls,wv_shift,wv_other,wv_rel,
             wv_pp_list,wv_pp_name,wv_var,wv_tabs,wv_phase_list)

   wv_tabs  = ["Pulse Sequence","acquisition","processing+display","File settings"] # Tab names
   wv_ctrls = [2,44,45,68,69,82,83,103,104,113] # Control groups
   wv_shift = [-14,226,466,706,709] # Amount to shift control groups
   wv_other = [112,308,1011]  # Collapse control and window size
   wv_saved = "false"

   (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar()

   if(nrArgs == 0)
      guipar = "show"
   endif

   keaCtrl:setUp(n,"EPI_2D",getmacropath(),guipar)
   if(guipar == "hide")
      return(n)
   elseif(guipar == "show")
      try; :initGUI(n); catch; endtry;
      showwindow(n)
      return(n)
   else
      setwindowpar(n,"type","dialog")
      guipar = showdialog(n)
      return(guipar)
   endif

endproc()

#########################################################
# 
# Returns important pulse sequence parameters
#
# rel ......... relationship between pulse sequence parameters
# var ......... variable which change during the pulse sequence
# pp_list ..... list of pulse sequence parameters sent to DSP
# pp_name ..... name of DSP pulse program to run
# phase_list .. phase cycling information
#
#########################################################

procedure(getseqpar)

   rel = ["d600 = 2",
          "n600 = round(pulseLength90/d600)",
          "(t1,t2,gfac) = B1NutSoft:getRFPulse(SPType,a1,n600)",
          "(t3,t4,gfac) = B1NutSoft:getRFPulse(SPType,a2,n600)",
          "pulseLength180 = pulseLength90",
          "rampDur = 50",
          "d300 = 2.5",
          "d100 = 2",
          "d101 = 100",
          "d102 = 100",
          "n300 = round(rampDur/d300)",
          "d8 = estTimeR",
          "d7 = 3000",
          "sliceComp = 0",
          "(del11,del19) = EPI_2D:getRewindSliceDelay(pulseLength90,sliceComp,rampDur)",
          "d19=del19",
          "d11=del11",
          "d3 = 1000*acqTime/2+rxLat+d8-rampDur/2-acqShiftRead",
          "d9 = 2*d3 - d8 + rampDur",
          "d4 = echoTime/2-d3-2*rampDur-d7-2*rampDur-pulseLength90/2-3*rampDur-d11-d19-(pulseLength180+2*d102+2*rampDur)/2-pgo",
          "d10 = d9+timeReadCPMG",
          "d5 = echoTime/2-(pulseLength180+2*d102+2*rampDur)/2-(2*d100+2*rampDur+rampDur+d8+d9+rampDur-4*2.5)*round(nrStepsP/2)",
          "n10  = EPI_2D:convertDirToChannel(dirRead)",
          "n20  = EPI_2D:convertDirToChannel(dirPhase)",
          "n30  = EPI_2D:convertDirToChannel(dirSlice)",
          "(gReadAmp,gReadAmpShim,gPhaseAmp,gPhaseAmpShim,gSliceAmp,gSliceAmpShim,sliceOffSet) = EPI_2D:setImageGradients(dirRead,dirPhase,dirSlice,FoVRead,FoVPhase,rampDur*(nrStepsP/2),sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)",
          "n31 =  gSliceAmp+gSliceAmpShim",
          "n31a = gSliceAmpShim",
          "n32  = -gSliceAmp+gSliceAmpShim",
          "n1 = round(nrStepsP/2)",
          "n11 = gReadAmp+gReadAmpShim",
          "n11a = gReadAmpShim",
          "n12  = -gReadAmp+gReadAmpShim",
          "n21a = gPhaseAmpShim",
          "n21 = gPhaseAmp*(nrStepsP/2)*(rampDur)/(rampDur+d7)+gPhaseAmpShim",
          "n22 = gPhaseAmp+gPhaseAmpShim",
          "f1  =  b1Freq+O1/1e6+sliceOffSet",
          "f2  =  b1Freq+O1/1e6",
          "n2 = nrPnts",
          "totPnts = nrPnts*nrStepsP",
          "totTime = echoTime*nrStepsP"]
   var = [""]
   pp_list = ["f1","n30","n31a","n31","n300","d300","d101","t1","t2","p1","n600","d600","d19","f2","n32","d11","n10","n11a","n11","d3","n20","n21a","n21","d7","d4","d102","t3","t4","p2","d5","n1","l1","n22","d100","d8","n2","d9","n12","d10"]
   pp_name = "EPI_2D.p"
   phase_list = [0,2;1,1;0,2]

endproc(rel,var,pp_list,pp_name,phase_list)


#########################################################
# 
# Provide an interface to this macro which does not
# require the use of the window interface
#
# User must supply a list of parameter (see help file)
# and the pulse program name if different from 
# "$macro$_ext.p"
#
#########################################################

procedure(backdoor, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   (rel,var,pp_list,pp_name,phase_list) = :getseqpar()
  
   (guipar,ppList,pcList,pcIndex,varList) = keaCtrl:initialisePP(getmacropath(),getmacroname(),guipar,rel,var,pp_list,pp_name,phase_list)
   
   r = keaCtrl:runBDPP(guipar,ppList,pcList,pcIndex,varList)

endproc(r)

#########################################################
# 
# Define the window gui
#
#########################################################

procedure(windowdefinition)

   # Automatically generated window definition procedure.
   # Any code added manually will be removed if layout modified interactively
   n = window("EPI 2D", -1, -1, 578, 751)

      # Define all controls with basic parameters
      getmessage(0,
        keaCtrl:processMessage();)
      tab(1, 6, 7, 560, 296,
         which = getpar(0,1,"currenttab");
         if(which == 2);
         fn = findobj(0,"name","filter");
         keaCtrl:enableControls(fn+1,fn+3,fn);
         fn = findobj(0,"name","showFreqDomain");
         keaCtrl:enableControls(fn+1,fn+4,fn);
         endif();)
      groupbox(2, "Pulse sequence", 9, 9, 552, 233)
      statictext(3, 115, 31, "right", "B1 Frequency (MHz)")
      textbox(4, 121, 27, 46)
      statictext(5, 115, 56, "right", "Repetition time (ms)")
      textbox(6, 121, 52, 46)
      statictext(7, 115, 82, "right", "Offset (Hz)")
      textbox(8, 121, 78, 46)
      statictext(9, 115, 108, "right", "Soft pulse shape")
      textmenu(10, 121, 104, 60, 200)
      statictext(11, 115, 134, "right", "90 pulse length (us)")
      textbox(12, 121, 130, 40)
      statictext(13, 115, 160, "right", "rf amplitude (dB)")
      textbox(14, 121, 156, 40)
      statictext(15, 115, 186, "right", "180 amplitude (dB)")
      textbox(16, 121, 182, 40)
      statictext(17, 115, 212, "right", "sliceComp(us)")
      textbox(18, 121, 208, 40)
      statictext(19, 285, 30, "right", "Echotime (us)")
      textbox(20, 291, 26, 40)
      statictext(21, 285, 56, "right", "acquisition Shift(us)")
      textbox(22, 291, 52, 40)
      statictext(23, 285, 82, "right", "estabil. Time read (us)")
      textbox(24, 291, 78, 40)
      statictext(25, 285, 108, "right", "acqShiftRead (us)")
      textbox(26, 291, 104, 40)
      statictext(27, 285, 134, "right", "tim. CPMG Read (us)")
      textbox(28, 291, 130, 40)
      statictext(29, 455, 30, "right", "FoV Read (mm)")
      textbox(30, 461, 26, 40)
      statictext(31, 455, 56, "right", "FoV Phase (mm)")
      textbox(32, 461, 52, 40)
      statictext(33, 455, 82, "right", "nr. pixels phase")
      textbox(34, 461, 78, 40)
      statictext(35, 455, 108, "right", "Slice thickness (mm)")
      textbox(36, 461, 104, 40)
      statictext(37, 455, 134, "right", "Slice shift (mm)")
      textbox(38, 461, 130, 40)
      statictext(39, 506, 30, "right", "")
      textmenu(40, 512, 26, 40, 200)
      statictext(41, 506, 56, "right", "")
      textmenu(42, 512, 52, 40, 200)
      statictext(43, 506, 108, "right", "")
      textmenu(44, 512, 104, 40, 200)
      groupbox(45, "Acquisition", 9, 249, 552, 233)
      statictext(46, 79, 320, "center", "Rx Gain (dB)")
      textmenu(47, 62, 338, 39, 200)
      statictext(48, 79, 369, "center", "Rx Phase (degrees)")
      textbox(49, 62, 385, 39)
      statictext(50, 187, 322, "center", "Number of")
      statictext(51, 187, 335, "center", "complex points")
      textmenu(52, 234, 324, 62, 200,
         keaCtrl:updateAcqTime();)
      statictext(53, 187, 354, "center", "Dwell time")
      statictext(54, 187, 367, "center", "(us)")
      textmenu(55, 234, 357, 62, 200,
         keaCtrl:updateFilters();)
      statictext(56, 187, 388, "center", "Number of")
      statictext(57, 187, 401, "center", "scans")
      textbox(58, 234, 389, 62)
      statictext(59, 361, 336, "center", "Flat filter")
      checkbox(60, 397, 337, "no,yes", "no",
           keaCtrl:setDwellTimeMenu();
           keaCtrl:updateFilters();)
      statictext(61, 361, 360, "center", "Accumulate")
      checkbox(62, 397, 361, "no,yes", "no")
      statictext(63, 361, 384, "center", "Phase cycle")
      checkbox(64, 397, 386, "no,yes", "yes")
      statictext(65, 489, 320, "center", "Spectral width (kHz)")
      textbox(66, 460, 334, 56)
      statictext(67, 489, 371, "center", "Acquisition time (ms)")
      textbox(68, 460, 385, 56)
      groupbox(69, "Processing_Display", 9, 489, 552, 233)
      statictext(70, 208, 569, "right", "Filter time domain")
      checkbox(71, 216, 570, "no,yes", "no",
           fn = findobj(0,"name","filter");
           keaCtrl:enableControls(fn+1,fn+3,fn);)
      statictext(72, 90, 600, "right", "Filter")
      textmenu(73, 97, 596, 108, 200)
      button(74, 214, 596, 22, 22, "...",
         filters();)
      statictext(75, 208, 632, "right", "Time domain magnitude")
      checkbox(76, 216, 633, "no,yes", "no")
      statictext(77, 479, 567, "right", "Show frequency domain data")
      checkbox(78, 487, 568, "no,yes", "no",
           fn = findobj(0,"name","showFreqDomain");
           keaCtrl:enableControls(fn+1,fn+4,fn);)
      statictext(79, 479, 597, "right", "Frequency domain magnitude")
      checkbox(80, 487, 598, "no,yes", "no")
      statictext(81, 429, 630, "right", "Display range (kHz)")
      textbox(82, 439, 627, 61)
      groupbox(83, "File_Settings", 9, 729, 552, 233)
      statictext(84, 82, 819, "right", "Working")
      statictext(85, 82, 832, "right", "directory")
      textbox(86, 98, 820, 215)
      button(87, 318, 820, 22, 22, "...",
         keaFiles:setWorkingDir();)
      statictext(88, 89, 856, "right", "Experiment")
      statictext(89, 74, 869, "right", "name")
      textbox(90, 98, 859, 105)
      button(91, 209, 859, 22, 22, "...",
         keaFiles:setExpName();)
      statictext(92, 311, 856, "right", "Experiment")
      statictext(93, 301, 869, "right", "number")
      textbox(94, 319, 859, 25)
      button(95, 349, 859, 22, 22, "...",
         keaFiles:setExpNr();)
      statictext(96, 373, 818, "center", "Save")
      statictext(97, 373, 831, "center", "data")
      checkbox(98, 401, 825, "false,true", "true")
      statictext(99, 417, 856, "center", "Auto")
      statictext(100, 417, 869, "center", "increment")
      checkbox(101, 452, 864, "no,yes", "no")
      button(102, 438, 813, 40, 36, "Load Data",
         keaFiles:loadData();)
      button(103, 493, 813, 40, 50, "Open data folder",
         keaFiles:openDataFolder();)
      colorbox(104, 20, 975, 10, 10, [255,255,255,255])
      colorbox(105, 20, 988, 10, 10, [255,255,255,255])
      button(106, 40, 972, 54, 29, "Run",
         (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar();
         keaCtrl:runPP(getmacropath(),wv_pp_name);)
      button(107, 105, 972, 54, 29, "Abort",
         setwindowpar(0,"title","Wait for macro to abort ...");
         wvExpStatus = "stop";)
      button(108, 170, 972, 54, 29, "Finish",
         setwindowpar(0,"title","Wait for phase-cycling to complete ...");
         wvExpStatus = "finish";)
      button(109, 235, 972, 54, 29, "Load Par.",
         keaFiles:loadParameters();)
      button(110, 300, 972, 54, 29, "Help",
         help("Macros\Tomograph-Poland","EPI_2D.htm");)
      button(111, 365, 972, 54, 29, "Kea Pref.",
         keaCtrl:showPreferences();)
      button(112, 430, 972, 54, 29, "Collapse",
         keaCtrl:toggleWindowSize(1);)
      button(113, 495, 972, 54, 29, "Close",
         guipar = getctrlvalues(0);
         if(getwindowpar(0,"type") == "dialog");
         guipar = keaFiles:addWindowSpecifics(guipar);
         keaFiles:saveCommonPar(guipar);
         closedialog(guipar);
         else;
         keaFiles:saveParameters();
         closewindow(0);
         endif;)
      menu(114, "bkgMenu", "Edit macro\tCtrl+Dbl-Click", edit("$getmacroname()$"),
                "Show compiler\tCtrl+Shift+Dbl-Click", MakePulseProgram("$getmacropath()$","$rmext(getmacroname())$"))

     # Set other control parameters
      setpar(n,1,"active","true",
                  "inittabs",[""])
      setpar(n,4,"valueID","b1Freq",
                  "tag","freqRange",
                  "type","double",
                  "range",[1,400])
      setpar(n,6,"valueID","repTime",
                  "type","float",
                  "range",[1,1e+008])
      setpar(n,8,"valueID","O1",
                  "type","float")
      setpar(n,10,"valueID","SPType",
                  "menu",["sinc3","sinc5","gauss","rect"])
      setpar(n,12,"valueID","pulseLength90",
                  "type","float",
                  "range",[0.5,1000])
      setpar(n,14,"valueID","a1",
                  "type","float",
                  "range",[-85,0])
      setpar(n,16,"valueID","a2",
                  "type","float",
                  "range",[-85,0])
      setpar(n,18,"valueID","sliceComp",
                  "type","float",
                  "range",[-1000,1000])
      setpar(n,20,"valueID","echoTime",
                  "type","float",
                  "range",[2,327670])
      setpar(n,22,"valueID","acqShift",
                  "type","float",
                  "range",[2,327670])
      setpar(n,24,"valueID","estTimeR",
                  "type","float",
                  "range",[2,327670])
      setpar(n,26,"valueID","acqShiftRead",
                  "type","float",
                  "range",[-1000,1000])
      setpar(n,28,"valueID","timeReadCPMG",
                  "type","float",
                  "range",[-1000,1000])
      setpar(n,30,"valueID","FoVRead",
                  "type","float",
                  "range",[-10000,10000])
      setpar(n,32,"valueID","FoVPhase",
                  "type","float",
                  "range",[-10000,10000])
      setpar(n,34,"valueID","nrStepsP",
                  "type","integer",
                  "range",[1,500])
      setpar(n,36,"valueID","sliceTickness",
                  "type","float",
                  "range",[0,10000])
      setpar(n,38,"valueID","sliceShift",
                  "type","float",
                  "range",[-10000,10000])
      setpar(n,40,"valueID","dirRead",
                  "menu",["x","y","z"])
      setpar(n,42,"valueID","dirPhase",
                  "menu",["x","y","z"])
      setpar(n,44,"valueID","dirSlice",
                  "menu",["x","y","z"])
      setpar(n,47,"valueID","rxGain",
                  "type","integer",
                  "tooltip","20-40 dB gives optimal SNR.\rDecrease if overload occurs.",
                  "range",[-20,70],
                  "menu",["-20","-17","-14","-11","-8","-5","-2","1","4","7","10","13","16","19","22","25","28","31","34","37","40","43","46","49","52","55","58","61","64","67","70"])
      setpar(n,49,"valueID","rxPhase",
                  "type","float",
                  "tooltip","Applies a fixed phase shift to collected data.\rIgnored if autophasing.")
      setpar(n,52,"valueID","nrPnts",
                  "type","integer",
                  "range",[2,65536],
                  "menu",["2","4","8","16","32","64","128","256","512","1024","2048","4096","8192","16384","32768","65536"])
      setpar(n,55,"valueID","dwellTime",
                  "type","float",
                  "menu",[""])
      setpar(n,58,"valueID","nrScans",
                  "type","integer",
                  "range",[1,1e+006])
      setpar(n,60,"valueID","flatFilter",
                  "tooltip","On: all frequencies equally weighted.\rOff: center frequencies enhanced.")
      setpar(n,62,"valueID","accumulate")
      setpar(n,64,"valueID","usePhaseCycle")
      setpar(n,66,"valueID","bandwidth",
                  "tag","disable")
      setpar(n,68,"valueID","acqTime",
                  "tag","disable")
      setpar(n,71,"valueID","filter")
      setpar(n,73,"valueID","filterType",
                  "menu",[""])
      setpar(n,76,"valueID","timeMag")
      setpar(n,78,"valueID","showFreqDomain")
      setpar(n,80,"valueID","freqMag")
      setpar(n,82,"valueID","dispRange",
                  "type","float")
      setpar(n,86,"valueID","dataDirectory",
                  "type","string",
                  "tooltip","Where experimental data will be stored.")
      setpar(n,90,"valueID","expName",
                  "type","string",
                  "tooltip","A subdirectory of the data working directory to store different experiments.")
      setpar(n,94,"valueID","expNr",
                  "tooltip","A numbered subdirectory below the experiment name.\rNot made if entry is blank.")
      setpar(n,98,"valueID","saveData")
      setpar(n,101,"valueID","incExpNr",
                  "tooltip","Increment the experiment number after each experiment.")
      setpar(n,102,"tooltip","Load and display the data specified in the directories fields")
      setpar(n,103,"tooltip","View the data directory in Windows Explorer.")
      setpar(n,104,"objID","ppStatus",
                  "tooltip","Experiment Status Indicator\rGreen: running\rBlue: processing\rYellow: waiting")
      setpar(n,105,"objID","rxOverflow",
                  "tooltip","Receiver Overflow Indicator\rRed: overflow")
      setpar(n,106,"valueID","run",
                  "tooltip","Start the experiment.")
      setpar(n,107,"valueID","stop",
                  "tooltip","Stop the experiment without saving data.",
                  "active","true")
      setpar(n,108,"valueID","finish",
                  "tooltip","Finish the current phase cycle and save data.",
                  "active","true")
      setpar(n,109,"valueID","load",
                  "tooltip","Load a parameter set for a similar experiment.")
      setpar(n,110,"valueID","help",
                  "tooltip","Display HTML help for this experiment.",
                  "active","true")
      setpar(n,111,"valueID","showPref",
                  "tooltip","Display a preferences dialog for the Kea spectrometer.")
      setpar(n,112,"valueID","size",
                  "tooltip","Expand or collapse the window size to show all or fewer controls.",
                  "active","true")
      setpar(n,113,"valueID","close",
                  "tooltip","Close the window saving all parameters.")

     # Set other window parameters
      setwindowpar(n,"bkgmenu",114)

endproc(n)


#######################################################
# Execute the pulse program, collecting nrScans of 
# data and displaying the result in the 1D plot. 
#
# This procedure can be modified to perform more
# complex functions using the passed parameters:
#
# guipar ..... all parameters from the user interface
# ppList ..... the pulse program parameter list
# pcList ..... phase-cycle list
# pcIndex .... indices of phase parameters in ppList
# varIndex ... indices of variable parameters in ppList
#
#######################################################

procedure(execpp,guipar,ppList,pcList,pcIndex,varIndex)

# Make all gui parameters available
   assignlist(guipar)

   wvPP->multiplot(1,1)
   wvPP2->multiplot(2,2)

#Checks
   :checkDelays(guipar)
   acqTimeReal = keaNMR:getAcqTime(guipar)
   if ((d9<=acqTimeReal)|(d10<=acqTimeReal));  pr "d9/d10 too short"; abort(""); endif;
   :checkGradPowerEPI_2D(guipar)
 
   sumData = cmatrix(totPnts)

# Calculate suitable time and frequency axes
   totalTime = ([0:1:totPnts-1]/totPnts)*totTime*1000
   f = ([0:1:totPnts-1]-totPnts/2+1)/totTime


# Reset the timer
   time(0)

   kSpace2D = cmatrix(nrPnts,nrStepsP)
   kSpace2De = cmatrix(nrPnts,round(nrStepsP/2))
   kSpace2Do = cmatrix(nrPnts,round(nrStepsP/2))    

               
# Accumulate scan
      for(scan = 0 to nrScans-1)
     
       # Note the time at scan start
         t1 = time()   
   
       # Set phases for this scan
         (ppList,pAcq) = keaNMR:setPPPhase(ppList,scan,pcList,pcIndex)
   
       # Send phase parameters to DSP
         dspwrite("x",0x00,ppList)
   
       # Collect the data
         (status,data) = keaNMR:getData(totPnts,guipar)

         if(status != "ok")
            keaNMR:enableButtons()
            abort("")
         endif
   
   
       # Accumlate the data
         sumData = keaNMR:accumulate(accumulate,pAcq,sumData,data)

         if(accumulate=="yes")
            sf = 1/(scan+1)
         else
            sf = 1
         endif

         pd = wvPP->subplot(1,1)
         pd->draw("false")
         pd->plot(sf*real(sumData),"tracecolor",black)
         pd->hold("on")
         pd->plot(sf*imag(sumData),"tracecolor",red)
         pd->hold("off")
         pd->title("text","raw data ($scan+1$/$nrScans$)")
         pd->xlabel("text","points")
         pd->ylabel("text","amplitude")
         pd->draw("true")
   
 
      # Check timing
         check = keaRun:checkTimeAndAbort(guipar,t1,scan,pcList)
         if(check == "abort")
            return(0)
         elseif(check == "finish")
            scan = scan+1
            exitfor()
         endif

      next(scan)

resto = 2

# ALL
      for(nPh = 0 to nrStepsP-1)
        if (nPh%resto == 0) 
          for(k = 0 to nrPnts-1)
           kSpace2D[k,nPh] = sf*sumData[nPh*nrPnts + k]
          next k
        else 
          for(k = 0 to nrPnts-1)
           kSpace2D[k,nPh] = sf*sumData[nPh*nrPnts + (nrPnts-1)-k]
          next k
        endif
      next(nPh)

# even /odd
      for(nPh = 0 to nrStepsP-1)
        if (nPh%resto == 0) 
          for(k = 0 to nrPnts-1)
           kSpace2De[k,trunc(nPh/2)] = sf*sumData[nPh*nrPnts + k]
          next k
        else 
          for(k = 0 to nrPnts-1)
           kSpace2Do[k,trunc((nPh-1)/2)] = sf*sumData[nPh*nrPnts + (nrPnts-1)-k]
          next k
        endif
      next(nPh)

# -- ALL
      curplot("2d",1,1)
      image(kSpace2D)
      curplot("2d",2,1)
      image(mag(kSpace2D))

      npxRead  =2*:FFTsize(nrPnts)
      npxPhase =2*:FFTsize(nrStepsP)
      
      idata = fft_local:2d(kSpace2D,npxRead,npxPhase,"sinebell","sinebell","FTEcho","FTEcho","yes")

      fac = 8
      idataNew = matrix(npxRead/fac,npxPhase)
      nr1 = round(npxRead/2-0.5*npxRead/fac)
      nr2 = round(npxRead/2+0.5*npxRead/fac)
      idataNew = submatrix(idata,nr1,nr2-1,0,npxPhase-1)
      curplot("2d",3,1)
      image(idataNew)

      assign("kSpace2D",kSpace2D,"global")
#
## -- Odd
#      curplot("2d",1,2)
#      image(kSpace2Do)
#      curplot("2d",2,2)
#      image(mag(kSpace2Do))
#
#      npxRead  =2*:FFTsize(nrPnts)
#      npxPhase =2*:FFTsize(nrStepsP)
#      
#      idata = fft_local:2d(kSpace2Do,npxRead,npxPhase,"sinebell","sinebell","FTEcho","FTEcho","yes")
#
#      fac = 8
#      idataNew = matrix(npxRead/fac,npxPhase)
#      nr1 = round(npxRead/2-0.5*npxRead/fac)
#      nr2 = round(npxRead/2+0.5*npxRead/fac)
#
#      idataNew = submatrix(idata,nr1,nr2-1,0,npxPhase-1)
#      curplot("2d",3,2)
#      image(idataNew)
#
#      assign("kSpace2Do",kSpace2Do,"global")
#
## -- even
#      curplot("2d",1,3)
#      image(kSpace2De)
#      curplot("2d",2,3)
#      image(mag(kSpace2De))
#
#      npxRead  =2*:FFTsize(nrPnts)
#      npxPhase =2*:FFTsize(nrStepsP)
#      
#      idata = fft_local:2d(kSpace2De,npxRead,npxPhase,"sinebell","sinebell","FTEcho","FTEcho","yes")
#
#      fac = 8
#      idataNew = matrix(npxRead/fac,npxPhase)
#      nr1 = round(npxRead/2-0.5*npxRead/fac)
#      nr2 = round(npxRead/2+0.5*npxRead/fac)
#
#      idataNew = submatrix(idata,nr1,nr2-1,0,npxPhase-1)
#      curplot("2d",3,3)
#      image(idataNew)
#
#      assign("kSpace2Do",kSpace2De,"global")
#


   if(saveData == "true")
      :saveData(guipar,kSpace2D,idata)
      keaFiles:incrementExperiment(guipar)
   endif


endproc("execpp")

#######################################################
# Save the accumulated data
# Either pass the parameters to save or use
# window variables of the same name.
#######################################################

procedure(saveData,guipar,kSpace2D,idata)

# Make all gui parameters available
   assignlist(guipar)

# Save data and plot in chosen folder
   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   mkdir("$expNr$")
   cd("$expNr$")

   export2dpar("ab","binary","xyrc","real","machine","littleend")
   export2d(idata,"rawimage2d.2d")  # Save data as an Excel file

   export2dpar("ab","binary","xyrc","complex","machine","littleend")
   export2d(kSpace2D,"rawkSpace2d.2d")  # Save data as an Excel file

   (n1,n2) = size(idata)

   save("$n1$x$n2$.pixels_image","empty")

   (n1,n2) = size(kSpace2D)

   save("$n1$x$n2$.kspace_size","empty")

   temp = getcwd()

   pr "data saved to $temp$"

endproc("saveData")

#-----------------------------
procedure(getRewindSliceDelay,PulseLength90,sliceComp,rampDur)   
   d19=2
   d11=PulseLength90/2+sliceComp+d19-0.5*rampDur
   if(d11<=0.25)
      d11=2
      d19=d11+0.5*rampDur-PulseLength90/2-sliceComp
   endif
endproc(d11,d19)

#-----------------------------
procedure(setImageGradients,dirRead,dirPhase,dirSlice,FoVRead,FoVPhase,phDur,sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)


   guipar = getctrlvalues(0)
   lst = keaNMR:loadPref()
   guipar = guipar + lst
   assignlist(guipar)

   FoVRead = FoVRead/1000             # change from mm to m
   FoVPhase = FoVPhase/1000           # change from mm to m
   sliceTickness = sliceTickness/1000 # change from mm to m
   sliceShift = sliceShift/1000       # change from mm to m


   bandwidthRead =  bandwidth*1e3
   if(FoVRead==0)
      gReadAmpTperM=0
   else
      gReadAmpTperM =  bandwidthRead/42.57e6/FoVRead
   endif

   xshim = xshim/1000
   yshim = yshim/1000 
   zshim = zshim/1000  

   if(dirRead == "x"); ampRead = gReadAmpTperM*xcal; ampReadShim = xshim*xcal;  endif
   if(dirRead == "y"); ampRead = gReadAmpTperM*ycal; ampReadShim = yshim*ycal; endif 
   if(dirRead == "z"); ampRead = gReadAmpTperM*zcal; ampReadShim = zshim*zcal; endif 

   bandwidthPhase =  1e6*0.5*nrStepsP/(phDur)
   
   if(FoVPhase==0)
      gPhaseAmpTperM=0
   else
      gPhaseAmpTperM =  bandwidthPhase/42.57e6/FoVPhase
   endif
  
   if(dirPhase == "x"); ampPhase = gPhaseAmpTperM*xcal; ampPhaseShim = xshim*xcal;  endif
   if(dirPhase == "y"); ampPhase = gPhaseAmpTperM*ycal; ampPhaseShim = yshim*ycal;  endif 
   if(dirPhase == "z"); ampPhase = gPhaseAmpTperM*zcal; ampPhaseShim = zshim*zcal;  endif

   bandwidthSlice =  gfac*1e6/(pulseLength90)

   if(sliceTickness == 0)
      gSliceTperM =0
   else
      gSliceTperM    =  bandwidthSlice/42.57e6/sliceTickness
   endif

   if(dirSlice == "x"); ampSlice = gSliceTperM*xcal; ampSliceShim = xshim*xcal; endif
   if(dirSlice == "y"); ampSlice = gSliceTperM*ycal; ampSliceShim = yshim*ycal; endif 
   if(dirSlice == "z"); ampSlice = gSliceTperM*zcal; ampSliceShim = zshim*zcal; endif

   sliceOffSet = gSliceTperM*42.57*sliceShift # in MHz

   if(abs(ampRead)>20800);   ampRead = 0; pr "Read gradient too high"; endif
   if(abs(ampPhase)>20800); ampPhase = 0; pr "Phase gradient too high"; endif
   if(abs(ampSlice)>20800); ampSlice = 0; pr "Slice gradient too high"; endif


endproc(round(ampRead),round(ampReadShim),round(ampPhase),round(ampPhaseShim),round(ampSlice),round(ampSliceShim),sliceOffSet)

procedure(convertDirToChannel,dir)

   if(dir == "x")
        return 3
   endif
   if(dir == "y")
        return 2
   endif
   if(dir == "z")
        return 1
   endif

   if(dir == 3)
        return 3
   endif
   if(dir == 2)
        return 2
   endif
   if(dir == 1)
        return 1
   endif
  
endproc(0)

#-----------------------------
procedure(checkGradPowerEPI_2D,guipar)

   assignlist(guipar)
   refPower=700

   #READ Channel
   p_R=gReadAmp*gReadAmp*(d3+rampDur)*1e-6 + gReadAmp*gReadAmp*(d8+d9+rampDur)*round(nrStepsP/2)*1e-6 + gReadAmp*gReadAmp*(d8+d10+rampDur)*round(nrStepsP/2)*1e-6
   
   #PHASE Channel
   gPhaseAmpTemp=gPhaseAmp*round(nrStepsP/2)*(rampDur)/(rampDur+d7)
   p_P=gPhaseAmpTemp*gPhaseAmpTemp*(d7+rampDur)*1e-6 + gPhaseAmp*gPhaseAmp*rampDur*nrStepsP*1e-6

   #SLICE Channel
   p_S=gSliceAmp*gSliceAmp*((pulseLength90+d101+d19+d11+2*rampDur)+(pulseLength180+2*d102+rampDur))*1e-6
   
   p_mean=(p_R+p_P+p_S)/repTime  

   if (p_mean>refPower)
      if(p_S>p_R+p_P)
         pr "Power requirement too high. Increase repetition time or slice thickness. \n"
         message("Waring","Power requirement too high.\r Increase repetition time tR > $round(p_mean/refPower*repTime)+1$ ms \r or slice thickness.","warning")
         abort("")          
      endif
      pr "Power requirement too high. Increase repetition time. \n"
      message("Waring","Power requirement too high.\r Increase repetition time tR > $round(p_mean/refPower*repTime)+1$ ms","warning")
      abort("")
   endif

endproc()

#-----------------------------
procedure(checkDelays,guipar)
   assignlist(guipar)
   for (k=1 to 1000)
      try
         d_temp=eval("d$k$")
         if(d_temp<=0); pr "\n d$k$<0 \n"; abort(""); endif;  
      catch
      endtry         
   next
endproc()

#-----------------------------
procedure(FFTsize,nrPnts)

  m=1
  a = nrPnts
  while(a>1)
     a = nrPnts/2^m
     m = m+1
  endwhile
  r = 2^(m-1)

endproc(r)

