#########################################################
# 
# T1T2
#                T1T2_pp.mac
#
# T1-T2 correlation experiment 
# 180 - delay - 90 - delay - {180 - delay - acqu - {180 - delay} }
#
# This pulse sequence will implement an inversion
# recovery experiment to encode for T1 followed by 
# a CPMG echo train to measure T2. The CPMG train
# includes dummy pulses to allow for long acquisition
# times while still using small echo times.
#
# a1 ... amplitude of 180 pulse
# a2 ... amplitude of 90 pulse
# p1 ... phase of first 180 pulse
# p2 ... phase of 90 pulse
# p3 ... phase of CPMG 180 pulses
# d1 ... width of pulses
# d2 ... delay between 90 and CPMG 180
# d3 ... delay between CPMG 180 and acquisition
# d4 ... delay between acquisition start and next CPMG 180 
# d5 ... delay between CPMG 180 dummy pulses
# n1 ... number of echos to collect
# n2 ... number of data points to collect per echo
# n3 ... number of 180 dummy pulses per echo
#
# Copyright (c) Magritek Ltd 2014
#
# U.I. V3
#########################################################

procedure(T1T2, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   n = :windowdefinition()

   windowvar(wv_dispMode,wv_ctrls,wv_shift,wv_other,wv_rel,
             wv_pp_list,wv_pp_name,wv_var,wv_tabs,wv_phase_list)

   wv_tabs  = ["Pulse Sequence","Progress","acquisition","Inverse Laplace","File settings"] # Tab names
   wv_ctrls = [2,32,33,42,43,66,67,89,90,110,111,120] # Control groups
   wv_shift = [-14,133,280,427,574,577] # Amount to shift control groups
   wv_other = [119,215,786]  # Collapse control and window size
   wv_saved = "false"

   (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar()

   if(nrArgs == 0)
      guipar = "show"
   endif

   keaCtrl:setUp(n,"T1T2",getmacropath(),guipar)
   if(guipar == "hide")
      return(n)
   elseif(guipar == "show")
      try; :initGUI(n); catch; endtry;
      showwindow(n)
      return(n)
   else
      setwindowpar(n,"type","dialog")
      guipar = showdialog(n)
      return(guipar)
   endif

endproc()

#########################################################
# 
# Returns important pulse sequence parameters
#
# rel ......... relationship between pulse sequence parameters
# var ......... variable which change during the pulse sequence
# pp_list ..... list of pulse sequence parameters sent to DSP
# pp_name ..... name of DSP pulse program to run
# phase_list .. phase cycling information
#
#########################################################

procedure(getseqpar)

   rel = ["a1 = 90Amplitude",
          "a2 = 180Amplitude",
          "d1 = pulseLength",
          "w1 = minTau*1000-d1-pgo",
          "d2 = echoTime/2-d1-pgo",
          "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
          "d4 = echoTime-d1-pgo-d3",
          "d5 = echoTime-d1-pgo",
          "n1 = nrEchoes",
          "n2 = nrPnts",
          "n3 = dummyEchoes",
          "totPnts = nrEchoes",
          "totTime = nrEchoes*echoTime*(dummyEchoes+1)"]
   var = ["w1"]
   pp_list = ["n1","a2","p1","d1","w1","a1","p2","d2","l1","p3","d3","n2","d4","n3","l2","d5"]
   pp_name = "T1T2.p"
   phase_list = [0,2,0,2;0,0,2,2;1,1,1,1;0,0,2,2]

endproc(rel,var,pp_list,pp_name,phase_list)


#########################################################
# 
# Provide an interface to this macro which does not
# require the use of the window interface
#
# User must supply a list of parameter (see help file)
# and the pulse program name if different from 
# "$macro$_ext.p"
#
#########################################################

procedure(backdoor, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   (rel,var,pp_list,pp_name,phase_list) = :getseqpar()
  
   (guipar,ppList,pcList,pcIndex,varList) = keaCtrl:initialisePP(getmacropath(),getmacroname(),guipar,rel,var,pp_list,pp_name,phase_list)
   
   r = keaCtrl:runBDPP(guipar,ppList,pcList,pcIndex,varList)

endproc(r)

#########################################################
# 
# Define the window gui
#
#########################################################

procedure(windowdefinition)

   # Automatically generated window definition procedure.
   # Any code added manually will be removed if layout modified interactively
   n = window("T1 - T2 Correlation", -1, -1, 577, 783)

      # Define all controls with basic parameters
      getmessage(0,
        keaCtrl:processMessage();)
      tab(1, 6, 7, 559, 203,
         which = getpar(0,1,"currenttab");)
      groupbox(2, "Pulse sequence", 9, 9, 551, 140)
      statictext(3, 115, 36, "right", "B1 Frequency (MHz)")
      textbox(4, 121, 32, 46)
      statictext(5, 115, 62, "right", "Inter-expt. delay (ms)")
      textbox(6, 121, 57, 46)
      statictext(7, 115, 87, "right", "Log. spacing")
      checkbox(8, 121, 87, "lin,log", "lin")
      statictext(9, 115, 113, "right", "Auto phase")
      checkbox(10, 121, 113, "no,yes", "no")
      statictext(11, 245, 35, "right", "90 amp. (dB)")
      textbox(12, 251, 31, 40)
      statictext(13, 245, 61, "right", "180 amp. (dB)")
      textbox(14, 251, 57, 40)
      statictext(15, 245, 87, "right", "Pulse length (us)")
      textbox(16, 251, 83, 40)
      statictext(17, 258, 113, "right", "Minimize imag. range")
      checkbox(18, 264, 113, "minImag,maxReal", "minImag")
      statictext(19, 375, 35, "right", "Min. tau (ms)")
      textbox(20, 381, 31, 40)
      statictext(21, 375, 61, "right", "Max. tau (ms)")
      textbox(22, 381, 57, 40)
      statictext(23, 375, 87, "right", "Tau steps")
      textbox(24, 381, 83, 40)
      statictext(25, 375, 113, "right", "Echo shift (us)")
      textbox(26, 381, 109, 40)
      statictext(27, 505, 35, "right", "Echo-time (us)")
      textbox(28, 511, 31, 40)
      statictext(29, 505, 61, "right", "No. of echoes")
      textbox(30, 511, 57, 40)
      statictext(31, 505, 87, "right", "Dummy echoes")
      textbox(32, 511, 83, 40)
      groupbox(33, "Progress", 9, 156, 551, 140)
      statictext(34, 168, 210, "right", "Current scan:")
      statictext(35, 173, 210, "left", "0")
      statictext(36, 169, 231, "right", "Current SNR:")
      statictext(37, 174, 231, "left", "0")
      statictext(38, 424, 210, "right", "Estimated remaining expt. time (mm:ss):")
      statictext(39, 436, 210, "left", "00:00")
      statictext(40, 284, 231, "right", "Progress:")
      progressbar(41, 294, 230, 131, 16, "horizontal")
      statictext(42, 436, 231, "left", "00:00")
      groupbox(43, "Acquisition", 9, 303, 551, 140)
      statictext(44, 78, 328, "center", "Rx Gain (dB)")
      textmenu(45, 61, 346, 39, 200)
      statictext(46, 78, 377, "center", "Rx Phase (degrees)")
      textbox(47, 61, 393, 39)
      statictext(48, 186, 330, "center", "Number of")
      statictext(49, 186, 343, "center", "complex points")
      textmenu(50, 233, 332, 62, 200,
         keaCtrl:updateAcqTime();)
      statictext(51, 186, 362, "center", "Dwell time")
      statictext(52, 186, 375, "center", "(us)")
      textmenu(53, 233, 365, 62, 200,
         keaCtrl:updateFilters();)
      statictext(54, 186, 396, "center", "Number of")
      statictext(55, 186, 409, "center", "scans")
      textbox(56, 233, 397, 62)
      statictext(57, 360, 344, "center", "Flat filter")
      checkbox(58, 396, 345, "no,yes", "no",
           keaCtrl:setDwellTimeMenu();
           keaCtrl:updateFilters();)
      statictext(59, 360, 368, "center", "Accumulate")
      checkbox(60, 396, 369, "no,yes", "no")
      statictext(61, 360, 392, "center", "Phase cycle")
      checkbox(62, 396, 394, "no,yes", "yes")
      statictext(63, 488, 328, "center", "Spectral width (kHz)")
      textbox(64, 459, 342, 56)
      statictext(65, 488, 379, "center", "Acquisition time (ms)")
      textbox(66, 459, 393, 56)
      groupbox(67, "Inversion_T1T2", 9, 450, 551, 140)
      statictext(68, 74, 484, 45, 28, "center", "Inversion method")
      textmenu(69, 108, 487, 85, 200)
      statictext(70, 74, 513, 51, 27, "center", "Smoothing factor")
      textbox(71, 108, 517, 57)
      statictext(72, 74, 544, 54, 26, "center", "Number of iterations")
      textbox(73, 108, 547, 57)
      statictext(74, 282, 471, "center", "T2 (s)")
      statictext(75, 340, 471, "center", "T1 (s)")
      statictext(76, 250, 493, "right", "Minimum")
      textbox(77, 260, 487, 43)
      textbox(78, 318, 487, 43)
      statictext(79, 250, 520, "right", "Maximum")
      textbox(80, 260, 517, 43)
      textbox(81, 318, 517, 43)
      statictext(82, 250, 550, "right", "Steps")
      textbox(83, 260, 547, 43)
      textbox(84, 318, 547, 43)
      button(85, 379, 485, 63, 25, "Reset",
         :resetPar();)
      button(86, 379, 515, 63, 25, "Calculate",
         :invert2DData();)
      statictext(87, 521, 467, "right", "Convergence")
      progressbar(88, 482, 491, 16, 86, "vertical")
      button(89, 379, 545, 63, 25, "Load result",
         :loadResult();)
      groupbox(90, "File_Settings", 9, 597, 551, 140)
      statictext(91, 81, 640, "right", "Working")
      statictext(92, 81, 653, "right", "directory")
      textbox(93, 97, 641, 215)
      button(94, 317, 641, 22, 22, "...",
         keaFiles:setWorkingDir();)
      statictext(95, 88, 677, "right", "Experiment")
      statictext(96, 73, 690, "right", "name")
      textbox(97, 97, 680, 105)
      button(98, 208, 680, 22, 22, "...",
         keaFiles:setExpName();)
      statictext(99, 310, 677, "right", "Experiment")
      statictext(100, 300, 690, "right", "number")
      textbox(101, 318, 680, 25)
      button(102, 348, 680, 22, 22, "...",
         keaFiles:setExpNr();)
      statictext(103, 372, 639, "center", "Save")
      statictext(104, 372, 652, "center", "data")
      checkbox(105, 400, 646, "false,true", "true")
      statictext(106, 416, 677, "center", "Auto")
      statictext(107, 416, 690, "center", "increment")
      checkbox(108, 451, 685, "no,yes", "no")
      button(109, 437, 634, 40, 36, "Load Data",
         keaFiles:loadData();)
      button(110, 492, 634, 40, 50, "Open data folder",
         keaFiles:openDataFolder();)
      colorbox(111, 20, 750, 10, 10, [255,255,255,255])
      colorbox(112, 20, 763, 10, 10, [255,255,255,255])
      button(113, 40, 747, 54, 29, "Run",
         (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar();
         keaCtrl:runPP(getmacropath(),wv_pp_name);)
      button(114, 105, 747, 54, 29, "Abort",
         setwindowpar(0,"title","Wait for macro to abort ...");
         wvExpStatus = "stop";)
      button(115, 170, 747, 54, 29, "Finish",
         setwindowpar(0,"title","Wait for phase-cycling to complete ...");
         wvExpStatus = "finish";)
      button(116, 235, 747, 54, 29, "Load Par.",
         keaFiles:loadParameters();)
      button(117, 300, 747, 54, 29, "Help",
         help("Macros\Tomograph","T1T2.htm");)
      button(118, 365, 747, 54, 29, "Kea Pref.",
         keaCtrl:showPreferences();)
      button(119, 430, 747, 54, 29, "Collapse",
         keaCtrl:toggleWindowSize(1);)
      button(120, 495, 747, 54, 29, "Close",
         guipar = getctrlvalues(0);
         if(getwindowpar(0,"type") == "dialog");
         guipar = keaFiles:addWindowSpecifics(guipar);
         keaFiles:saveCommonPar(guipar);
         closedialog(guipar);
         else;
         keaFiles:saveParameters();
         closewindow(0);
         endif;)
      menu(121, "bkgMenu", "Edit macro\tCtrl+Dbl-Click", edit("$getmacroname()$"),
                "Show compiler\tCtrl+Shift+Dbl-Click", MakePulseProgram("$getmacropath()$","$rmext(getmacroname())$"))

     # Set other control parameters
      setpar(n,1,"active","true",
                  "inittabs",[""])
      setpar(n,4,"valueID","b1Freq",
                  "tag","freqRange",
                  "type","double",
                  "range",[1,400])
      setpar(n,6,"valueID","ieTime",
                  "type","float",
                  "range",[1,1e+008])
      setpar(n,8,"valueID","delaySpacing")
      setpar(n,10,"valueID","autoPhase")
      setpar(n,12,"valueID","90Amplitude",
                  "type","float",
                  "range",[-85,0])
      setpar(n,14,"valueID","180Amplitude",
                  "type","float",
                  "range",[-85,0])
      setpar(n,16,"valueID","pulseLength",
                  "type","float",
                  "range",[0.5,1000])
      setpar(n,18,"valueID","phaseMethod")
      setpar(n,20,"valueID","minTau",
                  "type","float",
                  "range",[0.002,167000])
      setpar(n,22,"valueID","maxTau",
                  "type","float",
                  "range",[0.002,167000])
      setpar(n,24,"valueID","tauSteps",
                  "type","integer",
                  "range",[1,1000])
      setpar(n,26,"valueID","echoShift",
                  "type","float",
                  "range",[-20,20])
      setpar(n,28,"valueID","echoTime",
                  "type","float",
                  "range",[2,327670])
      setpar(n,30,"valueID","nrEchoes",
                  "type","integer",
                  "range",[1,64000])
      setpar(n,32,"valueID","dummyEchoes",
                  "type","integer",
                  "range",[0,1000])
      setpar(n,35,"objID","curScanCtrl")
      setpar(n,37,"objID","curSNRCtrl")
      setpar(n,39,"objID","remTimeCtrl")
      setpar(n,41,"objID","progressCtrl")
      setpar(n,42,"objID","expTimeCtrl")
      setpar(n,45,"valueID","rxGain",
                  "type","integer",
                  "tooltip","20-40 dB gives optimal SNR.\rDecrease if overload occurs.",
                  "range",[-20,70],
                  "menu",["-20","-17","-14","-11","-8","-5","-2","1","4","7","10","13","16","19","22","25","28","31","34","37","40","43","46","49","52","55","58","61","64","67","70"])
      setpar(n,47,"valueID","rxPhase",
                  "type","float",
                  "tooltip","Applies a fixed phase shift to collected data.\rIgnored if autophasing.")
      setpar(n,50,"valueID","nrPnts",
                  "type","integer",
                  "range",[2,65536],
                  "menu",["2","4","8","16","32","64","128","256","512","1024","2048","4096","8192","16384","32768","65536"])
      setpar(n,53,"valueID","dwellTime",
                  "type","float",
                  "menu",[""])
      setpar(n,56,"valueID","nrScans",
                  "type","integer",
                  "range",[1,1e+006])
      setpar(n,58,"valueID","flatFilter",
                  "tooltip","On: all frequencies equally weighted.\rOff: center frequencies enhanced.")
      setpar(n,60,"valueID","accumulate")
      setpar(n,62,"valueID","usePhaseCycle")
      setpar(n,64,"valueID","bandwidth",
                  "tag","disable")
      setpar(n,66,"valueID","acqTime",
                  "tag","disable")
      setpar(n,69,"valueID","inversionMethod",
                  "menu",["FISTA","Max Entropy"])
      setpar(n,71,"valueID","smoothFactor")
      setpar(n,73,"valueID","nrIterations")
      setpar(n,77,"valueID","x_minimum")
      setpar(n,78,"valueID","y_minimum")
      setpar(n,80,"valueID","x_maximum")
      setpar(n,81,"valueID","y_maximum")
      setpar(n,83,"valueID","x_steps",
                  "type","float",
                  "range",[5,90])
      setpar(n,84,"valueID","y_steps",
                  "type","float",
                  "range",[5,90])
      setpar(n,85,"tooltip","Use the pulse program to set the inversion parameters.")
      setpar(n,86,"tooltip","Perform the inversion.")
      setpar(n,88,"objID","convergObj",
                  "type","float",
                  "range",[0,100])
      setpar(n,89,"tooltip","Load and display the last inversion result.")
      setpar(n,93,"valueID","dataDirectory",
                  "type","string",
                  "tooltip","Where experimental data will be stored.")
      setpar(n,97,"valueID","expName",
                  "type","string",
                  "tooltip","A subdirectory of the data working directory to store different experiments.")
      setpar(n,101,"valueID","expNr",
                  "tooltip","A numbered subdirectory below the experiment name.\rNot made if entry is blank.")
      setpar(n,105,"valueID","saveData")
      setpar(n,108,"valueID","incExpNr",
                  "tooltip","Increment the experiment number after each experiment.")
      setpar(n,109,"tooltip","Load and display the data specified in the directories fields")
      setpar(n,110,"tooltip","View the data directory in Windows Explorer.")
      setpar(n,111,"objID","ppStatus",
                  "tooltip","Experiment Status Indicator\rGreen: running\rBlue: processing\rYellow: waiting")
      setpar(n,112,"objID","rxOverflow",
                  "tooltip","Receiver Overflow Indicator\rRed: overflow")
      setpar(n,113,"valueID","run",
                  "tooltip","Start the experiment.")
      setpar(n,114,"valueID","stop",
                  "tooltip","Stop the experiment without saving data.",
                  "active","true")
      setpar(n,115,"valueID","finish",
                  "tooltip","Finish the current phase cycle and save data.",
                  "active","true")
      setpar(n,116,"valueID","load",
                  "tooltip","Load a parameter set for a similar experiment.")
      setpar(n,117,"valueID","help",
                  "tooltip","Display HTML help for this experiment.",
                  "active","true")
      setpar(n,118,"valueID","showPref",
                  "tooltip","Display a preferences dialog for the Kea spectrometer.")
      setpar(n,119,"valueID","size",
                  "tooltip","Expand or collapse the window size to show all or fewer controls.",
                  "active","true")
      setpar(n,120,"valueID","close",
                  "tooltip","Close the window saving all parameters.")

     # Set other window parameters
      setwindowpar(n,"bkgmenu",121)

endproc(n)

#######################################################
# Execute the pulse program, collecting nrScans of 
# data and displaying the result in the 1D plot. 
#
# This procedure can be modified to perform more
# complex functions using the passed parameters:
#
# guipar ..... all parameters from the user interface
# ppList ..... the pulse program parameter list
# pcList ..... phase-cycle list
# pcIndex .... indices of phase parameters in ppList
# varIndex ... indices of variable parameters in ppList
#
#######################################################

procedure(execpp,guipar,ppList,pcList,pcIndex,varIndex)

# Make all gui parameters available
   assignlist(guipar)
   guipar = guipar + "timeMag = \"no\""

# Do some safety checks
   if(w1 <= 0 | d2 <= 0)
     message("Error","Pulse sequence timing error!\rIncrease minimum delay.","error")
     wvExpStatus = "stop"
     return(0,0)
   endif

 
   if(d4-keaRun:getAcqTime(guipar) < -1e-5)
      message("Error","Pulse sequence timing error!\rReduce number of points to $maxN$.","error")
      wvExpStatus = "stop"
      return(0,0)
   endif

 # Check RF duty cycle
   if(keaRun:highDutyCycle(d1*nrEchoes,nrEchoes*echoTime+minTau*1000,guipar))
      wvExpStatus = "stop"
      return(0,0)
   endif

# Check minimum delay
   if(delaySpacing == "log")
      md = (d1+pgo+dampingTime+10)/1000
      if(minTau*1000-d1-pgo-dampingTime < 0)
        message("Error","Minimum T1 delay is too short.\rMust be at least $md,2.2f$ ms","error")
        wvExpStatus = "stop"
        return(0,0)
      endif
   endif

# Calculate suitable time axes
   totalTime = ([0:1:totPnts-1]/totPnts)*totTime + echoTime

# Storage for each tau value
   data2d = cmatrix(totPnts,tauSteps)
   endData = cmatrix(totPnts)

# Make 1 subplot for both 1D and 2D
  
      prt = wvPP->multiplot(1,1)
      ir1 = wvPP2->multiplot(1,1)
   

# Make the delay array
   if(delaySpacing == "log")
      dArray = keaRun:logAxis(minTau,maxTau,tauSteps)*1000
   else
      dArray = linvec(minTau,maxTau,tauSteps)*1000
   endif

# Estimate total experiment time in ms
   expTime = (dArray[0]+sum(dArray)+dArray[tauSteps-1]*3)/(1000*(tauSteps+2)) # Avg tau time
   heaterDelay = 40 # Time required to turn off heater (ms)
   expTime = expTime+(ieTime+echoTime*nrEchoes/1000+heaterDelay) # Avg time With CPMG
   totEstExpTime = (tauSteps+2)*nrScans*expTime # Allow for dummy scans and long time scans
   procTime = 0.01 # Processing time est. in sec

# Reset the timer
   time(0)  

   ph = 0
   maxSNR = 0

# Loop over the delay array
   for(d = -2 to tauSteps-1)

   # Set inversion recovery delay
      if(d == -2)
         dly = dArray[tauSteps-1]*3 # Reference delay
      elseif(d == -1)
         dly = dArray[0]
      else
         dly = dArray[d]
      endif

      ppList = keaRun:setPPLongDelay(ppList,varIndex[0],dly - d1 - 1)

   # Storage for accumulated data
      sumData = cmatrix(totPnts)

   # Accumulate scan
      for(scan = 0 to nrScans-1)
   
       # Note the time at scan start
         t1 = time()   
   
       # Set phases for this scan
         (ppList,pAcq) = keaRun:setPPPhase(ppList,scan,pcList,pcIndex)
   
       # Send phase parameters to DSP
         dspwrite("x",0x00,ppList,wvPort)
   
       # Collect the data
         (status,data) = keaRun:getData(totPnts,guipar)
         if(status != "ok")
            return(0)
         endif

       # Accumlate the data
         sumData = keaRun:accumulate(accumulate,pAcq,sumData,data)
   
         if(autoPhase == "yes" & d == -2)
            ph =  keaRun:autoPhase(sumData,phaseMethod)
         endif

         sumDataAP = sumData*exp(i*ph/180*pi)

       # Graph the data
         if(d == -2)
            timeTxt = "CPMG echo amplitude: reference delay = $dly/1000,2.2f$ ms SCANS"
         elseif(d == -1)
            timeTxt = "CPMG echo amplitude: dummy scan: delay = $dly/1000,2.2f$ ms SCANS"
         else
            timeTxt = "CPMG echo amplitude: \G(t) = $dly/1000,2.2f$ ms SCANS"
         endif

         keaPlot:graphTime(prt,totalTime/1000,sumDataAP/nrPnts,scan,guipar,timeTxt,"Echo time (ms)","Average echo amplitude (\G(m)V)")

        if(isvar("curScanCtrl")) # From RCA interface
   
          # Display scan number
            curScanCtrl->text(scan+1)
   
          # Calculate and display the SNR
            if((scan+1)%4 == 0)
               ns = imag(sumDataAP)/(scan+1)
               ns = ns[round(size(ns)/2):-1]
               sd = keaRun:rmsValue(ns) # Noise is RMS of last half of data set
               sig = real(sumDataAP)/(scan+1)
               if(sd != 0)
                  SNR = abs(sig[0]/sd)
               else
                  SNR = 0
               endif
               curSNRCtrl->text("$SNR,1.1f$")
               if(SNR > maxSNR)
                 maxSNR = SNR
               endif
            endif

          # Estimate remaining time
            et = time()
            tm1 = trunc(et/60)
            ts = round(frac(et/60)*60)
            expTimeCtrl->text("$tm1,02.0f$:$ts,02.0f$")
            extraTime = procTime*nrScans*(tauSteps+2)*1000
            extraTime = 0
   
            remainingTime = (totEstExpTime+extraTime-et*1000)/1000
            if(remainingTime < 0)
               remainingTime = 0
            endif
   
            progressCtrl->value(round(et*1000/totEstExpTime*100))       
            tm1 = trunc(remainingTime/60)
            ts = round(frac(remainingTime/60)*60)
            remTimeCtrl->text("$tm1,02.0f$:$ts,02.0f$")
   
          # Elapsed time
            et = time()
            tm = trunc(et/60)
            ts = round(frac(et/60)*60)
            expTimeCtrl->text("$tm,02.0f$:$ts,02.0f$")
         endif

      # Check timing
         check = keaRun:checkTimeAndAbort(guipar,t1,scan,pcList)
         if(check == "abort")
            return(0)
         elseif(check == "finish")
            scan = scan+1
            exitfor()
         endif
   
      next(scan)

      if(d == -2)
         endData = sumDataAP
      elseif(d >= 0)
         data2d[~,d] = endData - sumDataAP       
      endif

   # Display the 2D data
      ir1->draw("false")
         if(delaySpacing == "log")
            ir1->image(data2d,[totalTime[0],totalTime[-1]]/1000,[dArray[0],dArray[-1]]/1000)
            ir1->ylabel("IR-delay (ms) - log mode")
            ir1->axes->ymapping("log")
         else
            ir1->image(data2d,[totalTime[0],totalTime[-1]]/1000,[dArray[0],dArray[-1]]/1000)
            ir1->ylabel("IR-delay (ms)")
            ir1->axes->ymapping("lin")
         endif
         ir1->title("T_(1)-T_(2) Correlation Data")
         ir1->xlabel("Echo time (ms)")
      ir1->draw("true")

      if(check == "finish")
         exitfor()
      endif

   next(d) # Next delay step

# Report the maximum SNR
   if(isvar("curSNRCtrl"))
      curSNRCtrl->text("$maxSNR,1.1f$")
   endif

# Save the data
   if(saveData == "true")
     keaFiles:save2DData(guipar,data2d/(nrScans*nrPnts))
   endif

# Increment the experiment number
   keaFiles:incrementExperiment(guipar)

# Return data
   result = struct()
   result->xaxis = linvec(totalTime[0]/1e3,totalTime[-1]/1e3,nrEchoes)
   result->yaxis = dArray/1e6
   result->T1T2corr = data2d

   return(result)

endproc("execpp")

#######################################################
# Invert the data
#######################################################

procedure(invert2DData)

   lst = getctrlvalues(0)
   assignlist(lst) 

   if(inversionMethod == "FISTA")
      :fistaCalc()
   else
      :maxEntropyCalc()
   endif

endproc()

#######################################################
# Maximum entropy inversion
#######################################################

procedure(maxEntropyCalc)

   lst = getctrlvalues(0)
   assignlist(lst)

   objNr = convergObj->ctrlnr
   convergObj->value(0)

  # Parameters for the user
   N_lambda_vert = y_steps
   N_lambda_hori = x_steps

  # Algorithm-internal parameters
   svdrankvert = 8
   svdrankhori = 8
   eps = 1e-8
   eta = 1e-4
   rho = smoothFactor/1000

  # Display the existing 2D data
   keaFiles:loadData()

  # Grab it
   (m,xr,yr) = getplotdata("2d")
   m = real(m)
   (w,h) = size(m)
   
  # Determine input ranges
   xMinIn = echoTime/1e6*(dummyEchoes+1)
   xMaxIn = nrEchoes*echoTime*(dummyEchoes+1)/1e6
   yMinIn = minTau/1000
   yMaxIn = maxTau/1000

  # Log bin x axis to make it more managable
   binnedWidth = 50
   mred = matrix(binnedWidth,h)
   xIn = linvec(xMinIn,xMaxIn,w)
   for(k = 0 to h-1)
      (x,mred[~,k]) = pseudologbin(xIn, m[~,k], binnedWidth)
   next(k)
  # image(mred)

   xaxis = double(pseudologvec(xMinIn,xMaxIn,binnedWidth))
   if(delaySpacing == "log")
      yaxis = double(logvec(yMinIn,yMaxIn,h))
   else
      yaxis = double(linvec(yMinIn,yMaxIn,h))
   endif

  # Normalise data
   mIn = double(mred/max(mred))

  # Output limits
   slow_hori = double(x_minimum)
   fast_hori = double(x_maximum)
   slow_vert = double(y_minimum)
   fast_vert = double(y_maximum)

  # Generate output space and kernels
   xOut = logvec(slow_hori, fast_hori, N_lambda_hori)
   yOut = logvec(slow_vert, fast_vert, N_lambda_vert)

  # Generate kernels
   Kh = exp(-xaxis'*(1/xOut))
   Kv = exp(-yaxis'*(1/yOut))

  # Initialise solution
   init = 0.01*mIn[0,0]/(N_lambda_vert*N_lambda_hori)
   solution = dmatrix( N_lambda_hori, N_lambda_vert) + init

   pr size(solution),size(mIn),size(Kh),size(Kv)
   pr ("Starting inversion core\n")
   time(0)

  # Perform the inversion
   (m_latest,regularized_error,mean_squared_error) = meil2d(mIn,xaxis,yaxis,solution,Kv,Kh,rho,svdrankvert,svdrankhori,eps,eta,nrIterations,":callBackME")

   pr "Time taken = $time()$\n"
   pr ("Regularized error  = $regularized_error$\n")
   pr ("Mean_squared_error = $mean_squared_error$\n")
   pr ("All done.\n")

  # Force convergence display to 100%
   convergObj->value(100)

  # Display the result
   if(isvar("wvPP2"))
      rg = wvPP2->subplot(1,1)
   else
      rg = curplot("2d")
   endif

   rg->draw("false")
   rg->image( m_latest,single([slow_hori, fast_hori]),single([slow_vert, fast_vert]))
   rg->axes("xmapping","log")
   rg->axes("ymapping","log")
   rg->xlabel("T2 (s)")
   rg->ylabel("T1 (s)")
   rg->title("T1-T2 correlation spectrum")
   rg->draw("true")

# Save the data
   guipar = getctrlvalues(0)

   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   if(expNr != "")
      mkdir("$expNr$")
      cd("$expNr$")
      expStr = "$expNr$\\Inversion"
   else
      expStr = "Inversion"
   endif

   mkdir("Inversion")
   cd("Inversion")
   save("inversion.pt2")
   save("inversion.2d",m_latest)

   pr("\n   2D inversion saved to:")
   pr("\n     $dataDirectory$\\$expName$\\$expStr$\\inversion.2d")
   pr("\n     $dataDirectory$\\$expName$\\$expStr$\\inversion.pt2")
   pr("\n")

   cd(bak)

endproc()


#######################################################
# Process the data (FISTA calc)
#######################################################

procedure(fistaCalc)

   lst = getctrlvalues(0)
   assignlist(lst)

   objNr = convergObj->ctrlnr
   convergObj->value(0)

  # Parameters for the user
   smth = (x_steps*y_steps)*smoothFactor/10000

  # Display the existing 2D data
   keaFiles:loadData()

  # Grab it
   (m,xr,yr) = getplotdata("2d")
   m = real(m)
   (w,h) = size(m)
   
  # Determine input ranges
   xMinIn = echoTime/1e6*(dummyEchoes+1)
   xMaxIn = nrEchoes*echoTime*(dummyEchoes+1)/1e6
   yMinIn = minTau/1000
   yMaxIn = maxTau/1000

  # Log bin x axis to make it more managable
   binnedWidth = 100
   mred = matrix(binnedWidth,h)
   xIn = linvec(xMinIn,xMaxIn,w)
   for(k = 0 to h-1)
      (x,mred[~,k]) = pseudologbin(xIn, m[~,k], binnedWidth)
   next(k)

   xaxis = double(pseudologvec(xMinIn,xMaxIn,binnedWidth))
   if(delaySpacing == "log")
      yaxis = double(logvec(yMinIn,yMaxIn,h))
   else
      yaxis = double(linvec(yMinIn,yMaxIn,h))
   endif

  # Normalise data
   mIn = double(mred/max(mred))

  # Output limits
   slow_hori = double(x_minimum)
   fast_hori = double(x_maximum)
   slow_vert = double(y_minimum)
   fast_vert = double(y_maximum)

  # Generate output space and kernels
   xSpec = logvec(slow_hori, fast_hori, x_steps)
   ySpec = logvec(slow_vert, fast_vert, y_steps)

  # Generate kernels
   Kh = exp(-xaxis'*(1/xSpec))
   Kv = exp(-yaxis'*(1/ySpec))

  # Get plot region
   if(isvar("wvPP2"))
      rg = wvPP2->subplot(1,1)
   else
      rg = curplot("2d")
   endif

   time(0)

 # Invert the data
   try
      startValue = 1
      solution = dmatrix(x_steps, y_steps) + startValue/(x_steps*y_steps)
      mInvert = fista(double(mIn),double(Kh),double(Kv),double(solution),
                      double(smth),nrIterations,2,rg,convergObj)
   catch
      pr lasterror()
      if(nrArgs == 1)
         :resetAllControls()
      endif
      return()
   endtry

   pr "   Time taken = $time()$\n"

  # Force convergence display to 100%
   convergObj->value(100)

# Plot the result
   rg->draw("false")
   rg->image(mInvert,single([slow_hori, fast_hori]),single([slow_vert, fast_vert]))
   rg->axes("xmapping","log")
   rg->axes("ymapping","log")
   rg->xlabel("T2 (s)")
   rg->ylabel("T1 (s)")
   rg->title("T1-T2 correlation spectrum")
   rg->draw("true")

# Save the data
   guipar = getctrlvalues(0)

   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   if(expNr != "")
      mkdir("$expNr$")
      cd("$expNr$")
      expStr = "$expNr$\\Inversion"
   else
      expStr = "Inversion"
   endif

   mkdir("Inversion")
   cd("Inversion")
   save("inversion.pt2")
   save("inversion.2d",mInvert)

   pr("\n   2D inversion saved to:")
   pr("\n     $dataDirectory$\\$expName$\\$expStr$\\inversion.2d")
   pr("\n     $dataDirectory$\\$expName$\\$expStr$\\inversion.pt2")
   pr("\n")

   cd(bak)

endproc()

###########################################################
# Load any previous results
###########################################################

procedure(loadResult)

   guipar = getctrlvalues(0)
   assignlist(guipar)

   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)
   if(expNr != "")
      mkdir("$expNr$")
      cd("$expNr$")
      dir = "$expNr$\\Inversion"
   else
      dir = "Inversion"
   endif

   if(isdir(dir))
      cd(dir)
      if(isfile("inversion.pt2"))
         load("inversion.pt2")
      endif
      if(isfile("inversion.par"))
        lst = load("inversion.par")
        setctrlvalues(0,lst)
      endif
   endif

   cd(bak)

endproc()


###########################################################
# Set inversion parameters based on
# pulse sequence parameters
###########################################################

procedure(resetPar)

   lst = getctrlvalues(0)
   assignlist(lst)

   x_minimum = echoTime/1e6
   x_maximum = nrEchoes*echoTime*(dummyEchoes+1)/1e6
   y_minimum = minTau/1000
   y_maximum = maxTau/1000

   x_steps = 40
   y_steps = 40

   smoothFactor = 1

   parlist = mkparlist()
   setctrlvalues(0,parlist)

endproc()

###########################################################
# Call backs to show Maximum entropy progress
###########################################################

procedure(callBackME,arg, p1,p2,p3)

  convergObj->value(arg)

endproc()

