#########################################################
# 
# T2CPMG
#
# CPMG pulse sequence in which each echo is summed to 
# return a single complex number per echo.
#
# 90 - delay - {180 - delay - acq}
#
# A parameter; "shift", is included to allow to allow
# data collection later in the echo, thereby reducing
# ringdown artefacts.
#
# Last modified : 13 March 2013
# Modified by : C Eccles, Magritek Ltd
# 
# Copyright (c) Magritek Ltd 2014
#
# U.I. V3
#########################################################

procedure(T2CPMG, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   n = :windowdefinition()

   windowvar(wv_dispMode,wv_ctrls,wv_shift,wv_other,wv_rel,
             wv_pp_list,wv_pp_name,wv_var,wv_tabs,wv_phase_list)

   wv_tabs  = ["Pulse Sequence","Progress","acquisition","processing+display","File settings"] # Tab names
   wv_ctrls = [2,26,27,36,37,60,61,68,69,89,90,99] # Control groups
   wv_shift = [-14,130,274,418,562,565] # Amount to shift control groups
   wv_other = [98,212,771]  # Collapse control and window size
   wv_saved = "false"

   (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar()

   if(nrArgs == 0)
      guipar = "show"
   endif

   keaCtrl:setUp(n,"T2CPMG",getmacropath(),guipar)
   if(guipar == "hide")
      return(n)
   elseif(guipar == "show")
      try; :initGUI(n); catch; endtry;
      showwindow(n)
      return(n)
   else
      setwindowpar(n,"type","dialog")
      guipar = showdialog(n)
      return(guipar)
   endif

endproc()

#########################################################
# 
# Returns important pulse sequence parameters
#
# rel ......... relationship between pulse sequence parameters
# var ......... variable which change during the pulse sequence
# pp_list ..... list of pulse sequence parameters sent to DSP
# pp_name ..... name of DSP pulse program to run
# phase_list .. phase cycling information
#
#########################################################

procedure(getseqpar)

   rel = ["ieTime = ieTime-40",
          "n3 = xcal*xshim/1000",
          "n4 = ycal*yshim/1000",
          "n5 = zcal*zshim/1000",
          "n6 = ocal*oshim/1000",
          "a1 = 90Amplitude",
          "a2 = 180Amplitude",
          "d1 = pulseLength",
          "d2 = echoTime/2-d1-pgo",
          "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
          "d4 = echoTime-d1-pgo-d3",
          "n1 = nrEchoes",
          "n2 = nrPnts",
          "totPnts = nrEchoes",
          "totTime = echoTime*nrEchoes"]
   var = [""]
   pp_list = ["n1","a1","p1","d1","d2","l1","a2","p2","d3","n2","d4"]
   pp_name = "T2CPMG.p"
   phase_list = [0,2,0,2;1,1,3,3;0,2,0,2]

endproc(rel,var,pp_list,pp_name,phase_list)


#########################################################
# 
# Provide an interface to this macro which does not
# require the use of the window interface
#
# User must supply a list of parameter (see help file)
# and the pulse program name if different from 
# "$macro$_ext.p"
#
#########################################################

procedure(backdoor, guipar)

   keaCtrl:checkVersion(2.15,1.1)

   (rel,var,pp_list,pp_name,phase_list) = :getseqpar()
  
   (guipar,ppList,pcList,pcIndex,varList) = keaCtrl:initialisePP(getmacropath(),getmacroname(),guipar,rel,var,pp_list,pp_name,phase_list)
   
   r = keaCtrl:runBDPP(guipar,ppList,pcList,pcIndex,varList)

endproc(r)

#########################################################
# 
# Define the window gui
#
#########################################################

procedure(windowdefinition)

   # Automatically generated window definition procedure.
   # Any code added manually will be removed if layout modified interactively
   n = window("T2 CPMG", -1, -1, 573, 768)

      # Define all controls with basic parameters
      getmessage(0,
        keaCtrl:processMessage();)
      tab(1, 6, 7, 555, 200,
         which = getpar(0,1,"currenttab");)
      groupbox(2, "Pulse sequence", 9, 9, 547, 137)
      statictext(3, 130, 35, "right", "B1 Frequency (MHz)")
      textbox(4, 136, 31, 46)
      statictext(5, 130, 61, "right", "Inter-exp delay (ms)")
      textbox(6, 136, 56, 46)
      statictext(7, 112, 112, "right", "Run to fixed SNR")
      checkbox(8, 118, 112, "fixedScans,minSNR", "fixedScans")
      statictext(9, 130, 86, "right", "Offset (Hz)")
      textbox(10, 136, 82, 46)
      statictext(11, 166, 112, "right", "SNR")
      textbox(12, 172, 108, 40)
      statictext(13, 310, 34, "right", "90 amplitude (dB)")
      textbox(14, 316, 30, 40)
      statictext(15, 310, 60, "right", "180 amplitude (dB)")
      textbox(16, 316, 56, 40)
      statictext(17, 310, 86, "right", "Pulse length (us)")
      textbox(18, 316, 82, 40)
      statictext(19, 310, 112, "right", "Echo shift (us)")
      textbox(20, 316, 108, 40)
      statictext(21, 490, 34, "right", "Echotime (us)")
      textbox(22, 496, 30, 40)
      statictext(23, 490, 60, "right", "Number of echoes")
      textbox(24, 496, 56, 40)
      statictext(25, 490, 112, "right", "Dummy scans")
      textbox(26, 496, 108, 40)
      groupbox(27, "Progress", 9, 153, 547, 137)
      statictext(28, 166, 205, "right", "Current scan:")
      statictext(29, 171, 205, "left", "0")
      statictext(30, 167, 226, "right", "Current SNR:")
      statictext(31, 172, 226, "left", "0")
      statictext(32, 422, 205, "right", "Estimated remaining expt. time (mm:ss):")
      statictext(33, 434, 205, "left", "00:00")
      statictext(34, 282, 226, "right", "Progress:")
      progressbar(35, 292, 225, 131, 16, "horizontal")
      statictext(36, 434, 226, "left", "00:00")
      groupbox(37, "Acquisition", 9, 297, 547, 137)
      statictext(38, 76, 320, "center", "Rx Gain (dB)")
      textmenu(39, 59, 338, 39, 200)
      statictext(40, 76, 369, "center", "Rx Phase (degrees)")
      textbox(41, 59, 385, 39)
      statictext(42, 184, 322, "center", "Number of")
      statictext(43, 184, 335, "center", "complex points")
      textmenu(44, 231, 324, 62, 200,
         keaCtrl:updateAcqTime();)
      statictext(45, 184, 354, "center", "Dwell time")
      statictext(46, 184, 367, "center", "(us)")
      textmenu(47, 231, 357, 62, 200,
         keaCtrl:updateFilters();)
      statictext(48, 184, 388, "center", "Number of")
      statictext(49, 184, 401, "center", "scans")
      textbox(50, 231, 389, 62)
      statictext(51, 358, 336, "center", "Flat filter")
      checkbox(52, 394, 337, "no,yes", "no",
           keaCtrl:setDwellTimeMenu();
           keaCtrl:updateFilters();)
      statictext(53, 358, 360, "center", "Accumulate")
      checkbox(54, 394, 361, "no,yes", "no")
      statictext(55, 358, 384, "center", "Phase cycle")
      checkbox(56, 394, 386, "no,yes", "yes")
      statictext(57, 486, 320, "center", "Spectral width (kHz)")
      textbox(58, 457, 334, 56)
      statictext(59, 486, 371, "center", "Acquisition time (ms)")
      textbox(60, 457, 385, 56)
      groupbox(61, "T2CPMG_Processing", 9, 441, 547, 137)
      groupbox(62, "", 177, 458, 210, 107)
      statictext(63, 227, 488, 54, 13, "center", "Auto-phase")
      checkbox(64, 259, 489, "no,yes", "no")
      statictext(65, 229, 512, 42, 13, "center", "Minimize")
      statictext(66, 227, 525, 55, 13, "center", "imag. range")
      checkbox(67, 259, 519, "maxreal,minimag", "maxreal")
      button(68, 306, 497, 51, 28, "Analyze",
         T2Analysis(guiwinnr(),"T2CPMG:getT2AnalysisPar",curplot("1d")->parent);)
      groupbox(69, "File_Settings", 9, 585, 547, 137)
      statictext(70, 79, 627, "right", "Working")
      statictext(71, 79, 640, "right", "directory")
      textbox(72, 95, 628, 215)
      button(73, 315, 628, 22, 22, "...",
         keaFiles:setWorkingDir();)
      statictext(74, 86, 664, "right", "Experiment")
      statictext(75, 71, 677, "right", "name")
      textbox(76, 95, 667, 105)
      button(77, 206, 667, 22, 22, "...",
         keaFiles:setExpName();)
      statictext(78, 308, 664, "right", "Experiment")
      statictext(79, 298, 677, "right", "number")
      textbox(80, 316, 667, 25)
      button(81, 346, 667, 22, 22, "...",
         keaFiles:setExpNr();)
      statictext(82, 370, 626, "center", "Save")
      statictext(83, 370, 639, "center", "data")
      checkbox(84, 398, 633, "false,true", "true")
      statictext(85, 414, 664, "center", "Auto")
      statictext(86, 414, 677, "center", "increment")
      checkbox(87, 449, 672, "no,yes", "no")
      button(88, 435, 621, 40, 36, "Load Data",
         keaFiles:loadData();)
      button(89, 490, 621, 40, 50, "Open data folder",
         keaFiles:openDataFolder();)
      colorbox(90, 18, 735, 10, 10, [255,255,255,255])
      colorbox(91, 18, 748, 10, 10, [255,255,255,255])
      button(92, 38, 732, 54, 29, "Run",
         (wv_rel,wv_var,wv_pp_list,wv_pp_name,wv_phase_list) = :getseqpar();
         keaCtrl:runPP(getmacropath(),wv_pp_name);)
      button(93, 103, 732, 54, 29, "Abort",
         setwindowpar(0,"title","Wait for macro to abort ...");
         wvExpStatus = "stop";)
      button(94, 168, 732, 54, 29, "Finish",
         setwindowpar(0,"title","Wait for phase-cycling to complete ...");
         wvExpStatus = "finish";)
      button(95, 233, 732, 54, 29, "Load Par.",
         keaFiles:loadParameters();)
      button(96, 298, 732, 54, 29, "Help",
         help("Macros\Tomograph","T2CPMG.htm");)
      button(97, 363, 732, 54, 29, "Kea Pref.",
         keaCtrl:showPreferences();)
      button(98, 428, 732, 54, 29, "Collapse",
         keaCtrl:toggleWindowSize(1);)
      button(99, 493, 732, 54, 29, "Close",
         guipar = getctrlvalues(0);
         if(getwindowpar(0,"type") == "dialog");
         guipar = keaFiles:addWindowSpecifics(guipar);
         keaFiles:saveCommonPar(guipar);
         closedialog(guipar);
         else;
         keaFiles:saveParameters();
         closewindow(0);
         endif;)
      menu(100, "bkgMenu", "Edit macro\tCtrl+Dbl-Click", edit("$getmacroname()$"),
                "Show compiler\tCtrl+Shift+Dbl-Click", MakePulseProgram("$getmacropath()$","$rmext(getmacroname())$"))

     # Set other control parameters
      setpar(n,1,"active","true",
                  "inittabs",[""])
      setpar(n,4,"valueID","b1Freq",
                  "tag","freqRange",
                  "type","double",
                  "range",[1,400])
      setpar(n,6,"valueID","ieTime",
                  "type","float",
                  "range",[80,1e+008])
      setpar(n,8,"valueID","t2SnrMode")
      setpar(n,10,"valueID","O1",
                  "type","float")
      setpar(n,12,"valueID","t2Snr",
                  "type","float",
                  "range",[0.1,1e+006])
      setpar(n,14,"valueID","90Amplitude",
                  "type","float",
                  "range",[-85,0])
      setpar(n,16,"valueID","180Amplitude",
                  "type","float",
                  "range",[-85,0])
      setpar(n,18,"valueID","pulseLength",
                  "type","float",
                  "range",[1,100])
      setpar(n,20,"valueID","echoShift",
                  "type","float",
                  "range",[-100,100])
      setpar(n,22,"valueID","echoTime",
                  "type","float",
                  "range",[2,327670])
      setpar(n,24,"valueID","nrEchoes",
                  "type","integer",
                  "range",[10,131072])
      setpar(n,26,"valueID","dummys",
                  "type","integer",
                  "range",[0,64])
      setpar(n,29,"objID","curScanCtrl")
      setpar(n,31,"objID","curSNRCtrl")
      setpar(n,33,"objID","remTimeCtrl")
      setpar(n,35,"objID","progressCtrl")
      setpar(n,36,"objID","expTimeCtrl")
      setpar(n,39,"valueID","rxGain",
                  "type","integer",
                  "tooltip","20-40 dB gives optimal SNR.\rDecrease if overload occurs.",
                  "range",[-20,70],
                  "menu",["-20","-17","-14","-11","-8","-5","-2","1","4","7","10","13","16","19","22","25","28","31","34","37","40","43","46","49","52","55","58","61","64","67","70"])
      setpar(n,41,"valueID","rxPhase",
                  "type","float",
                  "tooltip","Applies a fixed phase shift to collected data.\rIgnored if autophasing.")
      setpar(n,44,"valueID","nrPnts",
                  "type","integer",
                  "range",[2,65536],
                  "menu",["2","4","8","16","32","64","128","256","512","1024","2048","4096","8192","16384","32768","65536"])
      setpar(n,47,"valueID","dwellTime",
                  "type","float",
                  "menu",[""])
      setpar(n,50,"valueID","nrScans",
                  "type","integer",
                  "range",[1,1e+006])
      setpar(n,52,"valueID","flatFilter",
                  "tooltip","On: all frequencies equally weighted.\rOff: center frequencies enhanced.")
      setpar(n,54,"valueID","accumulate")
      setpar(n,56,"valueID","usePhaseCycle")
      setpar(n,58,"valueID","bandwidth",
                  "tag","disable")
      setpar(n,60,"valueID","acqTime",
                  "tag","disable")
      setpar(n,64,"valueID","autoPhase")
      setpar(n,67,"valueID","phaseMethod")
      setpar(n,72,"valueID","dataDirectory",
                  "type","string",
                  "tooltip","Where experimental data will be stored.")
      setpar(n,76,"valueID","expName",
                  "type","string",
                  "tooltip","A subdirectory of the data working directory to store different experiments.")
      setpar(n,80,"valueID","expNr",
                  "tooltip","A numbered subdirectory below the experiment name.\rNot made if entry is blank.")
      setpar(n,84,"valueID","saveData")
      setpar(n,87,"valueID","incExpNr",
                  "tooltip","Increment the experiment number after each experiment.")
      setpar(n,88,"tooltip","Load and display the data specified in the directories fields")
      setpar(n,89,"tooltip","View the data directory in Windows Explorer.")
      setpar(n,90,"objID","ppStatus",
                  "tooltip","Experiment Status Indicator\rGreen: running\rBlue: processing\rYellow: waiting")
      setpar(n,91,"objID","rxOverflow",
                  "tooltip","Receiver Overflow Indicator\rRed: overflow")
      setpar(n,92,"valueID","run",
                  "tooltip","Start the experiment.")
      setpar(n,93,"valueID","stop",
                  "tooltip","Stop the experiment without saving data.",
                  "active","true")
      setpar(n,94,"valueID","finish",
                  "tooltip","Finish the current phase cycle and save data.",
                  "active","true")
      setpar(n,95,"valueID","load",
                  "tooltip","Load a parameter set for a similar experiment.")
      setpar(n,96,"valueID","help",
                  "tooltip","Display HTML help for this experiment.",
                  "active","true")
      setpar(n,97,"valueID","showPref",
                  "tooltip","Display a preferences dialog for the Kea spectrometer.")
      setpar(n,98,"valueID","size",
                  "tooltip","Expand or collapse the window size to show all or fewer controls.",
                  "active","true")
      setpar(n,99,"valueID","close",
                  "tooltip","Close the window saving all parameters.")

     # Set other window parameters
      setwindowpar(n,"bkgmenu",100)

endproc(n)

#######################################################
# Execute the pulse program, collecting nrScans of 
# data and displaying the result in the 1D plot. 
#
# This procedure can be modified to perform more
# complex functions using the passed parameters:
#
# guipar ..... all parameters from the user interface
# ppList ..... the pulse program parameter list
# pcList ..... phase-cycle list
# pcIndex .... indices of phase parameters in ppList
# varIndex ... indices of variable parameters in ppList
#
# This version performs background subtraction
# when called in the RCA mode.
#
# 26-Nov-2013
#######################################################

procedure(execpp,guipar,ppList,pcList,pcIndex,varIndex)

   guipar = guipar + "timeMag = \"no\""

# Make all gui parameters available
   assignlist(guipar)

# Do some safety checks
   if(d3 <= 0)
     message("Error","Pulse sequence timing error!\rIncrease echo shift parameter.","error")
     wvExpStatus = "stop"
     return(0,0)
   endif
   if(d4 <= 0)
     message("Error","Pulse sequence timing error!\rIncrease echo time or reduce echo shift.","error")
     wvExpStatus = "stop" 
     return(0,0)
   endif
   
   if(d2 <= 0)
      message("Error","Pulse sequence timing error!\r90-180 time too short. Increase the echo time\ror reduce pulse length or damping time.","error")
      wvExpStatus = "stop"
      return(0,0)
   endif

   if(d4-keaRun:getAcqTime(guipar) < -1e-5)
      message("Error","Pulse sequence timing error!\rReduce number of points to $maxN$.","error")
      wvExpStatus = "stop"
      return(0,0)
   endif

 # Check RF duty cycle
   if(keaRun:highDutyCycle(d1*n1,nrEchoes*echoTime,guipar))
      wvExpStatus = "stop"
      return(0,0)
   endif

# Check phase cycling
  if(nrScans%4 != 0)
     if(query("Warning","For correct phase cycling this experiment\rrequires the number of scans be a mulitple of 4.\rDo you wish to proceed?") == "no")
        wvExpStatus = "stop"
        return(0,0)
     endif
  endif

# Calculate suitable time and frequency axes
   tAxis = ([0:1:totPnts-1]/totPnts)*totTime + echoTime

# Allocate data for outputs
   sumData = cmatrix(totPnts)

# Make subplots and define local variables
 
      windowvar(pdInt)
      prt = keaPlot:getPlotRegions(guipar,1,wvPP)
      wvExpStatus = "ok"
      assign("plotCtrl",wvPP,"window")
      autoPhaseMethod = phaseMethod
      bkgPhaseMethod = "useAutoPhase"
      eBak = null
      eqVolFac = 1
   

# Get background noise level if background exists
   if(eBak != null)
     sz = size(eBak)
     if(sz >= totPnts/2)
        ieBak = imag(eBak)
        ns = ieBak[round(size(ieBak)/2):]
        nsBak = keaRun:rmsValue(ns) # Noise is RMS of last half of data set
      else # Ignore background noise if shorter than half sample data
         nsBak = 0
      endif
   else # No background 
     nsBak = 0
   endif   

# Reset the timer
   time(0)  

   if(isvar("plotTab")) # From RCA interface
      targetSNR = t2Snr
      targetScans = t2Scans
      if(t2SnrModeCtrl->text == "minSNR")
         nrScans = 0
      endif
      mode = t2SnrModeCtrl->text
      assign("wvPP",plotCtrl,"global")
      nmrPorosityCtrl->text("--")
      fitMethodCtrl->text("")
      equivVolCtrl->text("--")
   else
      targetSNR = t2Snr
      targetScans = nrScans
      mode = t2SnrMode
   endif
   SNR = 0

# Intialise progress labels
   if(isvar("curScanCtrl"))
      curScanCtrl->text(0)
      progressCtrl->value(0)
      remTimeCtrl->text("00:00")
      curSNRCtrl->text("-")
   endif

# Intialise scan counter
   scan = -dummys

# Estimate repetition time
   repTime = ieTime + (nrEchoes*echoTime)/1000 + 40 # includes heater delay

# Accumulate scan
   while(1)

     if(scan == 0)
        time(0)
     endif

    # Note the time at scan start
      t1 = time()   

    # Set phases for this scan
      (ppList,pAcq) = keaRun:setPPPhase(ppList,scan,pcList,pcIndex)

    # Send phase parameters to DSP
      dspwrite("x",0x00,ppList,wvPort)

    # Collect the data
      (status,data) = keaRun:getData(totPnts,guipar)

      if(status != "ok")
         wvExpStatus = "stop"
         return(0,0)
      endif

      if(scan < 0)
         
         rg = plotCtrl->subplot(1,1) 
         rg->draw("false")
         rg->plot(matrix(totPnts))
         rg->xlabel("Points")
         rg->ylabel("Amplitude")
         rg->title("Dummy scan $-scan$")
         rg->draw("true")

      # Check timing
         check = keaRun:checkTimeAndAbort(guipar,t1,scan,pcList)
         if(check == "abort")
            return(0)
         elseif(check == "finish")
            exitwhile()
         endif

      else

      # Accumlate the data
         sumData = keaRun:accumulate(accumulate,pAcq,sumData,data)

      # Subtract unphased data sets and then autophase
         if(bkgPhaseMethod == "useRawPhase")
      
         # Subtract the background (if any from the data)
            if(eBak != null)
               difference = (scan+1)*RCA.pex:subtractBackgroundData(tAxis/1000,sumData/(nrPnts*(scan+1)),tBak,eBak)
            else
               difference = sumData/nrPnts
            endif
   
         # Phase the result
            if(autoPhase == "yes")
               (ph,sumDataAPDiff) = keaRun:autoPhase(difference,autoPhaseMethod)
            else
               sumDataAPDiff = difference
            endif

      # Autophase data and then subtract phased background
         else # Autophase method

         # Phase the result
            if(autoPhase == "yes")
               (ph,sumDataAP) = keaRun:autoPhase(sumData/nrPnts,autoPhaseMethod)
            else
               sumDataAP = sumData/nrPnts
            endif

         # Subtract the background (if any from the data)
            if(eBak != null)
               sumDataAPDiff = (scan+1)*RCA.pex:subtractBackgroundData(tAxis/1000,sumDataAP/(scan+1),tBak,eBak)
            else
               sumDataAPDiff = sumDataAP
            endif

         endif

       # Get correct labels
         (titleTxt,yTxt) = :getLabels(eBak,eqVolFac,mode,scan,nrScans)

       # Plot the integral data 
         if(isvar("wvT2Mapping"))
            prt->parent->draw("false")
            keaPlot:graphTime(prt,tAxis/1000,sumDataAPDiff*eqVolFac,scan,guipar,
                              titleTxt,"Time (ms)",yTxt)
            prt->axes->xmapping(wvT2Mapping)
            prt->parent->draw("true")
         else
            keaPlot:graphTime(prt,tAxis/1000,sumDataAPDiff*eqVolFac,scan,guipar,
                              titleTxt,"Time (ms)",yTxt)
         endif
       # Update GUI with scans and elapsed time
         if(isvar("curScanCtrl"))
            curScanCtrl->text(scan+1)
         endif

       # See if we are aborting
         if(wvExpStatus == "stop")
            return(0,0)
         endif
  
       # Check timing
         check = keaRun:checkTimeAndAbort(guipar,t1,scan,pcList)
         if(check == "abort")
            return(0)
         elseif(check == "finish")
            exitwhile()
         endif

       # Display current time
         if(isvar("expTimeCtrl"))
            et = time()
            tm = trunc(et/60)
            ts = trunc(frac(et/60)*60)
            expTimeCtrl->text("$tm,02.0f$:$ts,02.0f$")
         endif
   
       # Update GUI with SNR after each 4th scan
         if((scan+1)%4 == 0)
           # Calculate the SNR
            ns = imag(sumDataAPDiff)/(scan+1)
            ns = ns[round(size(ns)/2):-1]
            sd = keaRun:rmsValue(ns) # Noise is RMS of last half of data set
            sig = real(sumDataAPDiff)/(scan+1)
          #  sig = sum(sig[0:9])/10 # Signal is average of first 10 points
            sig = max(sig) # sig is the maximum

            if(sd != 0)
               SNR = sig/sd
            else
               SNR = 0
            endif
       
            if(isvar("curScanCtrl"))
               curSNRCtrl->text("$SNR,1.1f$")
               # See if target SNR has been reached
               if(mode == "minSNR")
                  f = :getTimeFactor(sig,sd,targetSNR,nsBak,scan)
                  if(f == -1)
                     message("Error","Target SNR will not be reached due to background noise.","error")
                     return(0,0)
                  endif
                  progressCtrl->value(round(100/f))
                  remainingTime = et*f-et
                  tm = trunc(remainingTime/60)
                  ts = trunc(frac(remainingTime/60)*60)
                  remTimeCtrl->text("$tm,02.0f$:$ts,02.0f$")
                  if(SNR >= targetSNR)
                     progressCtrl->value(100)
                     remTimeCtrl->text("00:00")
                     exitwhile()
                  endif
               endif
            endif # isvar("curScanCtrl")

         endif # (scan+1)%4
   
       # See if required number of scans has been reached
         if(mode == "fixedScans")
            if(scan+1 >= targetScans)
               exitwhile()
            endif
            if(isvar("remTimeCtrl"))
               if(scan == 0)
                  repTime = (time()-t1)*1000
               else # Keep a running average of repTime
                  repTime = ((time()-t1)*1000 + repTime*scan)/(scan+1)
               endif
               f = (scan+1)/targetScans
               progressCtrl->value(round(f*100))
               remainingTime = (1-f)*targetScans*repTime/1000
               tm = trunc(remainingTime/60)
               ts = trunc(frac(remainingTime/60)*60)
               remTimeCtrl->text("$tm,02.0f$:$ts,02.0f$")
            endif

         endif # mode == "fixedScans"

     endif # scan >= 0

     scan = scan+1

   endwhile() # Scan loop

# Total number of scans completed
   scan = scan+1

# Finalise labels
   if(isvar("curScanCtrl"))
      curScanCtrl->text(scan)
      progressCtrl->value(100)
      remTimeCtrl->text("00:00")
   endif

# Must have a multiple of 4 scan
#   if(scan%4 != 0)
#      message("Warning","Data not saved - multiple of 4 scans required","info")
#      return(0,0)
#   endif

# Make sure the uncorrected plot is saved 
# but the correct plot is visible
# and the phase correction used saved

# Get correct labels
   if(eBak != null)

      titleTxt = "T2 decay data for '$sampleName$'"
     # Phase the raw difference data
      if(bkgPhaseMethodCtrl->text == "useRawPhase")
         (ph,sumDataAP) = keaRun:autoPhase(sumData/nrPnts,autoPhaseMethod)
      endif

      prt->parent->draw("true")
      keaPlot:graphTime(prt,tAxis/1000,sumDataAP,scan-1,guipar,
                        titleTxt,"Time (ms)","Average echo amplitude (\G(m)V)")
      prt->axes->xmapping(wvT2Mapping)
      prt->parent->draw("true")
      keaFiles:save1DData(guipar,tAxis/1000,sumDataAP/scan)
     # Plot the phased corrected+calibrated data
     (titleTxt,yTxt) = :getLabels(eBak,eqVolFac,mode,scan-1,nrScans)

      prt->parent->draw("true")
      keaPlot:graphTime(prt,tAxis/1000,sumDataAPDiff*eqVolFac,scan-1,guipar,
                        titleTxt,"Time (ms)",yTxt)
      prt->axes->xmapping(wvT2Mapping)
      prt->parent->draw("true")
   else # Save the uncorrected data
      prt->title("T2 decay data")
      keaFiles:save1DData(guipar,tAxis/1000,sumDataAPDiff/scan)
   endif


 # Store the phase correction
   if(isvar("plotTab")) 
      t2PhaseValueCtrl->text(ph)
   endif

# Increment the experiment number
   keaFiles:incrementExperiment(guipar)

   return(0,0)

endproc("execpp")

#######################################################
# Get the plot labels based on display mode
#######################################################

procedure(getLabels,eBak,eqVolFac,mode,scan,nrScans)

   if(eBak != null) # We have a background to subtract
      if(eqVolFac != 1)  
         if(mode == "minSNR")
            titleTxt = "Calibrated & background corrected echo integrals (Acc: $scan+1$)"
            yTxt = "Equivalent volume (ml)"
         else
            titleTxt = "Calibrated & background corrected echo integrals (Acc: $scan+1$/$nrScans$)"
            yTxt = "Equivalent volume (ml)"
         endif
      else
         if(mode == "minSNR")
            titleTxt = "Background corrected echo integrals (Acc: $scan+1$)"
            yTxt = "Average echo amplitude (\G(m)V)"
         else
            titleTxt = "Background corrected echo integrals (Acc: $scan+1$/$nrScans$)"
            yTxt = "Average echo amplitude (\G(m)V)"
         endif
      endif

   else

      if(eqVolFac != 1)   # Calibration file present
         if(mode == "minSNR")
            titleTxt = "Calibrated echo integrals (Acc: $scan+1$)"
            yTxt = "Equivalent volume (ml)"
         else
            titleTxt = "Calibrated echo integrals (Acc: $scan+1$/$nrScans$)"
            yTxt = "Equivalent volume (ml)"
         endif
      else # No calibration file
         if(mode == "minSNR")
            titleTxt = "Echo integrals (Acc: $scan+1$)"
            yTxt = "Average echo amplitude (\G(m)V)"
         else
            titleTxt = "Echo integrals (Acc: $scan+1$/$nrScans$)"
            yTxt = "Average echo amplitude (\G(m)V)"
         endif
      endif

   endif

endproc(titleTxt,yTxt)


#######################################################
# Save the fitting information
#######################################################

procedure(saveFitList,guipar,fitlist)

# Extract GUI parameters
   assignlist(guipar)

# Save data and plot in chosen folder
   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)

   mkdir("Spectra")
   cd("Spectra")
   save("fitpars.lst",fitlist)

# Output information to the CLI
   pr "\n   Fit parameters saved to:"
   pr "\n     $dataDirectory$\\$expName$\\fitpars.lst\n"
# Restore cwd
   cd(bak)

endproc()

#######################################################
# Remove any T2 spectral information
#######################################################

procedure(deleteSpectrum,guipar)

# Extract GUI parameters
   assignlist(guipar)

# Save data and plot in chosen folder
   bak = getcwd()
   cd(dataDirectory)
   mkdir(expName)
   cd(expName)

   if(isdir("Spectra"))
      cd("Spectra")
      files = getfilelist(".")
      for(k = 0 to size(files)-1)
         rmfile(files[k])
      next(k)
      cd("..")
      rmdir("Spectra")
   endif

endproc()

##################################################################
# Get T2Analysis parameters (called from T2Analysis)
##################################################################

procedure(getT2AnalysisPar, winNr)

   keepfocus("true")
   winBak = guiwinnr()
   guiwinnr(winNr)
   guipar = getctrlvalues(0)
   assignlist(guipar)


   par = struct()
   par->src = "T2CPMG"
   if(expNr == "")
      par->dataDir = "$dataDirectory$\\$expName$"
   else
      par->dataDir = "$dataDirectory$\\$expName$\\$expNr$"
   endif
   par->sampleVolume = 0
   par->sampleName = ""
   par->project = getbasedir(getmacropath())
   par->porosityCtrl = null
   par->fitMethodCtrl = null
   par->win = null
   par->guiPar = null
   par->bkgPhaseMode = "autophase"
   par->autoPhaseMethod = "maxreal"
    
   guiwinnr(winBak)
   keepfocus("false")

endproc(par)


#####################################################
# Get a factor which determines how much longer to
# scan to get the desired SNR
#
# sig ......... current signal level
# sd .......... current noise level
# targetSNR ... target SNR
# nsBak ....... noise level of background signal
#####################################################

procedure(getTimeFactor,sig,sd,targetSNR,nsBak,scan)

  SNR = sig/sd
  fTarget = (targetSNR/SNR)^2 # Factor assuming no background 
  nsCur = sd
  nsSamp = sqrt(nsCur^2-nsBak^2)
  sqrNsTarg = (nsCur^2/fTarget - nsBak^2)

  if(sqrNsTarg <= 0) # We will never get to the target SNR
     return(-1)
  endif
  nsTarg = sqrt(sqrNsTarg)
  fRequired = (nsSamp/nsTarg)^2 # Factor with background included

# Work out the number of scans required (must be a multiple of 4)
   nrScans = fRequired*(scan+1)
   if(frac(nrScans/4) != 0)
      nrScans = (trunc(nrScans/4)+1)*4
      fRequired = nrScans/(scan+1)
   endif

endproc(fRequired)


