# getbasedir function test
procedure(getbasedir_test1,verbose,delay)

   workdir = "C:\\Program Files\\Prospa\\Example Data\\Import"
   base = getbasedir(workdir)
   if(base != "Import")
      return(0, "Invalid result for: getbasedir_test1() #1")
   endif

   workdir = "C:\\Program Files\\Prospa\\Example Data\\Import test"
   base = getbasedir(workdir)

   if(base != "Import test")
      return(0, "Invalid result for: getbasedir_test1() #2")
   endif

endproc(1,"")
