###################################################################################
# 
###################################################################################

procedure(acquireon, arg1, arg2)
      
   if(gSeq->psInfo->skipCmds == 0)
      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 0.5
      gSeq->psInfo->command = gSeq->psInfo->command + ["acquireon"]
   endif

endproc()

