###################################################################################
# 
###################################################################################

procedure(iftrue, skipName, condition)

   cnt = gSeq->psInfo->loopCnt
   gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt]
   gSeq->psInfo->skipCmds = not(condition)
   gSeq->psInfo->command = gSeq->psInfo->command + ["iftrue,$skipName$,$condition$"]

endproc()

