###################################################################################
#######################################################

procedure(inctxamp, ampName, increment)

   if(gSeq->psInfo->skipCmds == 0)

      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 0.5 # Check
      gSeq->psInfo->command = gSeq->psInfo->command + ["incrxfreq","$args[0]$","$args[1]$"]

   endif

endproc()

