###################################################################################
# 
###################################################################################

procedure(setrxfreq, f1)

   if(gSeq->psInfo->skipCmds == 0)

      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 0.5
      gSeq->psInfo->command = gSeq->psInfo->command + ["setrxfreq,$f1$,$args[0]$"]

   endif

endproc()

