###################################################################################
# 
###################################################################################

procedure(skiponfalse, skipName, condition)

   cnt = gSeq->psInfo->loopCnt
   gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt]
   gSeq->psInfo->command = gSeq->psInfo->command + ["skiponfalse,$skipName$,$condition$"]
   gSeq->psInfo->skipCmds = not(condition)

endproc()

