###################################################################################
#######################################################

procedure(stoplockandsat, trigger_length=200, timeout=50)

   if(gSeq->psInfo->skipCmds == 0)

      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 1000 # Guess
     # gSeq->psInfo->command = gSeq->psInfo->command + ["delay,$duration$,$args[0]$"]

   endif

endproc()

