###################################################################################
#######################################################

procedure(ttloff, byte=0)

   if(gSeq->psInfo->skipCmds == 0)

      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 0.18
      gSeq->psInfo->command = gSeq->psInfo->command + ["ttloff,$byte$,$args[0]$"]

   endif

endproc()

