###################################################################################
#######################################################

procedure(ttlon, byte)

   if(gSeq->psInfo->skipCmds == 0)

      args = getargnames()
      cnt = gSeq->psInfo->loopCnt
      gSeq->psInfo->durationNStk[cnt] = gSeq->psInfo->durationNStk[cnt] + 0.17
      gSeq->psInfo->command = gSeq->psInfo->command + ["ttlon,$byte$,$args[0]$"]

   endif

endproc()

