########################################################
#
# Saturation recovering sequence with CPMG detection
# www.magritek.com, March 2013
# Prospa V3.12
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, ctrlType, varType)
   interface = ["b1Freq",      "B1 Frequency (MHz)",   "0","0",    "tbwv",    "freq",
               "repTime",      "Repetition time (ms)", "0","1.6",   "tbwv",   "float,[20,1e8]",

               "90Amplitude",  "90 amplitude (dB)",    "1","0",     "tb",     "float,[-72,-6]",
               "180Amplitude", "180 amplitude (dB)",   "1","1",     "tb",     "pulseamp",
               "pulseLength",  "Pulse length (us)",    "1","2",     "tb",     "float,[1,500]",

               "echoTime",     "Echotime (us)",        "2","0",     "tb",     "sdelay",
               "nrEchoes",     "Number of echoes",     "2","1",     "tb",     "integer,[1,16000]",
               "echoShift",    "Echo shift (us)",      "2","2",     "tb",     "float,[-20,20]",

               "t1Est",        "T1 estimation (ms)",   "3","0",     "tb",     "float,[1,10000]",
               "tMax",         "Max. recov. time (ms)","3","1",     "tb",     "float,[0,60000]",
               "nrPntsT1",     "Number of time increm.","3","2",    "tb",     "integer,[1,1000]",
               "index",        "Time increment"        ,"3","3",    "tm",     "[\"lin\",\"exp\"]"]

  tabs = ["Pulse_sequence","Acquisition","Processing_Display_Std","File_Settings"]

# Relationships between pulse-sequence and GUI parameters
   relationships = ["a1 = 90Amplitude",
                    "a2 = 180Amplitude",
                    "d1 = pulseLength",
                    "d2 = echoTime/2-d1-pgo",
                    "d3 = echoTime/2-acqTime*500-d1/2+rxLat+echoShift",
                    "d4 = echoTime-d1-pgo-d3",
                    "d10 = 750-pgo",
                    "d9 = 500-pgo",
                    "d8 = 350-pgo",
                    "d7 = 200-pgo",
                    "d6 = 150-pgo",
                    "d5 = 100-pgo",
                    "w1 = tMax",
                    "n1 = nrEchoes",
                    "n2 = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# These parameters will be changed between experiments
   variables = ["w1"]

# x and y spacing between controls
   dim = [155,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   cleardata(64000)

   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d5)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d6)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d7)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d8)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d9)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse
   delay(d10)                   # delay
   pulse(mode,a1,p1,d1)    # 90 pulse

   wait(w1)                    # recovering delay

   pulse(mode,a1,p2,d1)           # 90 pulse
   delay(d2)                      # 90 - 180 delay

   loop(l1,n1)
      pulse(mode,a2,p3,d1)        # 180 internal pulse
      delay(d3)                   # 180 - acq delay
      acquire("sum",n2,d4)     # Acquire echo and wait
   endloop(l1)

   lst = endpp() # Return parameter list

# Phase cycle
    phaseList = [0,2,0,2;
                 0,0,2,2;
                 1,1,1,1;
                 0,0,2,2]
#     phaseList = [0,0;
#                 0,2;
#                 1,1;
#                 0,2]

endproc(lst,tabs,interface,relationships,variables,dim,phaseList)
