procedure(cumsum_test1,verbose,delay)
	# scalars will fail
	try		
		cumsum(1) = 1
	catch
		print "passed: cumsum cannot add real scalars\n"
	endtry

	try
		cumsum(1 + 1i) = 1 + i1
	catch
		print "passed: cumsum cannot add complex scalars\n"
	endtry
	
   tests = load("cumsum1.lst")

   for(n = 0 to size(tests)-1)
      s = tests[n]
      if(s[0] != "#")
         if(eval(tests[n]) == 0)
            return(0, "Invalid result for: $tests[n]$")
         endif 

         if(verbose)
            pr "      Valid test: $tests[n]$\n"  
         endif
      endif
   next(n)

endproc(1,"")
