procedure(clear_test1,verbose,delay)

# Make a 1D plot and clear it
   t = [0:511]/512
   y = sin(t*20*pi).*exp(-t*5)
   plot(t,y)
   pause(delay)
   clear("plot")
   
# Make a 2D plot and clear it
   m = y'*y
   image(m)
   pause(delay)
   clear("plot")

# Print some CLI stuff and clear it
#  m = noise(10)
#  pr m'
#  pause(delay)
#  clear("cli")

# Load something into the editor and clear it
  txt = load("clear_test1.mac","macro","yes")
  pause(delay)
  clear("edit")

endproc(1,"")
