########################################################
# 
# Slice selective spin-echo imaging
#
########################################################

procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1Freq",        "B1 Frequency (MHz)",        "0","0", "tbw", "freq",
               "repTime",       "Repetition time (ms)",      "0","1", "tbw", "reptime",
               "O1",            "Offset (Hz)",               "0","2", "tbw",  "float", 
               "SPType",        "Soft pulse shape",          "0","3", "tm",  "60,[\"sinc3\",\"sinc5\",\"gauss\",\"rect\"]",        
               "pulseLength90", "90 pulse length (us)",      "0","4", "tb",  "pulselength",
               "a1",            "rf amplitude (dB)",         "0","5", "tb",  "pulseamp",
               "a2",            "180 amplitude (dB)",        "0","6", "tb",  "pulseamp", 
               "sliceComp",     "sliceComp(us)",             "0","7", "tb",  "float,[-1000,1000]",

               "echoTime",      "Echotime (us)",             "1","0", "tb",  "sdelay",
               "acqShift",      "acquisition Shift(us)",     "1","1", "tb",  "sdelay",
               "estTimeR",      "estabil. Time read (us)",   "1","2", "tb",  "sdelay",
               "acqShiftRead",  "acqShiftRead (us)",         "1","3", "tb",  "float,[-1000,1000]",
               "timeReadCPMG",  "tim. CPMG Read (us)",       "1","4", "tb",  "float,[-1000,1000]",
              
               "FoVRead",       "FoV Read (mm)",             "2","0", "tb",  "float,[-10000,10000]",
               "FoVPhase1",     "FoV Phase1 (mm)",           "2","1", "tb",  "float,[-10000,10000]",
               "nrStepsP1",     "nr. pixels phase1",         "2","2", "tb",  "integer,[1,500]",
               "FoVPhase2",     "FoV Phase2 (mm)",           "2","3", "tb",  "float,[-10000,10000]",
               "nrStepsP2",     "nr. pixels phase2",         "2","4", "tb",  "integer,[1,500]",
               "sliceTickness", "Slice thickness (mm)",      "2","5", "tb",  "float,[0,10000]",
               "sliceShift",    "Slice shift (mm)",          "2","6", "tb",  "float,[-10000,10000]",

               "dirRead",       "",                          "2.3","0", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase1",     "",                          "2.3","1", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirPhase2",     "",                          "2.3","3", "tm",  "[\"x\",\"y\",\"z\"]",
               "dirSlice",      "",                          "2.3","5", "tm",  "[\"x\",\"y\",\"z\"]"]      


 # Relationships to determine remaining variable values
  relationships = [ "d600 = 2",     
                    "n600 = round(pulseLength90/d600)",
                    "(t1,t2,gfac) = B1NutSoft:getRFPulse(SPType,a1,n600)",
                    "(t3,t4,gfac) = B1NutSoft:getRFPulse(SPType,a2,n600)",
                    "pulseLength180 = pulseLength90",
                    "rampDur = 50",
                    "d300 = 2.5",
                    "d100 = 2",
                    "d101 = 100",
                    "d102 = 100",
                    "n300 = round(rampDur/d300)",
                    "d8 = estTimeR",
                    "d7 = 2000",
                    "phDur1 = rampDur*nrStepsP1/2",
                    "phDur2 = d7+2*rampDur",
                    "sliceComp = 0",
                    "(del11,del19) = EPI_3D:getRewindSliceDelay(pulseLength90,sliceComp,rampDur)",
                    "d19=del19",
                    "d11=del11",   
                    "d3 = 1000*acqTime/2+rxLat+d8-rampDur/2-acqShiftRead",
                    "d4 = echoTime/2-d3-2*rampDur-d7-2*rampDur-pulseLength90/2-3*rampDur-d11-d19-(pulseLength180+2*d102+2*rampDur)/2-pgo",
                    "d9 = 2*d3 - d8 + rampDur",
                    "d10 = d9+timeReadCPMG",
                    "d5 = echoTime/2-(pulseLength180+2*d102+2*rampDur)/2-(2*d100+2*rampDur+rampDur+d8+d9+rampDur-4*2.5)*nrStepsP1/2",
                    "n10  = EPI_3D:convertDirToChannel(dirRead)",
                    "n20  = EPI_3D:convertDirToChannel(dirPhase1)",
                    "n40  = EPI_3D:convertDirToChannel(dirPhase2)",
                    "n30  = EPI_3D:convertDirToChannel(dirSlice)",
                    "(gReadAmp,gReadAmpShim,gPhaseAmp1,gPhaseAmpShim1,gPhaseAmp2,gPhaseAmpShim2,gSliceAmp,gSliceAmpShim,sliceOffSet) = EPI_3D:setImageGradients(dirRead,dirPhase1,dirPhase2,dirSlice,FoVRead,FoVPhase1,FoVPhase2,phDur1,phDur2,sliceTickness,sliceShift,gfac,xshim,yshim,zshim,xcal,ycal,zcal)",    
                    "n31 =  gSliceAmp+gSliceAmpShim", 
                    "n31a = gSliceAmpShim", 
                    "n32  = -gSliceAmp+gSliceAmpShim",
                    "n1   = round(nrStepsP1/2)",
                    "n11 = gReadAmp+gReadAmpShim",
                    "n11a = gReadAmpShim",
                    "n12  = -gReadAmp+gReadAmpShim",
                    "n21a = gPhaseAmpShim1",
                    "n21 =  gPhaseAmp1*(nrStepsP1/2)*(rampDur)/(2*rampDur+d7)+gPhaseAmpShim1",
                    "n22 =  gPhaseAmp1+gPhaseAmpShim1",
                    "n41a = gPhaseAmpShim2",
                    "n41  = gPhaseAmpShim2",
                    "f1  =  b1Freq+O1/1e6+sliceOffSet",
                    "f2  =  b1Freq+O1/1e6",   
                    "n2 = nrPnts",
                    "totPnts = nrPnts*nrStepsP1",
                    "totTime = echoTime*nrStepsP1"]


# Define the tabs and their order
   tabs = ["Pulse sequence","Acquisition","Processing+Display","File Settings"]

# These parameters will be changed between experiments
   variables = ["n41"]

# dx,dy
   dim = [170,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   settxfreq(f1)                         
   gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
      delay(d101)                          # stabilization time slice
      shapedrf(mode,t1,t2,p1,n600,d600)    # 90 soft pulse
      delay(d19)
   gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF
   
   settxfreq(f2)

   gradramp(n30,n31a,n32,n300,d300)     # SLICE gradient ON
      delay(d11)
   gradramp(n30,n32,n31a,n300,d300)     # SLICE gradient OFF  
     
   gradramp(n10,n11a,n11,n300,d300)      # READ ON gradient
      delay(d3)
   gradramp(n10,n11,n11a,n300,d300)      # READ OFF gradient

   gradramp(n20,n21a,n21,n300,d300)     # PHASE1 ON gradient
   gradramp(n40,n41a,n41,n300,d300)     # PHASE2 ON gradient
      delay(d7)
   gradramp(n20,n21,n21a,n300,d300)     # PHASE1 OFF gradient
   gradramp(n40,n41,n41a,n300,d300)     # PHASE2 OFF gradient
  
   delay(d4)

   settxfreq(f1) 
   gradramp(n30,n31a,n31,n300,d300)        # Slice grad ON
      delay(d102)                          # stabilization time slice
      shapedrf(mode,t3,t4,p2,n600,d600)    # 180 soft pulse
      delay(d102)                          # stabilization time slice
   gradramp(n30,n31,n31a,n300,d300)        # Slice grad OFF

   settxfreq(f2)


   delay(d5)

   loop(l1,n1)
    
      gradramp(n20,n21a,n22,n300,d300)     # PHASE ON gradient
      gradramp(n20,n22,n21a,n300,d300)     # PHASE OFF gradient
      delay(d100)

      gradramp(n10,n11a,n11,n300,d300)      # READ ON gradient
         delay(d8)
         acquire("append",n2,d9)
      gradramp(n10,n11,n11a,n300,d300)      # READ OFF gradient
      delay(d100)

      gradramp(n20,n21a,n22,n300,d300)     # PHASE ON gradient
      gradramp(n20,n22,n21a,n300,d300)     # PHASE OFF gradient
      delay(d100)

      gradramp(n10,n11a,n12,n300,d300)      # READ ON gradient
         delay(d8)
         acquire("append",n2,d10)
      gradramp(n10,n12,n11a,n300,d300)      # READ OFF gradient
      delay(d100)

   endloop(l1)

   lst = endpp() # Return parameter list

# Phase cycle list
   phaseList = [0,2; # +x,-x : 90 phase
                1,1; # +y,+y : 180 phase
                0,2] # +x,-x : Acquire phase


endproc(lst,tabs,interface,relationships,variables,dim,phaseList)