##################################################
#               moveorigin1d.mac
#
# Toggle the position of the origin from the 
# beginning to the centre of the data set
#
# Author: C Eccles
#
# Copyright (c) Magritek December 2005
###################################################

procedure(moveorigin1d)
   (x,y) = getplotdata("1d")
   if(x != null)
      plot(x,ftshift(y))
   else
      message("Can't complete operation","No 1D data set presently plotted");
   endif
endproc()
