########################################################
#
# Samples noise data and calculates the rms value
#
########################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, x, y, control_type, variable_type)
  interface = ["b1FreqCh1", "B1 Frequency (MHz)",   "tb",  "freq";
               "repTime",   "Repetition time (ms)", "tb",  "reptime";
               "refLevel",  "Reference level (uV)", "tb",  "float,[0,1000]";
               "showRef",   "Show reference",       "cb",  "no,yes"]
 
# Relationships to determine remaining variable values
   relationships = ["n1 = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# Define the parameter groups and their order
   groups = ["Pulse_sequence","Acquisition","Processing_Std","Display_PPM_Range","File Settings"]

# These parameters will be changed between experiments
   variables = [""]

# Pulse sequence
   initpp(dir) # Reset internal parameter list
      acquire("overwrite",n1)     # Acquire echo and wait
   lst = endpp(0) # Return parameter list

# Phase cycle
   phaseList = [1,1,1,1]   # Acquire phase

endproc(lst,groups,interface,relationships,variables,0,phaseList)


#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   specPar = KeaParameterUpdater:readSpecPar()
   if(specPar == null)
      return(null)
   endif
   assignlist(specPar)

   par = ["rxGain    = $rxOptGaindB$",
          "b1FreqCh1 = $frequencyCh1$"]

endproc(par)

#####################################################
# Simulation code - only used in Simulation mode
#####################################################

#####################################################
# Defines the location of important variables in 
# the pulse program list
#####################################################

procedure(setSimParIndices, name, parNames, parIndex)

   SimulationInfo->name = name
#   SimulationInfo->pulseAmpIndex    = parIndex[getlistindex(parNames,"a90Amp")]
#   SimulationInfo->pulsePhaseIndex  = parIndex[getlistindex(parNames,"p1")]
#   SimulationInfo->pulseLengthIndex = parIndex[getlistindex(parNames,"d90Dur")]
#   SimulationInfo->acquDelayIndex   = parIndex[getlistindex(parNames,"dAcqDelay")]

endproc()

#####################################################
# Update the simulation parameters based on the 
# variable values in the pulse program list
#####################################################

procedure(setSimParValues, ppList)

#   pulseAmp = ppList[SimulationInfo->pulseAmpIndex]
#   pulseLength = (ppList[SimulationInfo->pulseLengthIndex]+1.0)/50.0
#   SimulationInfo->pulseIntegral = pulseAmp*pulseLength
#   pulsePhase = ppList[SimulationInfo->pulsePhaseIndex]/65536.0*2*pi
#   SimulationInfo->pulsePhase = pulsePhase 
#   SimulationInfo->acquisitionDelay = (ppList[SimulationInfo->acquDelayIndex]+1.0)/50.0

endproc()

#####################################################
# Generate some simulated T1-IR data based on the
# values stored in SimulationInfo
#####################################################

procedure(simulateNMR, dataSize)

   assignstruct(SimulationInfo)

# Non-experiment specific parameters
#    DW = dwellTime*1e-6 # <= This is the dwell time
#    off = single(1e6*(b1Freq-b0Freq)) # <= This is the offset (b1Freq - f0)
#    sigAmp = signalAmplitude*receiverGain
#    ph = receiverPhase - pulsePhase 
#    pulseInt = pulseIntegral
#    pulse90Int = pulse90Integral
#    sigAmp = sigAmp *sin(pulseInt*pi/(2*pulse90Int))
    nl = noiseAmplitude*receiverGain*sqrt(1.0/dwellTime)
pr dwellTime
pr receiverGain
pr noiseAmplitude
   mat = nl*noise(dataSize)

endproc(mat)
