procedure(pathnames_test1,verbose,delay)

   datadir  = pathnames("data")
   macrodir = pathnames("macrodata")
   plot1dir = pathnames("plot1d")
   plot2dir = pathnames("plot2d")
   import1dir = pathnames("import1d")
   import2dir = pathnames("import2d")
   import3dir = pathnames("import3d")
   export1dir = pathnames("export1d")
   export2dir = pathnames("export2d")
   export3dir = pathnames("export3d")

endproc(1,"")