
procedure(pulse_program,dir,mode)


# Interface description (name, label, x, y, ctrlType, varType)
   interface = ["b1Freq",      "B1 Frequency (MHz)",   "0","0",   "tbwv",   "freq",
               "repTime",      "Repetition time (ms)", "0","1.6", "tbwv",   "reptime",
               "O1",           "Offset (Hz)",          "0","3",   "tbwv",   "float",
               "90Amplitude",  "90 amplitude (dB)",    "1","0",   "tb",     "pulseamp",
               "pulseLength",  "Pulse length (us)",    "1","1",   "tb",     "pulselength",
               "deadTime",     "deadTime (us)",        "1","2",   "tb",     "sdelay",
               "updateFreq",   "updateFreq",           "2","0",   "cb",     "no,yes",
               "autoPhase",    "Auto-phase",           "2","1",    "cb",     "no,yes"]

  tabs = ["Pulse sequence","Acquisition","Processing+Display","File Settings"]

# Relationships between pulse-sequence and GUI parameters
   relationships = ["a1 = 90Amplitude",
                    "d1 = pulseLength",
                    "d2 = deadTime",
                    "n1 = nrPnts",
                    "totPnts = nrPnts",
                    "totTime = acqTime"]

# These parameters will be changed between experiments
   variables = [""]

# x and y spacing between controls
   dim = [155,26]

# Pulse sequence
   initpp(dir) # Reset internal parameter list

   pulse(mode,a1,p1,d1)           # 90 pulse
   delay(d2)                      # delay
   acquire("overwrite",n1)        # acquire    
    
   lst = endpp() # Return parameter list

# Phase cycle
   phaseList = [0; # 90 phase
                0] # acquire phase


endproc(lst,tabs,interface,relationships,variables,dim,phaseList)
