procedure(hold_test1,verbose,delay)

   clear1d()
   (x,y) = complex(1024,1,10,0.05)
    f = [0:1023]-512
    plot(f,real(ft(y)))
    hold("on")
   (x,y) = complex(1024,1,200,0.05)
    f = [0:1023]-512
    plot(f,real(ft(y)),"tracecolor",[255,0,0])

   (x,y) = complex(1024,1,-200,0.05)
    f = [0:1023]-512
    plot(f,real(ft(y)),"tracecolor",[0,255,0])

    title("hold test")

    pause(delay)

endproc(1,"")