procedure(interface_description)

  interface = ["saveData","Save data?","cb", "string", "false,true"]

endproc(interface,"Files")


procedure(help)

pr "\n\n -------------- File settings information ---------------------\n\n"
pr "   Save data: (saveData)\n"
pr "      Whether data will be saved or not.\n      Options: yes/no.\n"
pr "\n --------------------------------------------------------------------------------\n"

endproc()