procedure(movewindow_test1,verbose,delay)

   (win,x0,y0,w0,h0) =  movewindow("getargs")

   movewindow(win,0.1,0.1,0.4,0.4)

   for(x = 0 to pi step pi/64)
      movewindow(win,0.1+0.2*sin(x),0.1,0.4,0.4)
   next(x)

   for(y = 0 to pi step pi/64)
      movewindow(win,0.1,0.1+0.2*sin(y),0.4,0.4)
   next(x)

   for(w = 0 to pi step pi/32)
      movewindow(win,0.1,0.1,0.4+0.2*sin(w),0.4)
   next(x)

   for(h = 0 to pi step pi/32)
      movewindow(win,0.1,0.1,0.4,0.4+0.2*sin(h))
   next(x)

   movewindow(win,x0,y0,w0,h0)

endproc(1,"")
 
