procedure(groupbox_test1,verbose,delay)
 
   n = window("Group-box test", 139, 138, 300, 300)
   groupbox(1, "test",10, 10, 100, 100)
   showwindow(n)
   :boxtitle(n)
   :movebox(n)
   :growbox(n)
   pause(delay)
   closewindow(n)

endproc(1,"")


procedure(boxtitle,n)

   for (m = 10 to 0 step -1)
      setpar(n,1,"label","$m$");
      drawwin(n)
      pause(0.5)
   next (m)

endproc()

procedure(movebox,n)

   for (theta = 0 to 360)
      x = 50 * cos(theta/180*pi) + 75
      y = 50 * sin(theta/180*pi) + 75
      setpar(n,1,"x",x);
      setpar(n,1,"y",y);
      drawwin(n)
      pause(0.005)
   next (theta)

endproc()

procedure(growbox,n)

   setpar(n,1,"x",75);
   setpar(n,1,"y",50);

   for (w = 50 to 100)
     drawwin(n)
     pause(0.005)
  next (w)

   for (w = 100 to 50 step -1)
     drawwin(n)
     pause(0.005)
  next (w)

   for (w = 50 to 100)
     setpar(n,1,"height",w);
     setpar(n,1,"width",w);
     drawwin(n)
     pause(0.005)
  next (w)

   for (w = 100 to 50 step -1)
     setpar(n,1,"height",w);
     setpar(n,1,"width",w);
     drawwin(n)
     pause(0.005)
  next (w)
endproc()

 
