procedure(tracedefaults_test1,verbose,delay)


   tracedefaults("tracetype", "none", "symbolshape", "opensquare",
                 "symbolcolor", [255,0,0]) 

   x = [0:1:99]
   y = 10*noise(100) + x 
   plot(x,y)  # Plot a noisy data set

   tracedefaults("tracetype", "lines", "symbolshape", "none",
                  "tracecolor", [255,255,0],"tracewidth",2) 
   
   hold("on")
   plot(x,x) # Plot ideal data set

   
   title("trace command test")
   ylabel("y")
   hold("off")

   tracedefaults("tracetype", "lines", "symbolshape", "none",
                  "tracecolor", [255,255,0],"tracewidth",1) 

endproc(1,"")
