###########################################################
# A class to allow regions to be integrated
# in a stacked plot. Works with 1DPlotAnalyser
#
# Author: C Eccles
# Copyright Magritek 2023-2026
#
###########################################################

procedure(init, self)

   self->procedureList = "============================================="
   self->integratePeak         = "integrateClass:integratePeak"
   self->removeIntegral        = "integrateClass:removeIntegral"
   self->clearIntegrals        = "integrateClass:clearIntegrals"
   self->exportIntegrals       = "integrateClass:exportIntegrals"
   self->addFit                = "integrateClass:addFit"
   self->deleteFit             = "integrateClass:deleteFit"
   self->editFit               = "integrateClass:editFit"
   self->fitToData             = "integrateClass:fitToData"
   self->fitAll                = "integrateClass:fitAll"
   self->refreshList           = "integrateClass:refreshList"
   self->readData              = "integrateClass:readData"
   self->drawIntegratedData    = "integrateClass:drawIntegratedData"
   self->updatePlotReferences  = "integrateClass:updatePlotReferences"

   self->variableList = "============================================="
   self->pt1 = null
   self->pt2 = null
   self->regions = null # A array of structure holding the integral region information

   self->colors = [0xE6,0x00,0x49;
                    0x0B,0xB4,0xFF;
                    0x50,0xE9,0x91;
                    0xe6,0xD8,0x00;
                    0x9B,0x19,0xF5;
                    0xFF,0xA3,0x00;
                    0xDC,0x0A,0xB4;
                    0xB3,0xD4,0xFF;
                    0x00,0xBF,0xA0]

   self->symbols = ["opensquare",
                   "square",
                   "opencircle",
                   "circle",
                   "opentriangle",
                   "triangle",
                   "openinvtriangle",
                   "invtriangle",
                   "opendiamond",
                   "diamond"]
   self->nrRegions = 0
   self->xLabel = null

   self->fitPath = "$appdir$\\Macros\\Kea-Expert\\Processing Macros\\1DPlotAnalyser\\Fitting Functions"


endproc()


#######################################################
# Export the current integral list to a file
#######################################################

procedure(exportIntegrals, self)

   fileName = getfilename("save", "Save a to file", "Text files", "txt")

   if(fileName != "cancel")

      lst = dataList->list()
      sz = size(lst)
      x = matrix(sz-1)
      y = matrix(sz-1)
      for(k = 1 to sz-1)
         (xStr,yStr) = scanstr(lst[k],"%1|%2")
         x[k-1]= eval(xStr)
         y[k-1]= eval(yStr)
      next(k)

      export1dpar("ab","ascii",
                  "xyrc", "xydata",
                  "delimiter","comma")
      export1d(x,y,fileName)

   endif


endproc()

#######################################################
# Remove an integral and redraw the plot
#######################################################

procedure(updatePlotReferences, self, n)

   n = curwin()->winNr
   pp = getobj(n,1)
   if(n == 1)
      self->pt2 = pp->subplot(1,1)
   elseif(n == 2)
      self->pt1 = pp->subplot(1,1)
      self->pt2 = pp->subplot(1,2)
   endif

endproc()

#######################################################
# Remove an integral and redraw the plot
#######################################################

procedure(removeIntegral, self)

   n = curwin()->winNr
   pp = getobj(n,1)

   (w,h) = pp->size
   if(w == 1 & h == 2)
      self->pt1 = pp->subplot(1,1)
      self->pt2 = pp->subplot(1,2)
   else
      func1d("multiplot 2*1")
      self->pt1 = pp->subplot(1,1)
      self->pt2 = pp->subplot(1,2)
      self->pt1->rmlines()
      self->pt2->rmlines()
      self->pt2->clear()
   endif

   curplot(self->pt1)
   statusBar->text("Select point inside integral")
   pos1 = getx("value")

# Sometimes the clear button is left highlighted after getx
   clearButton->dehover("true")

   found = 0
   for(k = 0 to self->nrRegions-1)
      if(self->regions->symbols[k] != -1)
         left = self->regions->loc[0,k]
         right = self->regions->loc[1,k]
         if(pos1 >= left & pos1 <= right)
            self->pt1->rmlines(left)
            self->pt1->rmlines(right)
            self->regions->symbols[k] = -1
         else
            found = 1
         endif
      endif
   next(k)
   if(found == 0)
      self->clearIntegrals()
   else
      self->drawIntegratedData()
   endif

   statusBar->text("")

   curplot(self->pt1)

endproc()


#######################################################
# Select a region in pt1 interactively 
# integrate the region and plot the result in pt2
#######################################################

procedure(integratePeak, self)

# Organise the plot if it is new and get plot references
   n = curwin()->winNr

# Allow access to window variable in 1DPlotAnalyser
   guiwinnr(n)
   pp = getobj(n,1)
   (w,h) = pp->size
   if(w == 1 & h == 2)
      self->pt1 = pp->subplot(1,1)
      self->pt2 = pp->subplot(1,2)
   else
      func1d("multiplot 2*1")
      self->pt1 = pp->subplot(1,1)
      self->pt2 = pp->subplot(1,2)
      self->pt1->rmlines()
      self->pt2->rmlines()
      self->pt2->clear()
   endif

# Select the stacked plot
   curplot(self->pt1)
   sz = self->nrRegions
   nrCol = retvar(size(self->colors),2)
   color = self->colors[~,sz % nrCol]
   symbol = sz % size(self->symbols)

# Choose the integral region
   statusBar->text("Select points either side of peak")
   pos1 = getx("value")
   self->pt1->addline(pos1,-inf,pos1,inf,color,2,"solid")
   statusBar->text("Select other side of peak")
   pos2 = getx("value")
   self->pt1->addline(pos2,-inf,pos2,inf,color,2,"solid")
   if(pos1 > pos2)
      swapvar(pos1,pos2)
   endif

   avgPPM = (pos1+pos2)/2
   getobj(n,2)->text("")

# Sometimes these buttons are left highlighted so redraw
   rmButton->dehover("true")
   clearButton->dehover("true")

# Save this region
   if(self->regions == null)
     # Intialize region structure
      self->regions = struct()
      self->regions->loc = matrix(2,1)
      self->regions->loc[0,0] = pos1
      self->regions->loc[1,0] = pos2
      self->regions->dataZ = null
      self->regions->dataInt = null
      self->regions->fitInt = null
      self->regions->xAxis = null
      self->regions->colors = color
      self->regions->symbols = [symbol]
   else
    # Add the new region selected
      pos = matrix(2)
      pos[0] = pos1
      pos[1] = pos2
      self->regions->loc = join(self->regions->loc, pos, "horiz")
      self->regions->colors = join(self->regions->colors, color, "horiz")
      self->regions->symbols = join(self->regions->symbols, [symbol])
   endif
   self->nrRegions = self->nrRegions + 1

   self->xLabel = null
   self->yLabel = null

# Get the z axis data from the trace names
   tracelst = self->pt1->tracelist()
   sz = size(tracelst)
   z = matrix(sz)
   err = 0
   for(k = 0 to sz-1)
      txt = self->pt1->trace(k)->name
      try
         (protocol,comment) = scanstr(txt,"%1(%2)")
      catch
         comment = txt
      endtry
      if(isfloat(comment))
         z[k] = eval(comment)
      else
         z[k] = k
         err = 1
      endif
   next(k)
   if(err)
      print("Data abscissa not recorded - using index\n")
   endif

# Integrate the stacked plot data 
   ints = matrix(sz)
   for(k = 0 to sz-1)
      (x,y) = self->pt1->trace(k)->getdata
     # off = (avg(y[0:100]) + avg(y[-100:-1]))/2
     # y = y - off
      ints[k] = integvector(x,real(y),pos1,pos2)
   next(k)

# Allow for white wash mode
   if(z[0] > z[-1])
      z = reflect(z)
      ints = reflect(ints)
   endif

# Copy the z and integral data pairs into the dataInfo list 
   dataInfo = list(sz+1)
   dataZArray = matrix(sz)
   dataIntArray = matrix(sz)
   dataInfo[0] = "x|y"
   for(k = 1 to sz)
      dataInfo[k] = "$z[k-1]$|$ints[k-1]$"  
   next(k)
   dataList->nrcolumns(2)
   dataList->list(dataInfo)
   dataList->color([0,0,128,0])
   dataList->colwidth([0.3,0.7])
   rawDataGB->label("Raw Data ($pos1,1.1f$ to $pos2,1.1f$ ppm)")

# Record the z and integral data into the regions structure
   self->regions->dataZ = z
   self->regions->dataInt = join(self->regions->dataInt,ints,"horiz")
   self->regions->fitInt = join(self->regions->fitInt,matrix(sz*10)+nan,"horiz")
   self->regions->xAxis = join(self->regions->xAxis,z,"horiz")

# Plot the integral data
   self->drawIntegratedData()

# Fit if requested
   if(autoFit->text == "true")
      if(fitList->text == null)
         message("Error","Please select a fit function\rand try again.","error")
         return
      endif
      idx = retvar(size(self->regions->dataInt),2)-1
      self->fitToData(idx)
   endif

# Leave the integral data selected
   curplot(self->pt2)

endproc()

#######################################################
# Update the integrated data in plot pt2
#######################################################

procedure(drawIntegratedData, self, mode="linear")

# Update the color and symbol for each region
   sz = self->nrRegions

   curplot(self->pt2)
   try
      trcNr = curtrace()->id # The current trace nr
   catch
      trcNr = -1
   endtry

   self->pt2->draw("false")
   self->pt2->hold("off")

   for(k = 0 to self->nrRegions-1)

      if(self->regions->symbols[k] >= 0)

         symbol = self->symbols[self->regions->symbols[k]]
         x = self->regions->xAxis[~,k]
         y = self->regions->dataInt[~,k]
         fit = self->regions->fitInt[~,k]
         color = self->regions->colors[~,k]
      
       # Strip out negative values from raw data
         if(mode == "log")
            y1 = [y[0]]
            x1 = [x[0]]
            w = 0
            for(q = 0 to size(x)-1)
               if(y[q] > 0)
                  y1 = join(y1,[y[q]])
                  x1 = join(x1,[x[q]])
                  w = w + 1
               endif
           next(q)
         else
            x1 = x
            y1 = y
         endif

      # Draw all raw and fitted data
         n = self->pt2->plot(x1,y1,"symbolshape",symbol,
                             "symbolcolor",color,
                             "tracecolor",color,
                             "tracetype","none")
   
         self->pt2->hold("on")

         ppmLoc = self->regions->loc[~,k]
   
         self->pt2->trace(n)->name("raw $k$ $ppmLoc[0],1.1f$ to $ppmLoc[1],1.1f$")

         if(fit[0] != nan)
            xLarge = interp(x,size(x)*10)
            m = self->pt2->plot(xLarge,fit,"symbolshape","none",
                                "symbolcolor",color,
                                "tracecolor",color,
                                "tracetype","lines")
   
            self->pt2->trace(m)->name("fit $k$ $ppmLoc[0],1.1f$ to $ppmLoc[1],1.1f$")
   
         endif
      endif

   next(k)
   self->pt2->axes->ymapping(mode)
   self->pt2->grid->xgrid("on")
   self->pt2->grid->ygrid("on")
   self->pt2->grid->finexgrid("on")
   self->pt2->grid->fineygrid("on")
   self->pt2->title("Integrated data")
   if(self->yLabel != null)
      self->pt2->ylabel(self->yLabel)
   else
      self->pt2->ylabel("Integral")
   endif
   if(self->xLabel != null)
      self->pt2->xlabel(self->xLabel)
   else
      self->pt2->xlabel(self->pt1->ylabel->text)
   endif
   self->pt2->hold("off")
   self->pt2->draw("true")
#   if(trcNr != -1)
#      curtrace(trcNr) # Restore current trace
#   endif
   curplot(self->pt2)

endproc()

#######################################################
# Clear all the integral data
#######################################################
procedure(clearIntegrals, self)

   self->nrRegions = 0
   self->regions->dataInt = null
   self->regions->fitInt = null
   self->regions->xAxis = null
   self->regions->loc = null
   self->regions->symbols = null
   self->regions->colors = null
   self->pt1->rmlines()
   self->pt2->clear()

endproc()

#######################################################
# Open the fit editor to allow a new fit to be designed
#######################################################
procedure(addFit, self)

   fittingUI("Add Fit")

endproc()

#######################################################
# Remove the selected fit file
#######################################################
procedure(deleteFit, self)

   txt = fitList->text()
   if(txt == null)
      return
   endif

# Get the fit to delete
   (name,func) = scanstr(txt,"%1|%2")
   if(query("Warning","Do you really want to delete the file: $name$") == "no")
      return
   endif

# Delete it
   cd(self->fitPath)
   if(isfile("$name$.mac"))
      rmfile("$name$.mac")
      toggleIntegrate:generateFitList()
   endif

endproc()


#######################################################
# Open the fit editor to allow a fit to be edited
#######################################################
procedure(editFit, self)

   txt = fitList->text()
   if(txt != null)
      (name,func) = scanstr(txt,"%1|%2")
      fittingUI(name)
   endif

endproc()

#######################################################
# Refresh the fit list
#######################################################
procedure(refreshList, self)

  toggleIntegrate:generateFitList()

endproc()

#######################################################
# Try and fit the currently selected function to 
# all integrate data curves
#######################################################
procedure(fitAll, self)

   if(fitList->text() == null)
      message("Error","Please select a fit function\rand try again.","error")
      return
   endif

   self->pt2->parent->draw("false")
   print("\n\n ------------------ Fit results ------------------ \n\n")
   for(k = 0 to self->nrRegions-1)
      if(self->regions->symbols[k] != -1)
         result = self->fitToData(k)
         if(result == null)
            return
         endif
         if(k == 0)
            print("   Fit function '$result->fitName$': $result->func$ \n\n")
         endif
         ppm = self->regions->loc[~,k]
         print("   ($ppm[0],1.2f$ to $ppm[1],1.2f$) ppm\n")
         for(k = 0 to result->n-1)
            num = single(eval("result->par->p$k$"))
            err = single(eval("result->par->p$k$err"))
            if(err == 0 | isinf(err))
               print("      p$k$ = $num,g$\n")
               poorFit = 1
            else
               print("      p$k$ = $errorstr(num,err,2)$   ($abs(100*err/num),1.2g$%)\n")
               poorFit = 0
            endif
         next(k)
         if(poorFit)
            pr("   (Poor fit - uncertainties unavailable)\n")
         endif
         print("\n")
      endif
   next(k)
   print(" ------------------------------------------------- \n\n")

   self->pt2->parent->draw("true")

endproc()

#######################################################
# Fit the selected fit function to the currently 
# selected integrated data or by idx if specified
#######################################################
procedure(fitToData, self, idx=null)
 
# Get the trace labels - they become the default x axis for fitting
   x = self->regions->dataZ
   if(idx == null)
      name = curtrace()->name
      (type, nr, range) = scanstr(name,"%1 %2 %3")
      idx = eval(nr)
   endif
   y = self->regions->dataInt[~,idx]
   sz = size(x)
   txt = fitList->text()

   self->xLabel = null
   self->yLabel = null

# Get the fit function name and form
   (name,func) = scanstr(txt,"%1|%2")

   bak = getcwd()

   # 'info' might contain addition data from the main experiment macro
   proc = gData->curExpt->protocol+":getExptInfo"
   protocol = gData->curExpt->protocol
   path = gData->findPP(protocol)
   if(path == null)
      info = null
   else
      if(isproc(path,protocol,"getExptInfo"))
         info = proc()
      else
         info = null
      endif
   endif

   # The fitting macros are stored here
   path = self->fitPath
   cd(path)

   # Import the current one for efficiency
   import(name,path,"local")

   # We may need to preprocess the data - at least return initial search
   # values an x-axis label and y-axis mapping more
   if(isproc(path,name,"preprocess"))
       proc = "$name$:preprocess"
      (init, x, self->xLabel, self->yLabel, yMapping) = proc(x, y, info)
   else
      pr("Aborting fit: missing procedure $name$:preprocess\n")
   endif

   # Perform the non-linear fit returning the parameters in a structure
   try
      (par,chisq) = nlinfitd(x,y,name,"gj",init,0,"no",100,"struct0")
   catch
      pr ("\n  Non-linear fit failed. Try changing initial conditions, model or fit method\n")
      return(null)
   endtry

   # Generate the fit function but at 10x closer x-axis sampling
   f = name(interp(x,sz*10),par)

   # Might need to perform some post processing on the parameters
   if(isproc(path,name,"postprocess"))
      proc = "$name$:postprocess"
      par = proc(par)
      assignstruct(par)
   endif

   # The number of parameters
   n = size(init)

   for(k = 0 to n-1)
      if(eval("par->p$k$err") == inf)
         assign("par->p$k$err",0,"local")
         print("\n   Uncertainty in p$k$ is undefined")
      endif
   next(k)

  cd(bak)

# Record the fit axes
   self->regions->fitInt[~,idx] = f
   self->regions->xAxis[~,idx] = x

# Plot the data and fit
   self->drawIntegratedData(yMapping)

# Update the data list
   dataInfo = list(sz+1)
   dataZArray = matrix(sz)
   dataIntArray = matrix(sz)
   dataInfo[0] = "x|y"
   for(k = 1 to sz)
      dataInfo[k] = "$x[k-1]$|$y[k-1]$"  
   next(k)
   dataList->nrcolumns(2)
   dataList->list(dataInfo)
   dataList->color([0,0,128,0])
   dataList->colwidth([0.3,0.7])
   pos1 = self->regions->loc[0,idx]
   pos2 = self->regions->loc[1,idx]
   rawDataGB->label("Plotted Data ($pos1,1.1f$ to $pos2,1.1f$ ppm)")

# Pack the results in a structure
   result = struct(n = n, func=func, fitName=name, par=par, chisq=chisq)  

endproc(result)


procedure(readData, self)

   lst = dataList->list
   sz = size(lst)
   x = matrix(sz-1)
   y = matrix(sz-1)
   for(k = 1 to sz-1)
      (xv,yv) = scanstr(lst[k],"%1|%2")
      try
         x[k-1] = eval(xv)
      catch
         x[k-1] = k-1
      endtry
      y[k-1] = eval(yv)
   next(k)

endproc(x,y)

# Double click callback - update raw data with selected trace
procedure(dblClick, x, y)

# Make sure window variables are available for this callback
   curwin(curwin()->winnr)

# Update the raw data list
   trc = wvInt->pt2->curtrace()
   (x,y) = trc->getdata()
   sz = size(x)
   dataInfo = list(sz+1)
   dataInfo[0] = "x|y"
   for(k = 1 to sz)
     dataInfo[k] = "$x[k-1]$|$y[k-1]$"
   next(k)
   dataList->nrcolumns(2)
   dataList->list(dataInfo)
   dataList->color([0,0,128,0])
   dataList->colwidth([0.3,0.7])

endproc()

# Exp coefficients must be positive
procedure(PGSEBiExpFunc2, x, p1, p2, p3, p4)

   e2 = exp(-x*p2^2)
   e4 = exp(-x*p4^2)
   y = p1*e2 + p3*e4
   dydp1 = e2
   dydp3 = e4
   if(vartype(x) == "float")
      dydp2 = -2*x*p1*p2*e2
      dydp4 = -2*x*p3*p4*e4
   else
      dydp2 = -2*p1*p2*x.*e2
      dydp4 = -2*p3*p4*x.*e4
    endif

endproc(y,dydp1,dydp2,dydp3,dydp4)



