# ft function test (check that FFT and DFT produce same results)
procedure(ft_test1,verbose,delay)

   N = 64
   x = [0:1:N-1]/10
   y = exp((i-5)*x)
   
   # Calculate the DFT
   s = cmatrix(N)
   for(n = 0 to N-1)
      for(k = 0 to N-1)
         s[n] = s[n] + y[k]*exp(i*2*pi*k*n/N)
      next(k)
   next(n)
   
   clear1d()
plot(s)
   plot(ftshift(s))
   hold("on")
   plot(ft(y))
   trace("tracetype","none",
           "symbolshape","circle",
           "symbolcolor",[255,0,0])
   title("DFT and FFT comparison")
   
   hold("off")
   ratio = sum(mag(ft(y)))/sum(mag(ftshift(s)-ft(y)))
   if(ratio < 1e6) # Arbitrary large factor
      return(0, "Invalid result: ft()")
   endif

   pause(delay)


endproc(1,"")
