########################################################
#
# Frequency sweep pulse program used for probe tuning
# on the internal duplexer
#
########################################################

procedure(pulse_program,dir,mode,pars)

# Expose parameters for FX3 implementation
   if(nrArgs == 3)
      assignlist(pars)
   endif

# Interface description (name, label, x, y)
  interface = ["centFreq",    "Centre frequency (MHz)",   "tb",  "freq";
               "freqWidth",   "Frequency width (MHz)",    "tb",  "float,[0.01,50]";
               "nFreqSteps",  "Number of freq. steps",    "tb",  "integer";
               "aRF",         "RF amplitude",             "tb",  "float,[-72,0]";
               "repTime",     "Repetition time (ms)",     "tb",  "reptime"
               ]
#               "simDiv",      "Simulation",               "dv",  "simHelp";
 #              "simButton",   "Display sim controls",     "bt",  "addSimulator()"]

# Relationships to determine remaining variable values
   relationships = ["nPnts      = nrPnts",
                    "b1FreqCh1  = centFreq-freqWidth/2",
                    "fSweep     = linspace(b1FreqCh1,b1FreqCh1+freqWidth,nFreqSteps)",
                    "tFreq1     = gFX3->convertFrequency(fSweep)",
                    "tFreq2     = gFX3->convertFrequency(fSweep*10)",
                    "totPnts    = nFreqSteps",
                    "dStab      = 60",
                    "dRecover   = 2000",
                    "totTime    = acqTime",
                    "specialMode = \"wobble\""]

# Define the tabs and their order
   tabs = ["Pulse_sequence","Acquisition","Amplitude_Control","File_Settings"]

# These parameters will be changed between experiments
   variables = [""]

   mode = "w" + mode

# Pulse sequence
   initpp(dir)                    # Reset internal parameter list

      delay(10000)
      cleardata(nFreqSteps)
      setindex(tFreq1,0)
      setindex(tFreq2,0)
      loop("l1",nFreqSteps)         # Measure at nFreqSteps
         setrxfreq(tFreq2)            # Set the receiver frequency
         txon(mode,aRF,p1,tFreq1)     # Switch on Tx channel 1
         delay(dStab)                 # Wait for stability
         acquire("integrate",nPnts)      # Acquire and integrate
         txoff(mode)                  # Switch off the Tx
         incindex(tFreq1,2)           # Increment Tx frequency
         incindex(tFreq2,2)           # Increment Rx frequency
         delay(dRecover)              # Wait for HPA to recover
      endloop("l1")                 # Next measurement

   lst = endpp(0)                 # Return parameter list

# Phase cycle
   phaseList = [0;
                0]

endproc(lst,tabs,interface,relationships,variables,null,phaseList)


#####################################################
# Assign those parameters which should take their 
# values from the factory defaults when making a 
# new experiment
#####################################################

procedure(getFactoryBasedParameters, par)

   probeHeadPars = WobblePM:loadProbeHeadPars()
   assignlist(probeHeadPars)

   specPar = gData->specParameters
   if(specPar == null)
      return(null)
   endif

   par = ["centFreq = $b1Freq$"]

endproc(par)


#####################################################
# Generate some simulated WobblePM data based on the
# values stored in SimulationInfo
#####################################################

procedure(simulateNMR, dataSize)

   assignstruct(SimulationInfo)
   par = struct()
   fWidth = exptPar->freqWidth
   f0 = single(b1Freq+fWidth/2)
   par->minF = f0-fWidth/2
   par->maxF = f0+fWidth/2
   par->nrF = exptPar->nFreqSteps
   par->centFreq = b1Freq

   f = single(linvec(par->minF,par->maxF,par->nrF))

   # Check for interactive mode
   if(not(isvar("exptPar->offC1")) & not(isvar("exptPar->offC2")))
      offC1 = 0
      offC2 = 0
   else
      offC1 = exptPar->offC1  
      offC2 = exptPar->offC2
   endif   

   data = 1000*receiverGain*:calcRefCoef(f,f0,offC1,offC2)*exptPar->nrPnts

endproc(ctor(data))

#####################################################
# Here the reflection coefficent is calculated
# You can choose the bandwidth of the probe as well
# to define the coil resistance
#
#      ------ C2 ---- 
#     |    |          Rs = 50
#     L1   C1         |
#     R    |         Vin
#     |    |          |
#     ----------------
#          |
#         ---
#####################################################

procedure(calcRefCoef, f, f0, dC1, dC2)

   df = 50e3 # FWHM
   L = 10e-6 # This is not critical as this is a simulation
   R = 2*pi*df*L # From Q = wL/R and f/df = Q
   Rs = 50 # Source impedance

   (C1,C2) = :calcCaps(f0,L,R)

   C1 = C1*(1+dC1/1000*2/f0) # Scale by frequency to keep the
   C2 = C2*(1+dC2/1000*2/f0) # relative step sizes the same

   w = 2*pi*f*1e6
   XC1 = 1/(j*w*C1)
   XC2 = 1/(j*w*C2)  
   XL = j*w*L
   Z1 = XC1.*(XL+R)/(XC1+XL+R)
   Zp = Z1 + XC2 # Probe impedance

   r = (Zp - Rs)/(Zp + Rs) # Reflection coefficient

endproc(r)

#####################################################
# Calculate the capacitors by inverting 
# the above formula
#####################################################

procedure(calcCaps, f, L, R)

# The target probe impedance at the operating frequency
   Rt = 50 

# Real part of probe impedance should be 50 ohms
   w = 2*pi*f*1e6
   b = -2*Rt*w^2*L
   c = Rt-R
   a = Rt*(w^2*R^2 + w^4*L^2)
   C1 = (-b-sqrt(b^2-4*a*c))/(2*a)

# Imaginary part of probe imedance should be 0 ohms
   q = (1-w^2*L*C1)
   e = w^2*R^2*C1^2
   C2 = (q^2+e)/(w^2*L*q+e)

endproc(C1,C2)
